### PR TITLE
#8016 - AbstractIdGenerator:generate() - EntityManagerInterface inste…

### PR DESCRIPTION
**Pull request by ybenhssaien**
Use `AbstractIdGenerator:generate(EntityManagerInterface $em)` instead of `AbstractIdGenerator:generate(EntityManager $em)`

> Resolve : #8016

### CODE REVIEW

**Review by SenseException — CHANGES_REQUESTED** [review]
Changing the type hint to `EntityManagerInterface` would be a BC break for the 2.7 branch. I would expect this break in the next major 3.0 version.

**Comment by youssefbenhssaien** [comment]
Unfortunately yes, unless a minor version is planned between 2.7 and 2.8 (already include those changes) ...

**Comment by youssefbenhssaien** [comment]
Since most of Generator are instantiated directly by the framework, only CUSTOM generators will be impacted (< PHP 7.4)

**Comment by greg0ire** [comment]
> Unfortunately yes, unless a minor version is planned between 2.7 and 2.8 (already include those changes) ...

What do you mean by that? I don't understand…

> Since most of Generator are instantiated directly by the framework, only CUSTOM generators will be impacted (< PHP 7.4)

I don't think it makes the BC-break OK.

**Pull request closed without merging**
