### PR TITLE
Updated a link (hopefully :-)

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by Ocramius** [comment]
@ThomasLandauer thanks!

**Comment by ThomasLandauer** [comment]
Sorry, it didn't work out as I intended! :-( Please create a **link** to that anchor point on the 'Working with Associations' page.

**Comment by Ocramius** [comment]
@ThomasLandauer I'll revert the change - feel free to send in a new PR. Please compile the docs, if you aren't sure if it's doing what is expected.

**Comment by Ocramius** [comment]
Reverted in doctrine/doctrine2@d6eddab94fd71f18ee80b9d7f2a26fd4b32b246c

**Comment by ThomasLandauer** [comment]
Sorry, don't know how to do that....... :-(

**Pull request merged**
