### PR TITLE
Update doctrine/coding-standard in 2.x branch

### PR DESCRIPTION
**Pull request by ostrolucky**
See https://github.com/doctrine/doctrine2/pull/7328#discussion_r209202305

### CODE REVIEW

**Comment by Majkl578** [comment]
Any particular reason for this? We don't enforce CS in 2.x at all. For 2.7 we could at least consider the approach DBAL uses with CS checked on patch level.

**Comment by ostrolucky** [comment]
See referenced comment. Reason is to allow contributors to check new code if they want, without team member having to point them out.

Having CI not enforcing this does not mean we don't waste time by back and forth talk about CS in PRs by humans.

**Comment by Majkl578** [comment]
I don't see how this helps when you can't even run vendor/bin/phpcs.

**Comment by ostrolucky** [comment]
What do you mean I can't? I can and I did. I add `NewFile.php`, I run `vendor/bin/phpcs NewFile.php` and fix errors.

**Comment by ostrolucky** [comment]
Replaced with https://github.com/doctrine/doctrine2/pull/7473

**Pull request closed without merging**
