### PR TITLE
Fixing more links

### PR DESCRIPTION
**Pull request by ThomasLandauer**
The first two I missed in https://github.com/doctrine/orm/pull/9151
The third is probably older.
Shouldn't the chapter name be displayed as link text by default?? Are you sure that everything is set up correctly with the parser?

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
@SenseException I just wanted to start changing the order in the table (what I announced in https://github.com/doctrine/orm/pull/9131), but the overall structure of the page seems flawed:
[Load ClassMetadata Event](https://www.doctrine-project.org/projects/doctrine-orm/en/2.10/reference/events.html#load-classmetadata-event) is a top (!) level heading and "SchemaTool Events" too. And only the former events are included in the table, the latter aren't. I see two ways to fix this:

1. Include *all* events in the table. Merge all text starting at [Implementing Event Listeners](https://www.doctrine-project.org/projects/doctrine-orm/en/2.10/reference/events.html#implementing-event-listeners) into *one* section (called something like "List of Events").
2. Remove those "special" events (`onClassMetadataNotFound`, `postGenerateSchemaTable`, etc.) from the table, and leave their text sections where they are. But then move the table closer to "Implementing Event Listeners".

I have no preference, since I still haven't fully understood how all those topics belong together - that's why I started the "overview/table project" ;-)

**Comment by SenseException** [comment]
@ThomasLandauer Thanks again. Could you please combine your link-PRs into one PR instead of creating multiple ones? Maybe you could use this one and close the others.

**Comment by ThomasLandauer** [comment]
Just double-checked: They all have specific comments/questions :-(
I usually don't mix unrelated stuff (learned that from symfony-docs ;-) cause when *one* is problematic, at least the other can be merged in the meantime...
But I'll try to improve in the future :-)

**Comment by SenseException** [comment]
I don't want to have multiple commits with the same type of additions. In case of the links we can have them in one PR.

**Comment by ThomasLandauer** [comment]
OK. I integrated two, and closed one.

**Review by SenseException — APPROVED** [review]

**Pull request merged**
