### PR TITLE
issue: use doctrine:mapping:import with annotation lack of some database info

### PR DESCRIPTION
**Pull request by LinboLen**
generate extra information(such as `unsigned`, `comment`, `fixed`)

a generated use case
```
/**
 * Member
 *
 * @ORM\Table(name="member", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="mobile_UNIQUE", columns={"mobile"}),
 *     @ORM\UniqueConstraint(name="email_UNIQUE", columns={"email"})
 * })
 * @ORM\Entity
 */
class Member
{
    /**
     * @var integer
     *
     * @ORM\Column(name="member_id", type="integer", nullable=false, {"unsigned":false,"comment":"\u7528\u6237\u4e3b\u952e"})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $memberId;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=50, nullable=false, {"fixed":true,"comment":"\u7528\u6237\u540d"})
     */
    private $username;
}
```

### CODE REVIEW

**Comment by Ocramius** [comment]
wtf, no tests?!

**Comment by xsilen** [comment]
leave a note. will review and check this pr. 

modified
```
 str_replace(['(', ')'], ['\u40', '\u41'], json_encode($fieldMapping['options'], JSON_HEX_APOS|JSON_HEX_QUOT));
```

**Comment by xsilen** [comment]
use dump sql, missing primary key options info (such as `comment`, `unsigned`)
```
bin/console  doctrine:schema:create --dump-sql > ./sql2.sql   
```

**Comment by Ocramius** [comment]
@xsilen sorry for the initial snarky response (it was due to the `wtf.` in the issue description).

We need a test demonstrating the issue within the test suite of this repository.

Also, can you provide a more explicative PR title/description?

**Comment by xsilen** [comment]
ok, no problem

**Comment by xsilen** [comment]
this pr is edit in github online, i don't know how to edit this pr again. so i open another PR https://github.com/doctrine/doctrine2/pull/6323

**Pull request closed without merging**
