### PR TITLE
Fix: Use neutral pronouns

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses gender-neutral pronouns in the documentation

### CODE REVIEW

**Comment by SenseException** [comment]
Nice catch. Can you please rebase this PR to the 2.7 branch?

**Review by greg0ire — DISMISSED** [review]

**Comment by localheinz** [comment]
@SenseException 

Rebased!

**Review by greg0ire — DISMISSED** [review]

**Review by SenseException — APPROVED** [review]

**Review by SenseException — CHANGES_REQUESTED** [review]
I'm sorry, I was too fast on that. There are other pronouncs to be fixed:

* docs/en/reference/unitofwork.rst
  * "The developer can choose which kind of result he"
* docs/en/tutorials/getting-started.rst
  * "A User can see all his reported or assigned Bugs"

**Review by SenseException — APPROVED** [review]
Thank you.

**Comment by localheinz** [comment]
Thank you, @greg0ire and @SenseException!

**Pull request merged**
