### PR TITLE
Merge 2.13.x into 3.0.x

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by derrabus** [comment]
@greg0ire Can you have a look at the failing test? Did I do something wrong while merging your XSD validation feature up to 3.0.x?

**Comment by greg0ire** [comment]
I can take a look tonight. @Kern046, feel free to beat me to it.

**Comment by greg0ire** [comment]
Woops I completely forgot :sweat_smile: will try to fit that somewhere today.

**Comment by derrabus** [comment]
No worries.

**Review by greg0ire — APPROVED** [review]

**Comment by derrabus** [comment]
Thanks!

**Pull request merged**
