### PR TITLE
Fix EntityManagerHelper's documentation (it can't accept an array of paths)

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by greg0ire** [comment]
This branch is no longer maintained, you should probably target 2.6

**Comment by greg0ire** [comment]
I had a look at the history, it looks like this argument never existed, this is fishy…

**Review by greg0ire — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
So weird! Maybe the pull request for docs has been done at the same time as the contribution but the contribution was rejected?

👼

**Comment by greg0ire** [comment]
It was introduced in 997ef97521c2242916bc0dfe93f0abd7404b120e , which is the 8th commit in this repository, 9 years ago :P There didn't seem to be PRs at the time. Also, there was no code yet, it was just docs… `EntityManagerHelper` was introduced later on , in 5854bcab11ed8101d0f3c7e798fd669f17abab38 … go figure !

**Comment by lcobucci** [comment]
@mickaelandrieu thanks!

**Pull request merged**
