### PR TITLE
Updated all commands to use the SymfonyStyle

### PR DESCRIPTION
**Pull request by hiddewie**
The Symfony Style defines one default style for all commands using the Symfony Console code. Because Docrine has a number of commands, it would look nice if the commands made use of the Symfony style. This makes the output more human friendly to read.

Additions and comments are welcome, for example about which style to use for which messages.

All tests pass (although some commands are not tested). 

Some text about the style guide is written in http://symfony.com/blog/new-in-symfony-2-8-console-style-guide.

### CODE REVIEW

**Comment by Ocramius** [comment]
Looks good, but the `SymfonyStyle` was added in 2.7, if I remember correctly: therefore you should bump the dependency also in `composer.json`

**Comment by hiddewie** [comment]
Thanks. I forgot the version bump. Committed.

**Comment by lcobucci** [comment]
@hiddewie I'm truly sorry for that I didn't even see that we had this PR improving the commands. We indeed have much to improve on maintaining doctrine packages but I hope that you feel a bit happy with the fact that, even though is not your code, we now have better output for the commands.

**Comment by lcobucci** [comment]
Addressed by #6655

**Comment by hiddewie** [comment]
No problem, I am definitely happy the command output is more beautiful because of the other PR!

**Pull request closed without merging**
