### PR TITLE
Manually merge 2.7 into 2.8.x

### PR DESCRIPTION
**Pull request by greg0ire**
Not sure why doctrinebot didn't give it a try. I'm using the draft status so that this doesn't get merge by accident, which would result in 2 merges (not a big deal, but let's not needlessly confuse people). Once I get a green build and an approval, I will be able to push.

### CODE REVIEW

**Comment by greg0ire** [comment]
Not sure why we suddenly require `ext-dom` in GA… :thinking: `phar-io/manifest` wasn't upgraded.

**Comment by greg0ire** [comment]
Apparently the root cause is https://github.com/actions/virtual-environments/issues/981

**Review by beberlei — DISMISSED** [review]

**Comment by greg0ire** [comment]
I think I will wait for it to be fixed and revert 6393f8b00ab5e2facd996e511825685f82c46426

**Comment by greg0ire** [comment]
[It's supposed to be fixed now](https://github.com/actions/virtual-environments/issues/981#issuecomment-637724378)

**Pull request merged**
