### PR TITLE
Show full XML filename for dataset in test failure report

### PR DESCRIPTION
**Pull request by guilliamxavier**
Motivated by https://twitter.com/Ocramius/status/877414886963367937

Example output diff (in case of failure, e.g. while developing):

```diff
-1) Doctrine\Tests\ORM\Mapping\XmlMappingDriverTest::testValidateXmlSchema with data set #19 ('/z/tests/Doctrine/Tests/ORM/M...cm.xml')
+1) Doctrine\Tests\ORM\Mapping\XmlMappingDriverTest::testValidateXmlSchema with data set "Doctrine.Tests.Models.DDC3579.DDC3579User.dcm" ('/z/tests/Doctrine/Tests/ORM/M...cm.xml')
```

### CODE REVIEW

**Review by ostrolucky — DISMISSED** [review]

**Review by lcobucci — CHANGES_REQUESTED** [review]
Patch looks good but since this is not a bug fix it should be sent to `master` and ported back (by us) to `2.7`.

**Comment by guilliamxavier** [comment]
@lcobucci done

**Review by SenseException — APPROVED** [review]

**Comment by guilliamxavier** [comment]
@Ocramius: sorry to ping you but this may interest you

**Comment by Ocramius** [comment]
Seems like it misses tests though

**Comment by guilliamxavier** [comment]
> Seems like it misses tests though

Thanks but how do you write a test for a *test failure output*? 🤔

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
