### PR TITLE
Add primary key on temp table

### LINKED ISSUE #9768: sql_require_primary_key on mysql 8
### Bug Report
|    Q        |   A
|------------ | ------
| Version     | 2.12.2

#### Summary

We are running a managed database on DigitalOcean.
We are using a class table inheritance. If we now try to update one entity from this inheritance the `Doctrine\ORM\Query\Exec\MultiTableUpdateExecutor::class` is  called and creates a temporary table but the mysql option **sql_require_primary_key** is default **true**. So we are getting an SQL Exception that no primary key exists on this table.

We work around this issue setting **sql_require_primary_key** to **false** but the recommendation from DigitalOcean is:
*"For clusters with more than one node, we strongly recommend keeping sql_require_primary_key as True. Setting it to False may severely impact replication and cause issues."*

#### Current behavior
With **sql_require_primary_key** set to **true** we are getting a SQL Exception.

#### How to reproduce

Use a mysql8 Database, create an entity with  class table inheritance and try update an entity.

#### Expected behavior

Entity update works with **sql_require_primary_key** set to **true**.

### PR DESCRIPTION
**Pull request by wiseguy1394**
… to prevent exception on sql_require_primary_key=ON

Fixes #9768

### CODE REVIEW

**Comment by derrabus** [comment]
This PR adds the PK no matter what database engine we're using, right? Given that we use that temp table in an `IN()` statement later on, it might be a good idea to have the PK anyway, even if the `sql_require_primary_key` restriction is not in place.

Opinions on this, @greg0ire @beberlei?

I think we should enable `sql_require_primary_key` for MySQL 8 in our CI to make sure we don't introduce further regressions with that setting.

@wiseguy1394 Can you please run `./vendor/bin/phpcbf` and commit the result?

**Comment by greg0ire** [comment]
I don't have much to say on this, it seems fine, and I can't see how it would hurt.

**Comment by greg0ire** [comment]
Please associate your email address with your Github account, or change the
email in your commits to an address already associated with it. If you do not
want to expose your personal email address, you may use
`$userName@users.noreply.github.com`, that way we can still reach you through Github.
Additionally, you will get credit for this contribution on your Github profile.

**Comment by wiseguy1394** [comment]
Ah ok.. sry..I tried to changed the author for my commit, hope it worked.

**Comment by greg0ire** [comment]
It resulted in 3 commits, because I think you reset the author, then tried to push and noticed my commit, and you merged them both. I put it back to 1 commit. 

Please try again, but after doing: `git fetch --all && git reset --hard e06e215`. This will effectively use the commit I just pushed as a starting point.

**Review by beberlei — CHANGES_REQUESTED** [review]
Wouldn't this need all columns of the primary key of the entity instead just the first one? Otherwise it will lead to primary key duplicates for entities with multiple columns.

Does the `MultiTableDeleteExecutor` require the same change?

This will probably increase performance of these commands.

**Comment by wiseguy1394** [comment]
Is there anything I must/could do?

**Comment by derrabus** [comment]
> Is there anything I must/could do?

You could answer @beberlei's questions. 😉

**Comment by wiseguy1394** [comment]
> > Is there anything I must/could do?
> 
> You could answer @beberlei's questions. 😉

Oh ok, I answered the questions with yes in my commits ;)

**Review by derrabus — APPROVED** [review]

**Review by beberlei — APPROVED** [review]
Thank you!

**Pull request merged**
