### PR TITLE
[3.0][WIP][BC BREAK] Mapping as objects

### PR DESCRIPTION
**Pull request by guilhermeblanco**
This PullRequest is about changing the excessive usage of "untyped" arrays into objects such as FieldMapping, AssociationMapping (OneToOne, ManyToMany, ...). The reason for this is rooted into the PHP 5.4 and 5.5 changes to the object model that improve the space and memory efficiency of objects compared to arrays.
### Commit 2b68757

Removed `ClassMetadataInfo`. This was causing a dummy extends for no reason in our codebase.
Cleanup Mapping namespace. Allowed room for new mapping classes (FieldMetadata, AssociationMetadata et. al)
### Commit 0da09cb

Renamed `setIdentifierValues` to `assignIdentifier`. Burned on small TODO for 3.0
### Commit 22c69d3

Removed `columnNames` hash map. It was a marked TODO for 3.0, but also it was not necessary since all usages could be moved to use `fieldNames` easily and without any extra computational cost.
With the elimination of this array, cost of serializing and deserializing decreased and we won 0.5-1.0s from overall test suite run.
### Commit f2abed0

Removed `namespace` property. It was a marked TODO for 3.0.
There is only one usage of this and it is with no cache. Removing it in favour of inline computation made no difference in speed/memory.
### Commit 1ef65b0

Removed `requireSQLConversion` from field mapping. This is not very consistent across our codebase, since there are at least a hundred situations conversion is not done when it should.
However, the cost of removing this index, improved serialization/deserialization, but since conversion still needs to happen, the convert method is called every time, impacting in the performance of 0.1-0.2s in the overall unit test suite run.
With the removal of this method, field mapping is clean for `FieldMetadata` mapping, however, more optimizations are required to be done in order for this to happen. Also, making it consistent to always call type conversion exposed a flaw in our code where Type were not always being detected/mapped/provided which caused the subject of next commit. As next commit is done, we should come back and consistently review where fields are being used and properly apply type conversion across ORM.
### Commit 01179eb

Removed `getTypeOfColumn` method. **We should consider removing getTypeOfField too**, but it is enforced as a contract of Persistence ClassMetadata. This method is far from reliable and in a dozen of situations if returned null as field type (under inheritance, such as discriminator and also inherited fields). 
Switched cases to consume `PersisterHelper`, which should be the implementation of these methods in ClassMetadata, but unfortunately, CM does not have a pointer to its bound EntityManager (and I feel it should).
### Commit f3f25f0

Switch field mapping type index to hold a `Type` instance instead of string.
This is part 1 of 2 commits, since this is a very lengthy task. At this point it cannot be determined the speed improvements as it's now required to resolve the field type in many situations where it was assumed `string` type. Also, as part of this commit, a series of bugs were tackled, such as dependent test suites, undefined keys in association mapping, etc.
### Commits 75d2923 0f9a746 85a9a43 b38af2e

Part 2 of 2 commits, finalizing the `Type` instance instead of string in field mapping.
This should give us a clear information on speed improvement of holding instances instead of string.
In case it does not improve performance, we should still decouple some of the work done in previous commit and make an independent commit as there're many bug fixes.
### Commit ???

Consider optimizing inherited fields somehow as they create a series of new field mapping indexes
### Commit ???

Evaluate association mapping optimizations
### Commit ???

Evaluate embedded mapping optimizations
### Commit ???

Move field mapping to class instance. So far, I can foresee:

``` php
interface Property {}

class FieldMetadata implements Property {}

class InheritedFieldMetadata extends FieldMetadata {}
```

**TODO:** Figure it out on Field how inherited properties should be mapped.
### Commit ???

Move association mapping to class instance. So far, I can foresee:

``` php
abstract class AssociationMetadata implements Property {}

abstract class ToOneAssociationMetadata extends AssociationMetadata {}

abstract class ToManyAssociationMetadata extends AssociationMetadata {}

class OneToOneAssociationMetadata extends ToOneAssociationMetadata {}

class ManyToOneAssociationMetadata extends ToOneAssociationMetadata {}

class OneToManyAssociationMetadata extends ToManyAssociationMetadata {}

class ManyToManyAssociationMetadata extends ToManyAssociationMetadata {}
```

**TODO:** Figure it out on Association how inherited properties should be mapped.
## Final resolution
- Check performance and space for serialize/unserialize of metadata

### CODE REVIEW

**Comment by stof** [comment]
wouldn't they fit better in ``Mapping\Annotation`` ?

**Comment by guilhermeblanco** [comment]
@stof we'd be misusing mapping namespace. There're many more things that lineup closer to mapping than annotations.
I'm trying to reduce the package size as they'll increase a lot once I start creating the mapping information form array to objects (we used to have this before tbh)

**Comment by beberlei** [comment]
@guilhermeblanco I updated the Pull Request description a little with our reasoning.

**Comment by guilhermeblanco** [comment]
@beberlei I dunno how we should approach it. This change is pretty much ok as it is right now (cleaning up a bit some of todos for 3.0), however, I think it'll be better if I branch off this branch to do the work, then PR to this branch to evaluate performance impact.

**Comment by beberlei** [comment]
@guilhermeblanco We can compare performance when this branch is finished, against master, so i wouldnt branch off this one yet, just continue or?

**Comment by guilhermeblanco** [comment]
@beberlei I wouldn't work on this branch for that anymore. These changes are good enough even if we do not prove the point on mapping objects.

**Comment by guilhermeblanco** [comment]
@beberlei 0.5s out based on my last commit only (removing columnNames from ClassMetadata). I attribute this due to the size of unserializing it.

**Comment by beberlei** [comment]
@guilhermeblanco 0.5s what? The testsuite? How often?

**Comment by guilhermeblanco** [comment]
@beberlei yes, test suite...it's not consistent though, it ranges between 0.5-1.0s less.
I'll work on keep removing clutter of ClassMetadata until there's only either `fieldMappings` or `associationMappings` being used. This will simplify the work of creating classes for them later.

**Comment by guilhermeblanco** [comment]
Lost 0.2-0.5s in the overall test suite with the removal of `requireSQLConversion`. Conversion should always happen as of now, so the overhead of the extra call and fetching the type of TypeMap increased the memory consumption.
This will be optimized later once FieldMetadata gets introduced, because we'll serialize Type into its string representation and on wakeup will bring back its instance. It should bypass this loss as type retrieval happens everywhere in the codebase and it won't be necessary anymore.

**Comment by guilhermeblanco** [comment]
Depending on PHP version and DB driver, memory savings can reach up to 4s total and 40MB less resources usage.
Now considering the amount of work to get all types properly mapped, the overall logic increased, but with these savings I'd say it's a massive win so far! =)

**Pull request closed without merging**
