### PR TITLE
 Fix composer.json (doctrine/dbal)

### PR DESCRIPTION
**Pull request by andreclemente**
dev-snapshot/develop/2018-11-26 as 3.x-dev -> no matching package found

### CODE REVIEW

**Comment by Ocramius** [comment]
Is this supposed to target a specific dev branch?

**Comment by andreclemente** [comment]
dev-task/update-phpunit-8

**Comment by greg0ire** [comment]
This is an issue I observed on the `master` branch, and I was told the dbal branch should be `3.0.x-dev`, which implies changing quite a few method signatures. @guilhermeblanco is working on it.

**Comment by lcobucci** [comment]
Being handled by #7921, let's keep it there only :+1:

**Pull request closed without merging**
