### PR TITLE
Paginator: Skip limit subquery if not required

### PR DESCRIPTION
**Pull request by Seb33300**
This fixes https://github.com/doctrine/orm/issues/7829

### CODE REVIEW

**Comment by SenseException** [comment]
@lcobucci Are these `$query->setMaxResults(1);` in the older tests not an indicator for a breaking change that needs to target master?

**Comment by Seb33300** [comment]
I feel more like I fixed issues in older tests.

They are both related to the `Paginator` and tests was failing because they was expecting the Limit Subquery to be applied, but without adding a LIMIT to the query...
And an empty limit will return all data, so this is why my PR is intended to skip the limit query in this case.

The only BC that could happen is if you use the SQLLogger to count how many queries have been executed when using a Paginator without LIMIT.

**Comment by lcobucci** [comment]
@Seb33300 there's a small change which is not BC compatible here as highlighted by @SenseException: no length + usage of output walkers.

I'm working on solving this now because I think we can still put it in 2.7.0.

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@Seb33300 :ship: 

I marked this with `BC Break` because behaviour might change a tiny bit. I just forgot to document it in `UPGRADE.me`, will do it separately. Thanks for your contribution.

**Pull request merged**
