### PR TITLE
[Inheritance] Joined: Default discriminator map

### PR DESCRIPTION
**Pull request by comfortablynumb**
Hi all,

I know this topic was discussed a lot of times, but I wanted to give it a try anyway.

I want the discriminator map to be configured dynamically by doctrine instead of having to manually configure it myself. So I've digged into the code and the only place I've found (yet) to put the necessary code to make this happen is in the Drivers, just when they're loading the mapping information. So far, I've put a very simple piece of code in the AnnotationDriver to give it a try and I wrote a test for it. But before going on I wanted to ask you if it looks ok for you. 

I've tested it in an application I'm working on and, so far, it works.

So, in a brief, what this does is, if you have a class which is the root of a class table inheritance tree (JOINED type), you can let doctrine configure the DiscriminatorMap for you, filling it with all the subclasses of the root class. If, for some reason, the user needs to configure it by himself, then he can do it. If the DiscriminatorMap is set, Doctrine doesn't generate it.

I think this is useful. It's error prone to configure it manually every time a new class is added to the inheritance tree. And this is better in cases where you can't know which entities are present and which aren't (for example, think about pluggable modules in a modular application). There's a way to do it (although I didn't try it. Just read about it), but this is simpler and works out of the box.

Two things come to mind though:

1) Is there any special case this would cause problems that I don't know of?
2) If not then, Is there a better place to put this code so I don't have to implement it in all drivers? I've been looking at the ClassMetadataFactory class but I didn't find a place to put this code because it seems it's too late to calculate the discriminator map at the time this class is used. So, in case there is no other place, where should I refactor the logic? It feels uncomfortable to create a class just to put this simple logic on, but as drivers don't inherit from any class, I don't see another option.

I'll wait for your comments to continue with this.

Thanks!

### CODE REVIEW

**Comment by hal9087** [comment]
Hey guys, i'm a newbie, how to declare only the discriminator value for the child class?

**Comment by jmikola** [comment]
@DenisGorbachev: Sorry, I wasn't following this thread and just came across it. I'm not sure what this PR actually implements, but was there an equivalent PR opened on ODM that you can link me to?

**Comment by DenisGorbachev** [comment]
@jmikola I'm already using Meteor now, thanks!

**Comment by jmikola** [comment]
@DenisGorbachev: No worries :+1:

**Pull request closed without merging**
