### PR TITLE
Allow EntityManager::transational() to return non-null values

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by lcobucci** [comment]
@enumag could you please provide the reasons you need this change and also test cases for it?

**Comment by Ocramius** [comment]
The correct fix would be to return anything from the executed callable, but that's not fixable, as it is an interface BC break. See https://github.com/doctrine/doctrine2/blob/bfa9a31ad77ce769f8e78ab70c2083e75f623c7a/lib/Doctrine/ORM/EntityManagerInterface.php#L73-L84

**Comment by enumag** [comment]
@Ocramius Could it be changed in Doctrine 3.0?

**Comment by Ocramius** [comment]
Yes, can be done. You can send a patch against `develop`, changing the interface too.

**Comment by enumag** [comment]
Alright, thank you!

**Comment by enumag** [comment]
Note for myself: Create a second PR for Doctrine/DBAL with the same thing for Connection::transactional().

**Comment by enumag** [comment]
The transactional function is mentioned here in the docs: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html#approach-2-explicitly

**Pull request closed without merging**
