### PR TITLE
Resolve associations cache key not part of ResultSetMapping

### PR DESCRIPTION
**Pull request by giosh94mhz**
Yet another bug with 2nd level cache :) I cannot generate a proper test case (for now), so I try to explain the issue to sum up my change. This happens in `2.5`, `2.5-dev` and `dev-master` branches.
## the bug

I set up a DQL query which use `setCachable(true)`, and (almost) everything is configured to use 2nd level cache. While retrieving object from cache through the `DefaultQueryCache`, I got the following error:

```
Catchable Fatal Error: Object of class Doctrine\ORM\Cache\AssociationCacheEntry could not be converted to string
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php at line 2676
```

The error is triggered by an `AssociationCacheEntry` which is left behind during entity hydration.
## why it happen

I saw that in `DefaultQueryCache` the normal association cache resolution is overriden by `ResultSetMapping` resolution. This probably make sense, but the entity hydration is inlined (with a big `TODO` :) inside `DefaultQueryCache`, instead of using `DefaultEntityHydrator`.

I think that resolving only `Rsm` mapping is not enough. If the entity is cached through `DefaultEntityHydrator::buildCacheEntry`, there are also other association.
## my fix

I cannot provide a proper solution for merging the Rsm logic into `DefaultEntityHydrator`, to get rid of the TODO. So I copied the relevant part to `DefaultQueryCache`, just to fix the issue for now.

### CODE REVIEW

**Comment by piotrantosik** [comment]
I have same error, but this solution is not compatible with 2.5

**Comment by giosh94mhz** [comment]
@piotrantosik what do you mean with "is not compatible"? The patch don't apply, or it generates new bugs?

Btw, the Travis failure is not related to my patch, but with an issue with `php-coveralls` and `PHP 5.4`

**Comment by piotrantosik** [comment]
Is not apply - code in 2.5 branch i different than master

**Comment by giosh94mhz** [comment]
@piotrantosik I see. I've reviewed the changes to `DefaultQueryCache` in master. You may just copy the whole class, since the only changes introduced are bugfixes. Download [from here](https://raw.githubusercontent.com/giosh94mhz/doctrine2/bug_some_assoc_cache_key_left_behind/lib/Doctrine/ORM/Cache/DefaultQueryCache.php), I'll be happy to hear your feedback.

**Comment by lcobucci** [comment]
@giosh94mhz I'll check this late this evening (I'm also having this problem)

**Comment by giosh94mhz** [comment]
@lcobucci Two years have passed and I barely remember this bug, since lot of things changed since then. But you have all my support, if you need it.

I've checked the error on travis BTW, but seems unrelated.

**Comment by lcobucci** [comment]
@giosh94mhz indeed, a LOT of things changes. I just saw that I'm not having exactly this problem but is something similar.

I spent the whole night trying to reproduce this on a test and it was just impossible 😞 will continue on this...

**Comment by lcobucci** [comment]
I was unable to reproduce things on a test case so I conclude that we don't have that issue.
This PR introduces a different thing that is fetching associations that weren't added in the query as joins which is wrong IMO.

Closing as `wont-fix`.

**Comment by magnetik** [comment]
I'm having this (or more probably #5792). I did not came up with a functional test either but
- I have entity A with several ManyToOne association to B, two with fetch eager and one without.
- After updating A with a reference to a different B, when getting A from cache, A gets all association to B except the one that DO NOT have "fetch eager"

**Comment by lcobucci** [comment]
@magnetik did you check it using `2.6.x-dev`? We fixed a LOT of issues regarding L2C there.

**Comment by magnetik** [comment]
Well I over extended the scope of this bug because I do not have this exact exception but only the "consequences". 

I cannot reproduce as functional test in the 2.x or master branch. I'll open a new bug if I can come up with something.

**Pull request closed without merging**
