### PR TITLE
Add versionadded note for EntityRepository::count

### PR DESCRIPTION
**Pull request by teohhanhui**
Feature added in #6003

### CODE REVIEW

**Comment by Ocramius** [comment]
@teohhanhui sorry, that's not the kind of improvement I suggested in #6003: I was thinking of versioning the entire docs per tag. That is a major piece of work that needs undertaking before ORM 3.x anyway.

**Comment by teohhanhui** [comment]
I know.

**Comment by teohhanhui** [comment]
I don't have the time and resources for that. Sorry...

**Comment by Ocramius** [comment]
@teohhanhui no worries. Meanwhile, closing here. If you want to eventually create an issue on the other repo, outlining how the versioning could be achieved, that would already help a lot.

**Pull request closed without merging**
