### PR TITLE
null values in cached entity fix

### PR DESCRIPTION
**Pull request by AlexSmerw**
This is fix for issue [7735](https://github.com/doctrine/orm/issues/7735)

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
This kind of change requires a test case that fails before the patch, and passes after the patch.

**Comment by Ocramius** [comment]
@AlexSmerw could you also target `2.6` with this fix, please?

**Comment by AlexSmerw** [comment]
> @AlexSmerw could you also target `2.6` with this fix, please?

Done https://github.com/doctrine/orm/pull/7750

**Comment by lcobucci** [comment]
Closing here to keep the fix only for 2.6, we'll port it to master once things are integrated.

**Pull request closed without merging**
