### PR TITLE
problem with LimitSubqueryOutputWalker when use InheritanceType

### PR DESCRIPTION
**Pull request by alexander-orabey**
When we use InheritanceType ("SINGLE_TABLE") catch exception that field in joined class does not exist in base class.

### CODE REVIEW

**Comment by shustrik** [comment]
problem with #1220  on rebuildOrderByClauseForOuterScope when quoteStrategy call getColumnName

**Comment by zeroedin-bill** [comment]
@shustrik This should be fixed in #1349

**Comment by shustrik** [comment]
@zeroedin-bill  thanks. @Ocramius can you check and merge?

**Comment by zeroedin-bill** [comment]
Tests merged into #1353

**Comment by Ocramius** [comment]
Closing: to be handled in #1353

**Pull request closed without merging**
