### PR TITLE
allow ManyToManyPersister to handle identification types

### PR DESCRIPTION
**Pull request by dadamssg**
Not sure if I've followed all of the directions in the contributing guide accordingly but [this is the issue](http://www.doctrine-project.org/jira/browse/DDC-3785) i created.

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
@dadamssg While patch seems correct, I'd like if possible to see what was the issue you experienced that this patch solves.
Ideally, through a phpunit test case.

**Comment by dadamssg** [comment]
@guilhermeblanco crap. this patch is not correct. i hastily missed adding the $types as the 3rd argument.

**Comment by guilhermeblanco** [comment]
@dadamssg you don't need to close it... just commit the other fix and rebase squashing the commits into one.

**Comment by dadamssg** [comment]
@guilhermeblanco sorry. I'm terrible with git. I deleted my local branch, created a new one with the same name and --forced that to [my github](https://github.com/dadamssg/doctrine2/tree/DDC-3785). I think I may have orphaned this pull requests branch and made this all way more complicated than it should be :(

I'll reopen this one if you can guide me through it, leave this one closed and create a new pull request, or not touch anything and let you guys handle the bug fix :/

**Comment by guilhermeblanco** [comment]
@dadamssg oh... your force a push. There's nothing to do anymore. Please open a new PR.
I still need a test where you experienced this issue to prevent future breakages.

**Comment by dadamssg** [comment]
@guilhermeblanco not sure i'm going to be able to do that either. I just downloaded phing and attempted to run the tests and i get 

```
$ php ../phing-latest.phar 
Buildfile: /Users/dadamssg/Code/doctrine2/build.xml
 [property] Loading /Users/dadamssg/Code/doctrine2/build.properties

BUILD FAILED
/Users/dadamssg/Code/doctrine2/build.xml:72:19: Could not create task/type: 'macrodef'. Make sure that this class has been declared using taskdef / typedef.
Total time: 0.1221 seconds
```

I've never used phing before.

**Comment by dadamssg** [comment]
i'm just going to composer install and get phpunit and try to work with that. I'm not sure i should be attempting to use phing at all anyways

**Comment by guilhermeblanco** [comment]
@dadamssg This should be enough for you to run tests:

```
git clone ... orm
cd orm
composer install
./vendor/bin/phpunit
```

Look at examples on how to reproduce test cases in the path: `tests/Doctrine/Tests/ORM/Functional/Ticket`

**Comment by dadamssg** [comment]
@guilhermeblanco I attempted to get a handle on how to write a test but unfortunately there's too much going on for me to come up with anything. I think i need a better understanding of doctrine's internals to write a working test.

**Pull request closed without merging**
