### PR TITLE
#7763 escape quotes in field comments

### PR DESCRIPTION
**Pull request by guillaume-a**
This is my attempt to PR this.
Tell me if it's okay or not.

### CODE REVIEW

**Review by SenseException — CHANGES_REQUESTED** [review]
Thank you for your pull request. Please fix these 2 cs issues:

```
FILE: lib/Doctrine/ORM/Tools/EntityGenerator.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------------
 1682 | ERROR | [x] Function str_replace() should not be referenced via a
      |       |     fallback global name, but via a use statement.
      |       |     (SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly.ReferenceViaFallbackGlobalName)
 1682 | ERROR | [x] Concat operator must be surrounded by a single space
      |       |     (Squiz.Strings.ConcatenationSpacing.PaddingFound)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by guillaume-a** [comment]
I did the change, i don't know the process now :)
Changes are pushed.

**Review by SenseException — DISMISSED** [review]
This PR is probably fine, but be aware that entity creation with the `EntityGenerator` was dropped in the next major release and that there won't be a generator or a generator command anymore: https://github.com/doctrine/orm/blob/master/UPGRADE.md#bc-break-removed-code-generators-and-related-console-commands

**Comment by guillaume-a** [comment]
Thanks.

**Review by greg0ire — DISMISSED** [review]

**Review by lcobucci — APPROVED** [review]
@guillaume-a this PR completely passed by my reviews, sorry. As mentioned before, this class is going to die a terrible death but I'm fine with patching it up once more.

**Comment by lcobucci** [comment]
@guillaume-a thanks for your contribution :+1:

**Pull request merged**
