### PR TITLE
Replace "Blacklist" with "Banlist" in join example

### LINKED ISSUE #8173: Replace documentation example of "Blacklist" join query
https://github.com/doctrine/orm/blob/master/docs/en/reference/dql-doctrine-query-language.rst#arbitrary-join

shows an example of a join query with a "Blacklist" table. This could easily be changed to a more sensible example. I would suggest "Banlist" as alternative example.

### PR DESCRIPTION
**Pull request by albe**
Resolves #8173

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

**Review by SenseException — CHANGES_REQUESTED** [review]
@albe Thank you for the PR. Can you please target the 2.7 branch for this? I'd like to have this in the currently supported versions too.

Example how to change your base branch:
https://makandracards.com/makandra/10173-git-how-to-rebase-your-feature-branch-from-one-branch-to-another

**Comment by greg0ire** [comment]
@SenseException there is another PR for 2.7 already, but I thought this one was worth having too, since there are a lot more changes.

**Comment by albe** [comment]
Yep, see https://github.com/doctrine/orm/pull/8174 - sorry, should have linked the two PRs in the first place :/

**Review by SenseException — APPROVED** [review]
Okay, then #8174 will also cover the 2.8 branch. Thank you @albe

**Comment by greg0ire** [comment]
Thanks @albe!

**Pull request merged**
