### PR TITLE
Conversion to PHP 5.4's short array syntax

### PR DESCRIPTION
**Pull request by BenMorel**
Now that the minimum PHP version is 5.4, it would be good to encourage the use of the short array syntax `[]`.
Converting the existing codebase to this syntax will promote this good practice and encourage everyone to follow it.

I have converted the codebase with [a tool](https://gist.github.com/BenMorel/6994483) I wrote for personal projects:

```
find doctrine2 -type f -name '*.php' -exec php short-array-syntax-converter.php {} \;
```

The number of changes is quite large, but I'm confident that nothing is broken, and the passing tests confirm this.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by beberlei** [comment]
-1 at this point, this probably breaks all the other patches out there and introduces a difference between master and 2.5 that makes merges into the stable branches very cumbersome. I would say somewhen before 2.6 - Unless @Ocramius  wants to merge this for 2.5 already.

**Comment by Ocramius** [comment]
I also disagree on this for now: to be done with a shorter PR queue.

**Comment by deeky666** [comment]
Me too. Making things overly complicated for no real gain.

**Comment by Ocramius** [comment]
Note that the just merged PR already conflicted here :X

**Comment by BenMorel** [comment]
I understand, although I would point out that the conflicts would be easy to solve.
It's up to you, really. Feel free to use my tool to convert any file(s).

**Comment by Ocramius** [comment]
@BenMorel eh, conflicts are always a pain to deal with. A simple comment change can cause diffs to really go bananas.

**Comment by BenMorel** [comment]
Just resolved this conflict, that took me one minute, for what it's worth :)

**Comment by stof** [comment]
@BenMorel but this would cause conflicts for **all** bugfix backports for as long as Doctrine 2.4 is still supported. This is why it would be a pain.

**Comment by BenMorel** [comment]
OK I understand, no worries!

**Comment by Ocramius** [comment]
Closing  - same reason as #1606

**Pull request closed without merging**
