### PR TITLE
Do not allow cache clearing with APCu

### PR DESCRIPTION
**Pull request by shadowhand**
Refs https://github.com/doctrine/doctrine2/pull/7493#pullrequestreview-180007007

### CODE REVIEW

**Review by greg0ire — CHANGES_REQUESTED** [review]

**Comment by shadowhand** [comment]
@greg0ire all of the LogicExceptions have the same grammar error... do I fix all of them?

**Comment by greg0ire** [comment]
It's up to you I think, but do not introduce more of them :P

**Review by Ocramius — CHANGES_REQUESTED** [review]
This is a BC break which we need to document in `UPGRADE.md`

**Comment by shadowhand** [comment]
@greg0ire wording for all exceptions updated.

@Ocramius `UPGRADE.md` has been updated.

**Review by greg0ire — DISMISSED** [review]

**Comment by Ocramius** [comment]
We'll need to target `master` here

**Comment by shadowhand** [comment]
@Ocramius doesn't targeting `master` imply version 3.0? I was really hoping to avoid that.

**Comment by shadowhand** [comment]
@Ocramius in my mind this is a bugfix release, since clearing cache with APCu driver did not actually perform the expected operation.

**Comment by greg0ire** [comment]
It was not doing anything, but now it throws, which means every deploy script that calls it will fail under the right circumstances. That makes it a BC-break. Plus the cache is still not cleared, so not a bugfix either I think. It's just a nice DX improvement. It you want it to land on lower branches, maybe make the bugfix a simple call to one of the methods of `OutputInterface` or trigger a deprecation (to be confirmed, not sure what the Doctrine policy would be for this). That wouldn't be a BC-break I think.

**Comment by Ocramius** [comment]
Yes, by producing just a warning, it would not be a BC break

**Comment by Ocramius** [comment]
No, that would be yet another BC break 😜

**Comment by shadowhand** [comment]
@Ocramius okay, and how do you want to handle `master` branch? Separate PR? I'm don't know how the merging from 2.6 to master is done.

**Comment by Ocramius** [comment]
That's done by us later on

**Comment by shadowhand** [comment]
@Ocramius okay, then how about I make this PR against 3.0 and then add a "backport" for 2.6 that replaces the exception with a warning?

**Comment by Ocramius** [comment]
Since you are aiming for an improvement, then just re-target this patch to `master` and call it a day

**Comment by shadowhand** [comment]
@Ocramius rebased to master.

**Comment by shadowhand** [comment]
@Ocramius tests are passing now.

**Review by Ocramius — APPROVED** [review]
:+1: thanks @shadowhand!

**Pull request merged**
