### PR TITLE
[WIP] Second level cache

### PR DESCRIPTION
**Pull request by FabioBatSilva**
Hi guys. :)

After a look into some implementations I end up with the following solution for the second level cache..

There is lot of work todo before merge it, but i'd like to get your thoughts before i go any further on this approach.
I hope my drafts are good enough to explain the idea :
### Cache strategies

```
* READ_ONLY (DEFAULT)   : ReadOnly cache can do reads, inserts and deletes, cannot perform updates or employ any locks.
* NONSTRICT_READ_WRITE  : Nonstrict Read Write Cache doesn’t employ any locks but can do reads, inserts , updates and deletes.
* READ_WRITE            : Read Write cache employs locks the entity before update/delete.
```
### classes / interfaces
- **Region** : 
  Defines a contract for accessing a entity/collection data cache. (Doesn’t employ any locks)
- **ConcurrentRegion** :
  Defines contract for concurrently managed data region. (Locks the data before update/delete.)
- **CacheKey / EntityCacheKey / CollectionCacheKey/ QueryCacheKey**:
  Defines entity / collection key to be stored in the cache region.
- **EntityHidrator / CollectionHidrator**
  Build cache entries and rebuild entities/colection from cache
- **CacheFactory**
  Factory from second level cache components
### Collection Caching

The most common use case is to cache entities. But we can also cache relationships. 
A “collection cache” caches the primary keys of entities that are members of a collection (OneToMany/ManyToMany). 
and each element will be cached into its region.

Only identifiers will be cached for collection. When a collection is read from the second level cache it will create proxies based on the cached identifiers, if the application needs to access an element, Doctrine will go to the cache to load the element data.
### Query Cache

The query cache does not cache the state of the actual entities in the result set; 
it caches only identifier values for an individual query.
So the query cache should always be used in conjunction with the second-level cache.
#### Query Cache validation

> ##### UpdateTimestampsCacheRegion (hibernate approach) :
> - The timestamp cache region keeps track of the last update for each table. (updated for each table modification)
> - A single timestamps region it's utilized by all query cache instances.
> - In most hibernate cache implementations is recommend do not configured cache timeout at all.
> - When a query is loaded from cache, the timestamp region is checked for all tables in the query. 
> - If the timestamp of the last update on a table is greater than the time the query results were cached,
>   Then the entry is removed and the query goes straight to the database.
#### INSERT :

```
*************************************************************************************************
UnitOfWork#commit
    Connection#beginTransaction
    Persister#executeInserts
    Connection#commit
    CachedPersister#afterTransactionComplete
        -> Region#put
*************************************************************************************************
                    | READ-ONLY             | NONSTRICT-READ-WRITE      | READ-WRITE            |
-------------------------------------------------------------------------------------------------
pre-insert          |                       |                           |                       |
-------------------------------------------------------------------------------------------------
on-insert           |                       |                           |                       |
-------------------------------------------------------------------------------------------------
after-transaction   | add item to the cache | add item to the cache     | add item to the cache |
-------------------------------------------------------------------------------------------------
```
#### UPDATE :

```
*************************************************************************************************
UnitOfWork#commit
    Connection#beginTransaction
    CachedPersister#update
        -> Region#lock
        -> execute
    Connection#commit
    CachedPersister#afterTransactionComplete
        -> Region#put
        -> Region#unlock
*************************************************************************************************
                    | READ-ONLY             | NONSTRICT-READ-WRITE      | READ-WRITE            |
-------------------------------------------------------------------------------------------------
pre-update          |                       |                           | lock item             |
-------------------------------------------------------------------------------------------------
on-update           | throws exception      |                           |                       |
-------------------------------------------------------------------------------------------------
after-transaction   |                       |  update item cache        | remove item cache     |
-------------------------------------------------------------------------------------------------
```
#### DELETE :

```
*************************************************************************************************
UnitOfWork#commit
    Connection#beginTransaction
    CachedPersister#delete
        -> Region#lock
        -> execute
    Connection#commit
    CachedPersister#afterTransactionComplete
        -> Region#evict
*************************************************************************************************
                    | READ-ONLY             | NONSTRICT-READ-WRITE      | READ-WRITE            |
-------------------------------------------------------------------------------------------------
pre-remove          |                       |                           |                       |
-------------------------------------------------------------------------------------------------
on-remove           |                       |                           | lock item             |
-------------------------------------------------------------------------------------------------
after-transaction   | remove item cache     |  remove item cache        | remove item cache     |
-------------------------------------------------------------------------------------------------
```
#### USAGE :

``` php
<?php

/**
 * @Entity
 * @Cache("NONSTRICT_READ_WRITE")
 */
class State
{
    /**
     * @Id
     * @GeneratedValue
     * @Column(type="integer")
     */
    protected $id;
    /**
     * @Column
     */
    protected $name;
    /**
     * @Cache()
     * @ManyToOne(targetEntity="Country")
     * @JoinColumn(name="country_id", referencedColumnName="id")
     */
    protected $country;
    /**
     * @Cache()
     * @OneToMany(targetEntity="City", mappedBy="state")
     */
    protected $cities;
}
```

``` php
<?php

$em->persist(new State($name, $country));
$em->flush();                                // Put into cache

$em->clear();                                // Clear entity manager

$state   = $em->find('Entity\State', 1);     // Retreive item from cache
$country = $state->getCountry();             // Retreive item from cache
$cities  = $state->getCities();              // Load from database and put into cache

$state->setName("New Name");
$em->persist($state);
$em->flush();                                // Update item cache

$em->clear();                                // Clear entity manager

$em->find('Entity\State', 1)->getCities();   // Retreive from cache


$em->getCache()->containsEntity('Entity\State', $state->getId())  // Check if the cache exists
$em->getCache()->evictEntity('Entity\State', $state->getId());    // Remove an entity from cache
$em->getCache()->evictEntityRegion('Entity\State');               // Remove all entities from cache

$em->getCache()->containsCollection('Entity\State', 'cities', $state->getId());   // Check if the cache exists        
$em->getCache()->evictCollection('Entity\State', 'cities', $state->getId());      // Remove an entity collection from cache
$em->getCache()->evictCollectionRegion('Entity\State', 'cities');                 // Remove all collections from cache

```
#### TODO :
- [x] Handle many to many collection
- [x] Handle inheritance
- [x] Remove/add colection items on update
- [x] Improve region tests
- [x] Improve cached persisters coverage
- [x] Implement xml / yml / php drivers
- [x] Implement transaction region _(Improve cache drivers)_
- [x] Implement query cache _**(need more tests)**_
- [x] Read and write region when using query cache
- [x] Update documentation
- [x] Implement cache cache hits and misses log
- [ ] .... ????

### CODE REVIEW

**Comment by MIHDashboard** [comment]
Hi, awesome work.

I'm using ZF2 + doctrine currently. Could you please tell me how to enable this feature using configuration files? I use module.config.php to configure my entitymanager. 

Followed the documentation at http://doctrine-orm.readthedocs.org/en/latest/reference/second-level-cache.html but it does not have an example of how to pass the setting as a configuration option.

I've tried putting it in the module.config.php in the orm_default section as second_level_cache_enabled, but that does not work.

Thanks.

Cheers.

**Comment by jarrettj** [comment]
Hi, awesome work.

I'm using ZF2 + doctrine currently. Could you please tell me how to enable this feature using configuration files? I use module.config.php to configure my entitymanager. 

Followed the documentation at http://doctrine-orm.readthedocs.org/en/latest/reference/second-level-cache.html but it does not have an example of how to pass the setting as a configuration option.

I've tried putting it in the module.config.php in the orm_default section as second_level_cache_enabled, but that does not work.

Thanks.

Cheers.

**Comment by FabianKoestring** [comment]
@jarrettj I think you have to wait for this pr to be merged.
https://github.com/doctrine/DoctrineORMModule/issues/295

**Comment by skafandri** [comment]
@jarrettj in your entity manager config add:
```
 second_level_cache:
                    enabled: true
                    region_cache_driver: memcached
                    regions:
                        region_name:
                            lifetime: 3600
                            type: default
```

**Comment by jarrettj** [comment]
@FabianKoestring I'm using the doctrine orm 2.5. Thought this had been merged already? Or do you mean that doctrine zend module needs changes merged in as well? Thanks dude.

**Comment by FabianKoestring** [comment]
@jarrettj I think so. ;)

**Comment by jarrettj** [comment]
@skafandri have you actually got it to work in zend framework 2 + doctrine? I tried adding your options to module.config.php:
        'configuration' => array(
            'orm_default' => array(
                'generate_proxies'  => true,
                'proxy_dir'         => __DIR__ . '/../src/Application/Proxy',
                'proxy_namespace'   => 'Application\Proxy',
                'filters'           => array(),
                'string_functions'   => array(
                    'REGEXP'  => 'Application\DoctrineFunction\Regexp'
                ),
                'second_level_cache' => array(
                        'enabled' => true,
                        'region_cache_driver' => 'memcached',
                        'regions' => array(
                                        'region_name' => '',
                                        'lifetime' => 3600,
                                        'type' => 'default'
                            )
                ),
            )
        ),

Sorry for being dumb! No luck. My errors:

Fatal error: Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "second_level_cache" does not have a matching "setSecondLevelCache" setter method which must be defined' in /var/www/litigation/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 1093
( ! ) Zend\Stdlib\Exception\BadMethodCallException: The option "second_level_cache" does not have a matching "setSecondLevelCache" setter method which must be defined in /var/www/litigation/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php on line 110

Thanks. Cheers.

**Comment by FabianKoestring** [comment]
@jarrettj He is talking about entity manager config. If you want to use it with zf2 module you have definitely wait for doctrine/DoctrineORMModule#295.

**Comment by jarrettj** [comment]
Cool @FabianKoestring thanks! Then I'll patiently wait. :)

**Comment by jarrettj** [comment]
Well, the waiting is over @bakura10 thanks for merging 2nd level cache into doctrine-orm-module. Added the following to module.config.php: 
```
                'second_level_cache' => array(
                    'enabled'               => true,
                    'default_lifetime'      => 7200,
                    'default_lock_lifetime' => 500,
```
And updated my composer.json:
```
        "doctrine/doctrine-orm-module": "master",
        "doctrine/orm": "2.5.*@dev",
```

Hope that helps anyone else using ZF2 + doctrine.

**Comment by jarrettj** [comment]
How would you set the file lock region directory to use the READ_WRITE mode?

**Comment by bakura10** [comment]
Setting the cache usage is done in your entity with annotations. Setting the second level cache is a two steps process : you mark your entity as cacheable with an optional region, and you configure the region through arrays

**Comment by jarrettj** [comment]
@bakura10 All my entities have the Cache("READ_WRITE") annotation. But that does not work. It throws an error saying:

```
Fatal error: Uncaught exception 'LogicException' with message 'If you what to use a "READ_WRITE" cache an implementation of "Doctrine\ORM\Cache\ConcurrentRegion" is required, The default implementation provided by doctrine is "Doctrine\ORM\Cache\Region\FileLockRegion" if you what to use it please provide a valid directory, DefaultCacheFactory#setFileLockRegionDirectory(). ' in /var/www/litigation/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php on line 225
```

The configuration documentation does not have any details on how to set this file lock region directory.

If I use Cache("NONSTRICT_READ_WRITE") annotation, it works. But it does not cache relationships. Even when adding the Cache("NONSTRICT_READ_WRITE") annotation to associations and their target entity classes.

Thought if I tried Cache("READ_WRITE") instead, the entity association would maybe work.

**Comment by bakura10** [comment]
Looks like an option is missing. I'll have a look at this after lunch

**Comment by jarrettj** [comment]
Cool man :)

**Comment by bakura10** [comment]
@jarrettj , addressed by https://github.com/doctrine/DoctrineORMModule/pull/378

Thanks for reporting!

**Comment by jarrettj** [comment]
Only happy to help dude! Will have a look later.

**Comment by jarrettj** [comment]
File lock directory option works! :) Associations still don't work though. :(

I'll have a closer look tomorrow though. Thanks for the help so far though guys.

**Comment by jarrettj** [comment]
All jesus, all working! Just did a restart of memcache. This is Freakin Awesome! :)

**Comment by bakura10** [comment]
Good to know! :) Second Level Cache is indeed an awesome feature!

**Comment by guilhermeblanco** [comment]
@bakura10 @jarrettj SLC will leverage its power once all cache drivers implement multi get/save support. =D

**Pull request closed without merging**
