### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by lcobucci**
Related to #6424

### CODE REVIEW

**Comment by Ocramius** [comment]
:+1: how the heck did I miss this?!

**Comment by lcobucci** [comment]
@Ocramius give yourself some credit, it was failing due to builds on trusty 😉

**Comment by TomasVotruba** [comment]
This is so great!  :clap: 

I've added a note to GoPHP71.org: https://github.com/TomasVotruba/gophp71.org/commit/40c61f9a235e4c8863cab1cdba47f67c372eef44

**Comment by lcobucci** [comment]
@TomasVotruba we're working hard to finalise everything and release it, no idea on when though.

**Pull request merged**
