### PR TITLE
#7359 Added test for filter disable, refactored code and test

### LINKED ISSUE #7359: We need to add isset to this key
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | /no

#### Summary

We need to add isset to this key
image

and in enable too. A can make it

### PR DESCRIPTION
**Pull request by AndreyMashukov**
I look to code and not found test, I make test for this function

### CODE REVIEW

**Comment by AndreyMashukov** [comment]
Why CI was failed?

**Comment by AndreyMashukov** [comment]
@Ocramius Thanks, fixed!

**Review by Ocramius — APPROVED** [review]
Thanks :+1:

**Comment by Ocramius** [comment]
Note: this does not fix https://github.com/doctrine/doctrine2/issues/7359

**Pull request merged**
