### PR TITLE
Merge 2.9.x into 2.10.x

### PR DESCRIPTION
**Pull request by derrabus**
~~Don't merge yet: I'll backport all changes that were necessary to make the build pass.~~ ✅

### CODE REVIEW

**Comment by derrabus** [comment]
Backport: #9000

**Comment by derrabus** [comment]
Ready. 🙂

**Comment by greg0ire** [comment]
Let's add #9001 ?

**Comment by derrabus** [comment]
Added.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @derrabus !

**Pull request merged**
