### PR TITLE
Docs: use canonical order for phpdoc tags, add missed semicolon

### PR DESCRIPTION
**Pull request by andrew-demb**
Specification for tag `@var` https://docs.phpdoc.org/guide/references/phpdoc/tags/var.html

### CODE REVIEW

**Comment by greg0ire** [comment]
Looks like there are a bit more occurrences in the project:

```
rg -F '@var $'
tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheManyToOneTest.php
243:         * @var $entity Token

docs/en/reference/second-level-cache.rst
242:    /* @var $config \Doctrine\ORM\Configuration */
546:    /* @var $em \Doctrine\ORM\EntityManager */
573:    /* @var $em \Doctrine\ORM\EntityManager */
662:    /* @var $cache \Doctrine\ORM\Cache */
707:    /* @var $article Article */
711:    /* @var $article Article */

docs/en/cookbook/dql-user-defined-functions.rst
198:            /* @var $lexer Lexer */

docs/en/cookbook/dql-custom-walkers.rst
104:            /* @var $countQuery Query */
```

**Comment by andrew-demb** [comment]
@greg0ire 
Done

**Comment by greg0ire** [comment]
@andrew-demb you should target 2.10.x, 2.8 is no longer supported.

**Comment by andrew-demb** [comment]
Sorry, it was't clear to me from readme (lower branch 2.8 is mentioned)

**Comment by greg0ire** [comment]
> Sorry, it was't clear to me from readme (lower branch 2.8 is mentioned)

Is it? I don't see it mentioned on https://github.com/doctrine/orm

**Comment by andrew-demb** [comment]
Then I can't find a reason why I chose this branch :(

**Comment by derrabus** [comment]
Can you resolve the conflicts, please?

**Comment by andrew-demb** [comment]
@derrabus done

**Comment by andrew-demb** [comment]
And rebased one more time

**Comment by andrew-demb** [comment]
Build failure is unrelated

<details>
  <summary>Run phpcs log</summary>
  
  
```
FILE: tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheManyToOneTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 243 | ERROR | [x] Use assertion instead of inline documentation comment.
     |       |     (SlevomatCodingStandard.PHP.RequireExplicitAssertion.RequiredExplicitAssertion)
----------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 17.46 secs; Memory: 82MB

  ```
  
</details>

**Comment by andrew-demb** [comment]
Fixed build - CS requires avoiding use phpdoc for specifying variable type

<details>
  <summary>Run phpcs log</summary>
  
  
```
FILE: tests/Doctrine/Tests/ORM/Functional/SecondLevelCacheManyToOneTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 243 | ERROR | [x] Use assertion instead of inline documentation comment.
     |       |     (SlevomatCodingStandard.PHP.RequireExplicitAssertion.RequiredExplicitAssertion)
----------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 17.46 secs; Memory: 82MB

  ```
  
</details>

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you!

**Pull request merged**
