### PR TITLE
Add missing use statement

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
Follow-up of https://github.com/doctrine/orm/pull/9696

**Comment by greg0ire** [comment]
Thanks @ThomasLandauer !

**Comment by SenseException** [comment]
@ThomasLandauer Thank you. Could you please target the branch 2.12.x and add missing `use` statements to the other examples too?

**Comment by ThomasLandauer** [comment]
Done :-)
@greg0ire thanks for the rebase

**Review by derrabus — APPROVED** [review]

**Pull request merged**
