### PR TITLE
Allow arithmetic expressions within IN operator

### PR DESCRIPTION
**Pull request by webda2l**
Replace and close #6476

### CODE REVIEW

**Comment by derrabus** [comment]
Would it be possible to add a functional test for this feature? I'd feel better if we actually executed the generated query on a real database.

**Comment by webda2l** [comment]
Sure, functional tests added. But maybe in failure because not ran in local, I'll see with the CI

**Comment by derrabus** [comment]
You should be able to run the SQLite tests locally though.

**Comment by webda2l** [comment]
After rebase, local tests with sqlite are ok.

```
david@laptop:~/Works/orm$ vendor/bin/phpunit -c ci/github/phpunit/sqlite.xml
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

...................................................
Using DB driver Doctrine\DBAL\Driver\PDO\SQLite\Driver
..........   61 / 3597 (  1%)
.............................................................  122 / 3597 (  3%)
.............................................................  183 / 3597 (  5%)
.............................................................  244 / 3597 (  6%)
.........SS..................................................  305 / 3597 (  8%)
.............................................................  366 / 3597 ( 10%)
.............................................................  427 / 3597 ( 11%)
..............S.........SSSS.S...............................  488 / 3597 ( 13%)
.............................................................  549 / 3597 ( 15%)
.............................................................  610 / 3597 ( 16%)
......SS.....................................................  671 / 3597 ( 18%)
.............................................................  732 / 3597 ( 20%)
.............................................................  793 / 3597 ( 22%)
.............................................................  854 / 3597 ( 23%)
.............................................................  915 / 3597 ( 25%)
.............................................................  976 / 3597 ( 27%)
............................................................. 1037 / 3597 ( 28%)
.............................................S.SSSSSSSSSSSS.. 1098 / 3597 ( 30%)
............................................................. 1159 / 3597 ( 32%)
............................................................. 1220 / 3597 ( 33%)
..SS.................................S....................... 1281 / 3597 ( 35%)
...................S......................................... 1342 / 3597 ( 37%)
.........................................S................... 1403 / 3597 ( 39%)
............................................................. 1464 / 3597 ( 40%)
............................................................. 1525 / 3597 ( 42%)
.............................................S..SS........... 1586 / 3597 ( 44%)
....S..................................................S..... 1647 / 3597 ( 45%)
...........S.................................SS.............. 1708 / 3597 ( 47%)
............................................................. 1769 / 3597 ( 49%)
............................................................. 1830 / 3597 ( 50%)
............................................................. 1891 / 3597 ( 52%)
............................................................. 1952 / 3597 ( 54%)
......................................SSSSSSS................ 2013 / 3597 ( 55%)
............................................................. 2074 / 3597 ( 57%)
...........................S................................. 2135 / 3597 ( 59%)
............................................................. 2196 / 3597 ( 61%)
............................................................. 2257 / 3597 ( 62%)
..........................SS.........................S....... 2318 / 3597 ( 64%)
............SSS..............................IISS............ 2379 / 3597 ( 66%)
.............S.................SSS........................... 2440 / 3597 ( 67%)
............................................................. 2501 / 3597 ( 69%)
............................................................. 2562 / 3597 ( 71%)
............................................................. 2623 / 3597 ( 72%)
............................................................. 2684 / 3597 ( 74%)
............................................................. 2745 / 3597 ( 76%)
............................................................. 2806 / 3597 ( 78%)
............................................................. 2867 / 3597 ( 79%)
............................................................. 2928 / 3597 ( 81%)
............................................................. 2989 / 3597 ( 83%)
............................................................. 3050 / 3597 ( 84%)
............................................................. 3111 / 3597 ( 86%)
............................................................. 3172 / 3597 ( 88%)
............................................................. 3233 / 3597 ( 89%)
............................................................. 3294 / 3597 ( 91%)
............................................................. 3355 / 3597 ( 93%)
.............................S.......S.......S.......S....... 3416 / 3597 ( 94%)
..................S.............S............................ 3477 / 3597 ( 96%)
............................................................. 3538 / 3597 ( 98%)
...........................................................   3597 / 3597 (100%)

Time: 00:12.754, Memory: 434.50 MB

OK, but incomplete, skipped, or risky tests!
Tests: 3597, Assertions: 13035, Skipped: 62, Incomplete: 2.
```

**Review by derrabus — APPROVED** [review]

**Review by beberlei — APPROVED** [review]

**Comment by beberlei** [comment]
@webda2l @astepin thank you both!

**Comment by webda2l** [comment]
Thanks to the Doctrine team likewise!

**Pull request merged**
