### PR TITLE
travis: remove unnecessary database creation

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref: #1278

### CODE REVIEW

**Comment by Ocramius** [comment]
@TomasVotruba as you can see, fails because of the tmpdb stuff...

**Comment by Ocramius** [comment]
Needs a rebase due to #1286

**Comment by TomasVotruba** [comment]
Rebased. Looks like still some tests are skipped, so this probably would not bring any improvement.

**Comment by TomasVotruba** [comment]
Closing in favor of #1289

**Pull request closed without merging**
