### PR TITLE
Removing copyright headers in every file - LICENSE file is sufficient

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by Majkl578** [comment]
I'm afraid this will be huge pain to rebase in develop as we recently added strict types to every single file. :(

**Comment by mikeSimonson** [comment]
Right I should have done that on develop.

@Ocramius Should I close this one and redo it on develop ?

**Comment by Majkl578** [comment]
You can reset source branch to develop, do changes there and change target branch in the PR without closing it. 👍

**Comment by mikeSimonson** [comment]
@Majkl578 How do I do that ?

**Comment by Majkl578** [comment]
When you edit the PR, there is a dropdown to select target branch.

**Comment by mikeSimonson** [comment]
@Majkl578 I still need to redo it localy and force push to this branch right ?

**Comment by Majkl578** [comment]
@mikeSimonson Yep, in the same branch as before. 😎

**Comment by mikeSimonson** [comment]
@Majkl578 Done

**Comment by Ocramius** [comment]
LGTM :+1:

**Comment by guilhermeblanco** [comment]
:scream: for a few minutes I was like... "WAAAAAAT" imagining my rebase + push removed all the headers....

**Comment by mikeSimonson** [comment]
@guilhermeblanco rebase can suggest you nightmare like that ...

**Pull request merged**
