### PR TITLE
Fix EnumType not being hydrated with HYDRATE_ARRAY

### LINKED ISSUE #9947: EnumType with HYDRATE_ARRAY returns string
### Bug Report

DQL with simple entity alias in SELECT part return string instead of enum instance (in HYDRATE_ARRAY mode).

|    Q        |   A
|------------ | ------
| BC Break    |no
| Version     | 2.12.x

#### Current behavior

```php
#[Entity]
class Animal
{
    #[Column, Id, GeneratedValue]
    public int $id = 0;

    #[Column]
    public Status $status = Status::OK;
}

enum Status: string
{
    case OK = 'OK';
    case ERROR = 'ERROR';
}

class AnimalRepository
{
    public function __construct(private readonly EntityManagerInterface $entityManager)
    {
    }

    public function test(): void
    {
        // animal.status is Status enum - OK
        $items1 = $this->entityManager->createQueryBuilder()
            ->select('animal')
            ->from(Animal::class, 'animal')
            ->getQuery()
            ->getResult();

        // animal.status is string - BUG
        $items2 = $this->entityManager->createQueryBuilder()
            ->select('animal')
            ->from(Animal::class, 'animal')
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_ARRAY);

        // animal.status is Status enum - OK
        $items3 = $this->entityManager->createQueryBuilder()
            ->select('animal.id, animal.status')
            ->from(Animal::class, 'animal')
            ->getQuery()
            ->getResult();

        // animal.status is Status enum - OK
        $items4 = $this->entityManager->createQueryBuilder()
            ->select('animal.id, animal.status')
            ->from(Animal::class, 'animal')
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
```

#### Expected behavior

DQL with SELECT entity as root (+ ArrayHydrator) should returns instance of enum.

### PR DESCRIPTION
**Pull request by kvush**
Fixes #9947

add new processEnum method in ArrayHydrator

### CODE REVIEW

**Review by remedge — DISMISSED** [review]

**Comment by derrabus** [comment]
Sorry for picking up your PR that late. Can you please rebase your PR on 2.13.x? If I do so locally, I get a couple of test failures that seem to be related to your changes.

**Comment by kvush** [comment]
> 

Thanks @derrabus, it was my new enum field in CmsUser that broke bunch of existing tests. So I decides do not touch CmsUser and cover my test cases with another Entity. Now all looks good.

**Comment by janatjak** [comment]
@derrabus is there anything else that needs to be improved please?

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you!

**Comment by derrabus** [comment]
I've reverted this PR with 5f29fcdea238a23b4fb28805940041ee1752d1f8 in favor of #10041.

**Pull request merged**
