### PR TITLE
fix scalar column hydrator when using hidden entity

### PR DESCRIPTION
**Pull request by calvera**
as discussed in #9100 @bhushan

### CODE REVIEW

**Comment by bhushan** [comment]
https://github.com/doctrine/orm/pull/9100#discussion_r724717097

**Comment by calvera** [comment]
> [#9100 (comment)](https://github.com/doctrine/orm/pull/9100#discussion_r724717097)

in your test you hide scalar column, try hide whole `bp`
```
        return $this->createQueryBuilder('bp')
            ->select('bp.title')
            ->addSelect('bp as HIDDEN i')
            ->orderBy('bp.id', 'DESC')
            ->getQuery()
            ->getSingleColumnResult();
```
ie. `bp.id` vs `bp`

**Comment by bhushan** [comment]
> > [#9100 (comment)](https://github.com/doctrine/orm/pull/9100#discussion_r724717097)
> 
> in your test you hide scalar column, try hide whole `bp`
> 
> ```
>         return $this->createQueryBuilder('bp')
>             ->select('bp.title')
>             ->addSelect('bp as HIDDEN i')
>             ->orderBy('bp.id', 'DESC')
>             ->getQuery()
>             ->getSingleColumnResult();
> ```
> 
> ie. `bp.id` vs `bp`

I dont think it creates any problem, why do you want to hide `bp` ? what is this scenario ?

**Comment by calvera** [comment]
> > > [#9100 (comment)](https://github.com/doctrine/orm/pull/9100#discussion_r724717097)
> > 
> > 
> > in your test you hide scalar column, try hide whole `bp`
> > ```
> >         return $this->createQueryBuilder('bp')
> >             ->select('bp.title')
> >             ->addSelect('bp as HIDDEN i')
> >             ->orderBy('bp.id', 'DESC')
> >             ->getQuery()
> >             ->getSingleColumnResult();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ie. `bp.id` vs `bp`
> 
> I dont think it creates any problem, why do you want to hide `bp` ? what is this scenario ?

if it did not create any problem i would not need a fix :-)
i need them in SQL because postgres error `for SELECT DISTINCT, ORDER BY expressions must appear in select list`

**Comment by bhushan** [comment]
@greg0ire @derrabus could you please help? I don't understand scenario and problem, why we need to hide `bp` (table reference) from query.

**Comment by greg0ire** [comment]
> for SELECT DISTINCT, ORDER BY expressions must appear in select list

I don't understand either… I mean… there is no distinct here, is there?

@calvera , please amend your commit message to include a detailed, crystal clear explanation of why this is needed (`git commit --amend && git push --force`). In an ideal world, every commit should be fully understandable even 6 months later without additional context.

**Comment by calvera** [comment]
the point is not in the DQL or if distinct is needed or if it is there... the point is: when you select whole entity as hidden, it is not hidden for the new scalar column hydrator... i do not know how to explain it more clearly. i thought that it is clear when you see the test cases i've added

**Comment by greg0ire** [comment]
> when you select whole entity as hidden, it is not hidden for the new scalar column hydrator

What happens then? Are you getting a crash? If yes, can you provide a stack trace? Because from the tests you added, it's not clear what happens. In a more general way, if you write a commit message with "fix", it's nice to indicate what is broken. "Trust me, it's broken" is not enough, sorry.

> the point is not in the DQL or if distinct is needed or if it is there

Agreed, this is not required but still, it would have been nice to know why you _need_ to hide (and select) `bp` in its entirety and why we need to support that use case.

**Pull request closed without merging**
