### PR TITLE
DDC-3120 - PHP 5.6 internal classes/Serializable serialization fix

### PR DESCRIPTION
**Pull request by Ocramius**
See DDC-3120 ( http://www.doctrine-project.org/jira/browse/DDC-3120 )

This PR provides a backport for the 2.4 branch

### CODE REVIEW

**Comment by lyrixx** [comment]
Hi @Ocramius or @beberlei ; Could you tag a new release with this fix ? Because I want to run my project on php 5.6, and this current release prevent me to do that.

**Comment by Ocramius** [comment]
This was already tagged in 2.4.6

**Comment by lyrixx** [comment]
Oups, sorry for the noise.

Github did not show me the tag for this commit: https://github.com/doctrine/doctrine2/commit/a69584a841efdb1312c8410ade2489c3f558752f

Thanks anyway ;)

**Comment by Ocramius** [comment]
@lyrixx consider that we mark the release versions in jira.

**Pull request merged**
