### PR TITLE
Add option for QueryBuilder to use deferred Criteria

### PR DESCRIPTION
**Pull request by thomasklein94**
In one of my projects using doctrine, I needed to achieve something like adding a criteria to a QueryBuilder, and only evaluates this Criteria when getting the real Query from the QueryBuilder. I have not found anything to fulfill my needs, so I created this small patch to contribute to the community, maybe someone needs this feature too.

An example when this approach can be usefull:
You want some business logic like selecting only some entities based on the environment or something like that. You implemented the EntityRepository for these entities to aware this constraints, but an awful lot of external modules wants to override the where constraints by not using the andWhere() method instead of where() on the QueryBuilder instance, throwing out your carefull filtering, causing confusions with the users. With deferred Critetia, you can define filtering which can not be getting around by external modules of your application.

### CODE REVIEW

**Comment by lcobucci** [comment]
@thomasklein94 thanks for sharing your ideas. I have mixed feelings here, though.

I'm not sure if this should be part of the ORM... I mean, the fact that you have modules overriding filters that were previously defined sounds more like design issues on your application.

Let's wait to hear from other maintainers (@Ocramius @Majkl578 @alcaeus) and then we can do a more in-depth review of the code.

**Comment by Ocramius** [comment]
> but an awful lot of external modules wants to override the where constraints by not using the andWhere() method instead of where() on the QueryBuilder instance, throwing out your carefull filtering, causing confusions with the users. 

This is exactly why custom repositories should be used in different modules (or even simple query methods, segregated each in their own class).

I don't think that adding complexity on the query builder aids with customisation problems. In fact, it will probably even worsen things.

As a rule of thumb, do not share a query builder across two classes: this applies both to inheritance and composition.

**Comment by thomasklein94** [comment]
Hi,
I can see why you think this is a flaw, originated from the application i'm currently developing, but as I mentioned, not just our Bundles using the QueryBuilder - lets say - in a sily way, but lot of 3rd party Bundles as well. 

But let put this aside for a moment. Let's say you want Soft

**Comment by thomasklein94** [comment]
Hi,
I can see why you think this is a flaw in my application, but i still think this is a small changset helping a simplifying application logic. Let me give you an other, more specific example.

Lets filter our entities based on its 'deletedAt' field. As stated in DDC-3708 (Issue #4543 ), it can't be done (easily) with SqlFilter, as it is more like a business logic task, and SqlFilter operates on the data layer. 
So let's move the filtering to the application layer. The first thing that came in the mind of almost everyone is that we can put this filtering in the Entity's Repository class. It may sounds good, but when using with other Bundles, lots of them ask the repository to create a QueryBuilder for the given Entity, and later using that like it have not contain any filtering, Basicly throwing out your Criteria, and often result in an Exception, because the parameters was not reseted and there is a mismatch in used and given parameters. Yes, this is the other module's fault, but its really hard to fix every third party module, but more easy to adopt this deferred criteria feature. 
I'm aware that there is a donctrine extension for soft deletes, i only used this as an easy example (in my inherited application, there is an even bigger and complicated problem, and i don't want to share that problems with you, sorry).

**Pull request closed without merging**
