### PR TITLE
[doctrineGH-9042] Paginator: replace Where clause with IN condition to avoid results with incomplete data

### PR DESCRIPTION
**Pull request by LuigiCardamone**
This PR adds an optional feature to fully load child collections as described in this issue: https://github.com/doctrine/orm/issues/9042
This implementation has been developed and tested for doctrine v2.7.3 but it should be compatible also with latest versions.

### CODE REVIEW

**Comment by derrabus** [comment]
Please resolve the merge conflicts and provide a test for your change.

**Comment by stof** [comment]
See my comment on the issue. To me, this PR is introducing the bug, not fixing it.

**Comment by LuigiCardamone** [comment]
I changed the implementation. The result is an optional feature that is disabled by default and can be enabled by using an additional parameter in the Paginator constructor.
We are currently using this feature and we believe that can be useful to other users. If you are willing to merge this PR I can add the proper test cases.

**Comment by stof** [comment]
even as an optional feature, this is still wrong to me. Write the right DQL query instead of making the paginator change the behavior of DQL

**Pull request closed without merging**
