### PR TITLE
[3.0] [DDC-3406] [Test] Proxy has string instead of objects as identifiers

### PR DESCRIPTION
**Pull request by ThaDafinser**
A failing test case for 
http://www.doctrine-project.org/jira/browse/DDC-3406

@Ocramius got now a test case :+1: 

Reference https://github.com/doctrine/DoctrineORMModule/issues/355

### CODE REVIEW

**Comment by Ocramius** [comment]
After looking a bit further into this, I can confirm that this is a limitation that can't be fixed for now and without breaking any BC.

**Comment by guilhermeblanco** [comment]
@Ocramius just don't close this for now... this seems somehow related to the extra lazy because building the select query is extremely flaky inside of BasicEntityPersister, which falls back into the entire approach we're taking to address it through the PersisterFactory

**Comment by Ocramius** [comment]
@guilhermeblanco added a `3.0` marker for now.

**Comment by ThaDafinser** [comment]
Hui 3.0 ...i should stop finding (or using) edge cases :smile:

**Comment by Ocramius** [comment]
@ThaDafinser I moved it to `3.0` because this is actually very complex to solve right now, and will probably require a hydrator rewrite.

**Comment by Ocramius** [comment]
Closing: moved to #1284

**Pull request closed without merging**
