### PR TITLE
composer: autoload via PSR-4

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by DHager** [comment]
Is this just a "because we can and it's newer" change, or is there something problematic with the older set-up?

I don't anticipate anybody dropping support for PSR-0 anytime soon, it'll probably stick around forever.

**Comment by TomasVotruba** [comment]
@DHager It's rather [about PSR-0 deprecation](http://www.php-fig.org/psr/psr-0/).

**Comment by phansys** [comment]
:+1:

**Comment by Ocramius** [comment]
this-is-fine-meme-500x272c

Merging :-)

**Comment by TomasVotruba** [comment]
@Ocramius :dancer:

**Pull request merged**
