### PR TITLE
Move performance tests to phpbench

### PR DESCRIPTION
**Pull request by lcobucci**
Cherry-picked the work done in #5840 - with some minor adjustments.

Runs fine with the `PHAR` version (waiting on phpbench/phpbench#476 so we can require it on composer).

### CODE REVIEW

**Comment by Ocramius** [comment]
So... what happens when we rebase `develop` on top of this if we merge it? :-\

**Comment by lcobucci** [comment]
@Ocramius git will be smart enough to drop commits (except for the commits with different deltas)

**Comment by Ocramius** [comment]
Good enough for me then. This suite is vital for comparing ORM 2.x to ORM 3.x, so it's gonna be shipped.

@lcobucci can you add a build matrix entry to run this on travis too?

**Comment by lcobucci** [comment]
@Ocramius sure 😉

**Comment by lcobucci** [comment]
@Ocramius done

**Review by Ocramius — APPROVED** [review]
LGTM :+1:

**Pull request merged**
