### PR TITLE
#6942 SQL Function ROUND is not parsed in Query\Parser

### PR DESCRIPTION
**Pull request by cgardiennet**
Branch created from doctrine/doctrine2/2.5
Need to have this feature in next 2.5 version

### CODE REVIEW

**Comment by Ocramius** [comment]
@cgardiennet ORM 2.5 and 2.6 are closed for modification/improvement - you will need to send a PR to `develop` (3.x)

**Comment by beberlei** [comment]
Functions can be added via `Doctrine\ORM\Configuration` registration, this is not needed as a core feature.

**Comment by cgardiennet** [comment]
@ocramius I didn't take time to make a new PR to be merged on branch develop 2 years ago. I should have... 
@beberlei This is unbelievable that an SQL Core function won't be in Doctrine Core features. I understand more why some people are not using Doctrine at all. 
I'll do a fork myself and I'll will patch with all the missing SQL standard functions that I need. Doctrine is not at the level we can expect just because of answers like yours and a lack of quality in functionalities.

**Comment by Ocramius** [comment]
> Doctrine is not at the level we can expect

You can't "expect" things from software developed by volunteers in their free time, sorry.

Besides that, @beberlei is correct, and the DQL functions are already extensible via configuration, so this doesn't need to live in core, especially if `ROUND()` semantics change across platforms.

**Comment by cgardiennet** [comment]
Anyway I'm a volunteer too (even though I'm not a big contributor to the code) and also a consumer.

> especially if ROUND() semantics change across platforms.

Explain to me the purpose of a Database Abstraction Layer then, if not to able to work with different database platforms.

**Pull request closed without merging**
