### PR TITLE
Fix for DDC-3719.

### PR DESCRIPTION
**Pull request by boskee**
Switch to relationToTargetKeyColumns when matching non-owning side with Criteria. Fixes DDC-3719.

### CODE REVIEW

**Comment by Ocramius** [comment]
@boskee can you please include a test case?

**Comment by davidkmenta** [comment]
Hi!

Can anybody please resolve this issue? I am experiencing same problem :-(

**Comment by TomasVotruba** [comment]
I came across the same issue.

@Ocramius I could do that. Could you link me some example?

**Comment by Ocramius** [comment]
@TomasVotruba see https://github.com/doctrine/doctrine2/tree/2b3648c725f82efc1f1b12e8e3e35c76df990b58/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by TomasVotruba** [comment]
Thanks. I've managed to fix that by using OneToMany annotation instead (which was the correct one).

I'll pass the tests back to @boskee .

**Comment by steffenbrem** [comment]
I've tried this PR but It does not seem to apply the correct criteria, it ignores `maxResults`.

**Comment by steffenbrem** [comment]
Is this PR stil being worked on?

**Comment by TomasVotruba** [comment]
@steffenbrem Not really, I probably didn't need it to fix it anymore.

**Pull request merged**
