### PR TITLE
Hotfix: Reverting BC Break - PersistentCollection should accept `null` and `array` as constructor parameter

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
:+1: for array
:-1: for null

**Comment by stof** [comment]
@Ocramius Are you sure about this ? PersistentCollection in 2.4 does not seem to accept arrays(well, the constructor accept them, but you get a fatal error later on almost any method call

**Comment by Ocramius** [comment]
> PersistentCollection in 2.4 does not seem to accept arrays(well, the constructor accept them, but you get a fatal error later on almost any method call

Then I'm fixing this incorrectly and I'll change the fix.

Adding a `Collection` type-hint to the third constructor argument of `PersistentCollection` actually exposes the code bits that are troublesome right no

**Comment by Ocramius** [comment]
> Therefore, claiming we support null is very odd.

Agreed. I'll check for a better solution

**Comment by stof** [comment]
@Ocramius IMO, giving them an error on the typehinted argument is fine, given that code which would break on the typehint is code that would have produced a fatal error anyway. Code paths triggering a fatal error are not covered by BC IMO. Fatal errors are not a feature of the code

**Comment by Ocramius** [comment]
Sorry for closing/re-opening: I accidentally deleted the branch on my fork. This approach should be better :-)

**Comment by guilhermeblanco** [comment]
:+1:

**Comment by zeroedin-bill** [comment]
:+1:

**Comment by Ocramius** [comment]
Backported into `2.5` at doctrine/doctrine2@724dfa0de3a45da9214ab926d86aa4bad91dbbfd

**Comment by Ocramius** [comment]
Note: assigned http://www.doctrine-project.org/jira/browse/DDC-3667 to this issue (since the integration bot had a hiccup)

**Pull request merged**
