### PR TITLE
Modernize `strpos()` calls

### PR DESCRIPTION
**Pull request by derrabus**
PHP 8 introduced nicer function to check if a string contains another string. The PHP 8 polyfill that we're already using should allow us to leverage those function.

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]
The amount of changes you did shows that it was totally worth creating these new functions!

**Comment by greg0ire** [comment]
Triggered a new build, this one wasn't starting

It seems to be failing because of a signature-compatibility issue, not sure why this was not caught before in #9418 :thinking: 

> Declaration of Doctrine\Tests\ORM\Functional\ManyToOneOrphanRemovalTest::getEntityManager(?Doctrine\DBAL\Connection $connection = NULL, ?Doctrine\Persistence\Mapping\Driver\MappingDriver $mappingDriver = NULL): Doctrine\ORM\EntityManagerInterface should be compatible with Doctrine\Tests\OrmFunctionalTestCase::getEntityManager(?Doctrine\Tests\DbalExtensions\Connection $connection = NULL, ?Doctrine\Persistence\Mapping\Driver\MappingDriver $mappingDriver = NULL): Doctrine\ORM\EntityManagerInterface in /home/runner/work/orm/orm/tests/Doctrine/Tests/ORM/Functional/ManyToOneOrphanRemovalTest.php on line 95

```diff
- Doctrine\Tests\ORM\Functional\ManyToOneOrphanRemovalTest::getEntityManager(
+ Doctrine\Tests\OrmFunctionalTestCase::getEntityManager(
- ?Doctrine\DBAL\Connection $connection = NULL, 
+ ?Doctrine\Tests\DbalExtensions\Connection $connection = NULL
 ?Doctrine\Persistence\Mapping\Driver\MappingDriver $mappingDriver = NULL
 ): Doctrine\ORM\EntityManagerInterface 
```

EDIT: it was in fact occuring, but is just a warning at that point: https://github.com/doctrine/orm/runs/4914222176?check_suite_focus=true

Maybe we should use https://phpunit.readthedocs.io/en/9.5/configuration.html?highlight=warning#the-convertwarningstoexceptions-attribute or https://phpunit.readthedocs.io/en/9.5/configuration.html?highlight=warning#the-failonwarning-attribute ?

**Comment by SenseException** [comment]
> Maybe we should use https://phpunit.readthedocs.io/en/9.5/configuration.html?highlight=warning#the-convertwarningstoexceptions-attribute or https://phpunit.readthedocs.io/en/9.5/configuration.html?highlight=warning#the-failonwarning-attribute ?

In this PR or in another one?

**Comment by greg0ire** [comment]
Another one would be best I suppose

**Comment by derrabus** [comment]
The warning did not cause the tests to fail.

```
PHP Fatal error:  Uncaught Error: Call to a member function executeStatement() on null in /home/runner/work/orm/orm/tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyCompositeIdForeignKeyTest.php:53
Stack trace:
#0 /home/runner/work/orm/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): Doctrine\Tests\ORM\Functional\ValueConversionType\ManyToManyCompositeIdForeignKeyTest::tearDownAfterClass()
#1 /home/runner/work/orm/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(746): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#2 /home/runner/work/orm/orm/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(629): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#3 /home/runner/work/orm/orm/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#4 /home/runner/work/orm/orm/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run(Array, true)
#5 phpvfscomposer:///h in /home/runner/work/orm/orm/tests/Doctrine/Tests/ORM/Functional/ValueConversionType/ManyToManyCompositeIdForeignKeyTest.php on line 53
```

I have no idea why this suddenly happens and why only on PHP 7.1.

**Comment by greg0ire** [comment]
@derrabus Looking at the interrupted output of the non-prefer-lowest build, it seems it works better there. So it's probably more related to the `prefer-lowest` part than to the PHP 7.1 part. I'm not reproducing the issue locally with `prefer-lowest`, so the PHP 7.1 part does play a role. Maybe it has to do with the version of `symfony/polyfill-php80`?

**Comment by greg0ire** [comment]
`str_start_with` is only available since v1.16

**Review by greg0ire — APPROVED** [review]

**Comment by derrabus** [comment]
Oh, right. I should've checked that. Thanks!

**Pull request merged**
