### PR TITLE
DDC-2248: Expire result cache functionality not implemented #2947

### PR DESCRIPTION
**Pull request by bruno-ds**
PR for this issue : https://github.com/doctrine/doctrine2/issues/2947#issuecomment-293181787

I don't know how to run the test... sorry

### CODE REVIEW

**Comment by theofidry** [comment]
>I don't know how to run the test...

@bruno-ds one easy way to figure it out is to look at the `.travis.yml`. After a quick glance, it doesn't seem it requires much:

- run phpunit specifying the appropriate config file with the option `-c`
- ensure you have the right DB setup for the tests (if you don't want to bother, I think sqlite should be enough for your tests)

**Comment by bruno-ds** [comment]
Well, I cannot have a working env. : `./vendor/bin/phpunit --configuration ./tests/mysqlconf.xml ./tests/Doctrine/Tests/ORM/Functional/Ticket/StupidlyNamedTest.php `

> Doctrine\DBAL\Cache\CacheException: Trying to cache a query but no result driver is configured.

**Comment by lcobucci** [comment]
@bruno-ds this is what you're looking for: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html#result-cache

You can just use the `ArrayCache` for that purpose.

**Comment by bruno-ds** [comment]
please note that I had to change `tests/Doctrine/Tests/OrmFunctionalTestCase.php` in order to activate 
`$config->setResultCacheImpl(self::$_resultCacheImpl);`

**Comment by lcobucci** [comment]
@bruno-ds thanks for you contribution, I've simplified the tests a bit and provided a fix for it on #6417.

**Comment by Ocramius** [comment]
Handled in #6417

**Pull request closed without merging**
