### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by stof** [comment]
Your config does not work. The command removing xdebug.ini should be skipped on PHP 7 given that PHP 7 does not have XDebug on Travis (XDebug is not yet compatible)

**Comment by TomasVotruba** [comment]
@stof Haven't checked that. Thanks.

I'd prefer standalone bash script file. There long lines start being messy.

What do you think?

**Comment by Ocramius** [comment]
@TomasVotruba this is good as-is IMO

**Comment by TomasVotruba** [comment]
Thanks @Ocramius

**Pull request merged**
