### PR TITLE
Add UPGRADE note for EntityRepository::count()

### LINKED ISSUE #6933: Better document addition of EntityRepository::count()
There are multiple reports about consumers being broken due to this new method. See https://github.com/doctrine/doctrine2/pull/6003#issuecomment-353442961 and linked issues.
Although adding new public method is not a BC break per se. we should at least document it somewhere in UPGRADE as a possible source of problems.

### PR DESCRIPTION
**Pull request by Majkl578**
closes #6933

### CODE REVIEW

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@Majkl578 🚢 !

**Comment by lcobucci** [comment]
We might probably to sync this to `master`, correct?

**Comment by Majkl578** [comment]
Yesm the question is how do we do it in some organized way so we don't forget some commits. :|

**Comment by lcobucci** [comment]
@Majkl578 labels?

**Comment by Majkl578** [comment]
Possibly. 🥇

**Pull request merged**
