### PR TITLE
DBAL 3

### LINKED ISSUE #8884: Get Psalm job to pass with DBAL 3
[Recently, a CI job was added on the 2.10.x branch to statically analyze this project after forcing the installation of `doctrine/dbal` v3](https://github.com/doctrine/orm/pull/8874).

In order not to disrupt contributors, we made sure it would not fail the build although it really does not pass at all:

https://github.com/doctrine/orm/blob/e09f126abfec0add53dc1ed8d4e3708117032fc1/.github/workflows/static-analysis.yml#L94

If you want to help us fix it or get closer to fixing it, you can reproduce the failures locally by running (from the 2.10.x branch)

```shell
composer require doctrine/dbal ^3.0
vendor/bin/psalm
```

When this issue is fixed, we should create a new one about making this job no longer experimental.

### PR DESCRIPTION
**Pull request by derrabus**
Fixes #8884, #8885.

### CODE REVIEW

**Comment by derrabus** [comment]
I don't understand the failure on Postgres. The test passes locally. 🤔

**Comment by greg0ire** [comment]
I do reproduce the failure locally.

```
docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:9.6
vendor/bin/phpunit -c ci/github/phpunit/pdo_pgsql.xml   --stop-on-error
```

I use php 7.4

**Comment by greg0ire** [comment]
This might be a new issue introduced in https://github.com/doctrine/dbal/pull/4082 … I don't understand why it only affects PostgreSQL though.
Previously, this worked because it resulted in

```php
    public function getDatabase(Connection $conn)
    {
        $params = $conn->getParams();

        return $params['dbname'] ?? $conn->query('SELECT CURRENT_DATABASE()')->fetchOne();
    }
```

Now it results in

`$this->connection = new PDO($dsn, (string) $user, (string) $password, (array) $options);`

**Comment by greg0ire** [comment]
I'm currently working on a fix, we have the database name in `$testConnParams` in `TestUtil`

**Comment by greg0ire** [comment]
Pushed the fix :)

**Comment by derrabus** [comment]
We're green. The PR is ready, but because I've added a new parameter to various PHPUnit jobs, GitHub is waiting for jobs that don't exist anymore.

**Comment by greg0ire** [comment]
Yes. We will have to tweak the settings, and it's going to be a bit complicated because we will have to do so for 2.10.x and 3.x but not for 2.9.x .

**Comment by derrabus** [comment]
Shall I add `dbal-version: ["default"]` to 2.9.x as well? It wouldn't do anything there, but it would make the configration easier.

**Comment by derrabus** [comment]
see #8965

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @derrabus ! That was impressive!

**Pull request merged**
