### PR TITLE
Remove primary key requirement from DatabaseDriver.php.

### PR DESCRIPTION
**Pull request by danyPatient**

### CODE REVIEW

**Comment by Ocramius** [comment]
Any mapping must come with a non-empty set of identifier fields. This patch leads to the database driver producing invalid mapping definitions, and is therefore invalid.

The correct approach here is to simply skip tables with no PK when reverse-engineering the DB, and that is usually done by passing an exclusion pattern to the CLI tools.

**Comment by danyPatient** [comment]
But what can I do when I have a legacy base which has not any id and needs to be mapped?

**Comment by danyPatient** [comment]
@Ocramius Is updating the database the only way?

**Comment by Ocramius** [comment]
You'll have to reverse engineer it manually.

On 19 Jan 2017 12:00, "danyPatient" <notifications@github.com> wrote:

But what can I do when I have a legacy base which has not any id and needs
to be mapped?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/pull/6242#issuecomment-273745262>,
or mute the thread

**Comment by danyPatient** [comment]
And one I reversed engineer manually, how do I resolve the Exception `No identifier/primary key specified for Entity "AppBundle\Entity\SomeEntity". Every Entity must have an identifier/primary key`?

**Comment by Ocramius** [comment]
You will have to add an identifier to your entities: the ORM can't work without it.

**Pull request closed without merging**
