### PR TITLE
LimitSubqueryOutputWalker: fix aliasing of property in OrderBy from MappedSuperclass

### PR DESCRIPTION
**Pull request by fprochazka**
http://www.doctrine-project.org/jira/browse/DDC-3679

### CODE REVIEW

**Comment by zeroedin-bill** [comment]
Thanks - i'll merge after nitpick :+1:

**Comment by fprochazka** [comment]
I'm not sure if it's fixed properly. Is this enough?

**Comment by zeroedin-bill** [comment]
@fprochazka I think so - though there's no functional test for this case...

**Comment by fprochazka** [comment]
@zeroedin-bill now I'm thinking it might be better to reverse the condition and only change the alias if the entity is in inheritance and it's the type of inheritance where you use multiple tables.

**Comment by fprochazka** [comment]
@zeroedin-bill now I'm thinking it might be better to reverse the condition and only change the alias if the entity is in inheritance and it's the type of inheritance where you use multiple tables. Because it still might break with STI.

**Comment by zeroedin-bill** [comment]
@fprochazka we need more functional test cases...

**Comment by fprochazka** [comment]
Sure, there is never enough tests :) But I won't be able to write more right now. Soonest would be somewhere around monday.

**Comment by zeroedin-bill** [comment]
@fprochazka For now I'll merge this. I'd really appreciate if you could write some functional tests on Monday to cover this scenario if you have time!

Thanks!

**Comment by fprochazka** [comment]
I'll try!

**Pull request merged**
