### PR TITLE
Fix the regular field changeset phantom value object change

### PR DESCRIPTION
**Pull request by yakupars**
Reference comparison thinks the fields have changed even it is a value object and internal data is the same.

### CODE REVIEW

**Comment by derrabus** [comment]
A test would've been nice.

**Comment by yakupars** [comment]
https://github.com/doctrine/orm/pull/11591/files#diff-f9dac2024d31e149cbb4624bc32b6eda6a3300d908daf7eeb5e90609a9205aa4 should cover it

**Comment by derrabus** [comment]
Can you elaborate a bit more why you face this issue? Your test does not really tell me that and also your PR description falls pretty short. The thing is, we've been rejecting this kind of change for quite some time now, see the explanation in https://github.com/doctrine/orm/pull/814#issuecomment-320161448 for instance.

The ORM currently has no concept for equality on value objects and we don't want to implement guesswork on when two arbitrary objects are to be considered equal.

**Comment by yakupars** [comment]
After reviewing your feedback and comparing it with the other PR, I realize there's no need to repeatedly explain the framework to you. The other PR seems to address a more specific scenario than this fix tbh.

However, I noticed the statement:
> just because a !== b && a == b is true doesn't mean Doctrine should just not update it

That says it all actually. And about value objects, 7 years, no solution and asking me to convince you in a comment?

I have already found a workaround for this bug and was simply trying to contribute to the project. I don't feel the need to engage in a philosophical debate about whether two objects must share the same memory location to be considered equal.

Oh, the issue I had was about https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/loggable.md btw.

Thanks for the feedback! You may close the PR since I will not drag this out for 7 more years.

**Comment by derrabus** [comment]
All right. Thanks for giving it a try though.

**Pull request closed without merging**
