### PR TITLE
Add integer cast in setFirstResult methods of Query and QueryBuilder

### LINKED ISSUE #9089: Return value of Doctrine\ORM\Query::getFirstResult() must be of the type int or null, string returned
### Bug Report

Calling getFirstResult() results in an error:
Return value of Doctrine\ORM\Query::getFirstResult() must be of the type int or null, string returned

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0

#### Summary

After updating from 2.9.6 to 2.10.0 I'm getting this error, reverting back to 2.9.6 resolves this.

#### Current behavior

The above error is shown.

#### How to reproduce

Can't really build a stub to reproduce, the error is a result of a query by sg/datatablesbundle, it calls getIterator() in the Paginator which calls getFirstResult().

#### Expected behavior

Not seeing an error as with version 2.9.6, maybe related to #9086?

### PR DESCRIPTION
**Pull request by knallcharge**

### CODE REVIEW

**Comment by derrabus** [comment]
Fixes #9089

**Comment by derrabus** [comment]
Please run `./vendor/bin/phpcbf`

**Comment by knallcharge** [comment]
done, sorry for that

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you, @Knallcharge!

**Pull request merged**
