### PR TITLE
Allow Symfony Console 5.x

### PR DESCRIPTION
**Pull request by alexeyshockov**

### CODE REVIEW

**Review by lcobucci — CHANGES_REQUESTED** [review]
@alexeyshockov we haven't updated this yet because we're handling everything to make v2.x mergeable into v3.0. If we accept this PR we would add more conflicts to the list.

Do you really need it or can this wait?

**Comment by alexeyshockov** [comment]
It can definitely wait at the moment

**Comment by alexeyshockov** [comment]
I'm just curious about the merging strategy, because in [the adjacent PR I got a bit different info about it](https://github.com/doctrine/orm/pull/7978#issuecomment-573445494)

**Comment by lcobucci** [comment]
It's the same info. We're starting to merging things up. So, `2.7.x` is merged into `2.8.x`, which is then merged into `master` :+1:

**Comment by greg0ire** [comment]
Glad to read this is happening :tada: !

**Comment by alexeyshockov** [comment]
OK, so feel free to close this PR if you will merge this change from `2.8.x` to `master` eventually

**Pull request closed without merging**
