### PR TITLE
Enable Strict Types declaration

### PR DESCRIPTION
**Pull request by Majkl578**
Replaces #6523.

Just enables strict types for develop branch + some obvious fixes.
More work will be needed here.

Probably having PHPStan (#6440) operating on level 5 would help a lot.

### CODE REVIEW

**Comment by Ocramius** [comment]
@Majkl578 could we add the strict types declaration also to all test files? That would expose breakages from a userland perspective

**Comment by Majkl578** [comment]
Enabled for tests as well.

Ton of the failures is not relevant since develop is broken right now. :/

**Comment by Majkl578** [comment]
Rebased and updated. Base test suite passes, otherwise same failures as in develop, 🎉 No illusions though, there will indeed be some hidden type errors that'll appear over time. Otherwise not too many errors - see a39e82bb. :)

**Comment by Ocramius** [comment]
@Majkl578 one further rebase and check needed - new files and changes introduced :-)

**Comment by Majkl578** [comment]
Rebased once more and added even more strict declarations (missed previously by a rather dumb regexp).
`$ grep -L strict_types {lib,tests}/**/**.php` shows no more missing declarations. 😎

**Comment by Majkl578** [comment]
One final rebase, merge is now up to you @guilhermeblanco. 👍

**Review by guilhermeblanco — APPROVED** [review]

**Pull request merged**
