### PR TITLE
Combine consecutive unsets

### PR DESCRIPTION
**Pull request by carusogabriel**
`unset` allow us to pass multiple values to check.

[PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me on that.

### CODE REVIEW

**Comment by Ocramius** [comment]
@carusogabriel something went wrong with the test suite here - can you check it and see if that's because of this patch?

**Comment by carusogabriel** [comment]
Gonna compare to the previous `Travis CI` and see what I missed :sweat_smile:

**Comment by Majkl578** [comment]
@Ocramius develop is failing permanently, nothing wrong there, at least until #6903. But as I already said, I'm not really sold here, it's worse to read.

**Review by Majkl578 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
