### PR TITLE
fixed exception class name

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by Majkl578** [comment]
Since the code is not inside namespace, I¨d argue the current snippet is correct and `\` is suprfluous (has no effect).

**Comment by greg0ire** [comment]
Maybe, but it does not hurt and makes this piece of code more copy/pastable in context where namespaces are used, which is the most likely.

**Review by greg0ire — APPROVED** [review]

**Comment by OskarStark** [comment]
> which is the most likely.

thats what I thought about, most users doing the copy paste will use it in a namespaced environment.

**Review by SenseException — COMMENTED** [review]
-

**Review by SenseException — CHANGES_REQUESTED** [review]
I would like this to be consistent through the docs. It's either all having a `\` or none. Just changing one class doesn't do the trick.

**Comment by OskarStark** [comment]
@SenseException thank you for your feedback, which target branch would you prefer when doing such "global fix"?

**Comment by SenseException** [comment]
2.6 and master diverges in the docs, but I guess there aren't much changes in the code examples yet. I suggest master.

**Comment by OskarStark** [comment]
Sorry I don't have some free time to do this 😢

**Pull request closed without merging**
