### PR TITLE
Fix MEMBER_OF comparison when using criteria in query builder

### PR DESCRIPTION
**Pull request by Smartel1**
Fixes "Unknown comparison operator: MEMBER_OF" exception when apply Criteria memberOf comparison to queryBuilder

### CODE REVIEW

**Comment by greg0ire** [comment]
Please associate your email address with your Github account, or change the email in your commits to an address already associated with it.

**Comment by Smartel1** [comment]
@greg0ire done

**Review by greg0ire — DISMISSED** [review]
Looks fine to me. Are there any docs that need to be updated/or tests that need to be written?

**Comment by Smartel1** [comment]
Im not sure. I will check it tommorrow

**Review by vudaltsov — CHANGES_REQUESTED** [review]
Please, add a relevant test case to data provider at https://github.com/doctrine/orm/blob/2.6/tests/Doctrine/Tests/ORM/Query/QueryExpressionVisitorTest.php#L54.

**Review by vudaltsov — DISMISSED** [review]

**Review by greg0ire — DISMISSED** [review]

**Review by azjezz — DISMISSED** [review]

**Review by SenseException — DISMISSED** [review]

**Comment by kevinpapst** [comment]
Just ran into this issue. Since it has two approvals, what about merging?

**Comment by Smartel1** [comment]
Can I merge by myself?

**Comment by lcobucci** [comment]
It hasn't been merged because IMHO this should be considered as an improvement and not a bug fix, so should be sent to branch `2.7` or `master`.

**Comment by kevinpapst** [comment]
There is a public API method `Criteria::expr()->memberOf()` which runs into an exception when used. One could argue that this feels like a bug ...

**Comment by lcobucci** [comment]
@kevinpapst my bad, the title and the patch mislead me. It would be crucial to have a functional test case for it then. I'll rebase this branch and add it.

**Comment by Smartel1** [comment]
<script src="https://gist.github.com/Smartel1/cb06b7ff343f163f46d458b544e6fc93.js"></script>

**Comment by Smartel1** [comment]
`
Criteria::create()->andWhere(
    Criteria::expr()->memberOf(':user', 'e.likedUsers')
);
`

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@Smartel1 :ship:

**Pull request merged**
