### PR TITLE
Update ObjectHydrator.php

### PR DESCRIPTION
**Pull request by eltharin**
correction for bug when multiple calls : 

when I automaticly made a DQL like : 

```
		return $this
			->createQueryBuilder('s0_')

			->leftJoin('s0_.itemSeries','i1_')->addSelect('i1_')
			->leftJoin('i1_.item','i2_')->addSelect('i2_')
			->leftJoin('s0_.serieImportators','s4_')->addSelect('s4_')
			->leftJoin('s4_.serie','s5_')->addSelect('s5_')
			->leftJoin('s5_.itemSeries','i6_')->addSelect('i6_')			
```

ItemSerie Entity : 

```
class ItemSerie
{
	#[ORM\Id]
	#[ORM\ManyToOne( inversedBy: 'itemSeries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Item $item = null;

	#[ORM\Id]
    #[ORM\ManyToOne( inversedBy: 'itemSeries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Serie $serie = null;

    #[ORM\Column(type: 'string', length: 50)]
    private $numero;
   ...
}
```

on each series, the last itemSeries has the good number but the item witch is associate is bad, it take the second of list

### CODE REVIEW

**Comment by derrabus** [comment]
Sorry, I don't understand the problem that you're trying to fix here. Please start by providing a functional test that fails without your changes. That might help others understand and it also helps preventing future regressions.

**Comment by eltharin** [comment]
here is a repo for reproduce the error : https://github.com/eltharin/errordoctrine/
don't know why but sometimes when changing some values, all become good...

**Comment by eltharin** [comment]
error

**Comment by greg0ire** [comment]
Emphasis is mine:

> Please start by providing _a functional test_ that fails without your changes.

**Comment by eltharin** [comment]
I Hope test is OK for you, I didn't know where I Can put the entity classes.

**Comment by eltharin** [comment]
Is there something to do more ?

**Comment by greg0ire** [comment]
Getting a green build perhaps?

**Comment by eltharin** [comment]
Yes... but I can(t correct all of your errors, 
my change appear as error with PSALM but indexof want mixed argument and I give object... 
and all unit test failed without reason

**Comment by eltharin** [comment]
Other one is good :)

**Pull request closed without merging**
