### PR TITLE
Merge 2.14.x into 3.0.x

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by SenseException** [comment]
Are the coding styles supposed to be fixed in another PR or in this PR for the upmerge?

**Comment by greg0ire** [comment]
I think PRs have been merged that passed the build before the CS PR was merged.

UPD: actually no, all 3 branches pass the CS build. This means the failures happen because of the difference in config between branch (3.0.x has PHP-8.1-specific rules)

**Comment by SenseException** [comment]
> Error: Usage of short nullable type hint in "?Animal" is disallowed.

**Comment by derrabus** [comment]
I've fixed the CS issue while merging.

**Pull request closed without merging**
