### PR TITLE
Fixed wrong property name

### PR DESCRIPTION
**Pull request by deguif**

### CODE REVIEW

**Comment by deeky666** [comment]
@deguif even though it's a trivial patch, it requires a regression test IMO

**Comment by zeroedin-bill** [comment]
Definitely - clearly there's no existing test coverage... LOL

**Comment by deeky666** [comment]
@zeroedin-bill yes unfortunately. Therefore we should require at least tests to be added for touched methods.

**Comment by deguif** [comment]
I just added a test to cover this and found another bug.

**Comment by Ocramius** [comment]
Assigning to @guilhermeblanco to change the test into a a test that doesn't hit the DB.

**Comment by Ocramius** [comment]
Backported to `2.5.x` in doctrine/doctrine2@39098ce4156fedf8074c379b26a13e5624ba4362

**Pull request merged**
