### PR TITLE
Fixed a situation where unnecessary sql UPDATE statements were issued fo...

### PR DESCRIPTION
**Pull request by iBiryukov**
...r unchanged DateTime objects

computeChangeSet method in unitOfWork compares original and new data using 'identical' (===) operator. This works well, except for DateTime objects. 

Two different DateTime objects that contain the same data, should not trigger an unnecessary UPDATE query. 

I made changes to account for this case.

### CODE REVIEW

**Comment by AlexeyKosov** [comment]
> So far we didn't introduce them because they only solve edge cases and cause great performance overhead.

Great performance overhead is generating redundant UPDATE queries which, obviously, take some time to execute.

**Comment by Ocramius** [comment]
Yes, but we can't fix it without a massive amount of overhead for the 99% use-case scenario.

**Comment by AlexeyKosov** [comment]
Ok, of course, it's up to you to make strategic decisions, but it could be solved without any massive overhead. 1 `if` condition for checking if the comparable items are both objects and have the same type and another 1 to check if there's a comparator (or however you call it) registered for that class. In other words, it could be implemented as an optional feature, i.e. if one wanted to enable it for, say, `DateTime` or `Money` objects, they could inject a comparator for the specific class which would be responsible for comparing objects of this type. All other comparisons could still be done using `===`.
IMHO, a couple of simple checks are much less evil than executing tons of unnecessary update queries.

**Comment by Ocramius** [comment]
Yes, but that's just fixing a symptom that comes from the
mutability/immutability dichotomy in column types. We don't have a
performance-valid solution for that, and adding exceptions and edge case
handling just clutters the code and introduces more bugs.

If you want to improve this then I suggest looking into a way of unifying
hydration and changeset computation with DBAL type awareness baked in.

Hacks for edge cases are not allowed in any of the doctrine projects,
unless it's about security issues.

**Comment by AlexeyKosov** [comment]
Your point makes sense and, indeed, the ideal solution would be comparing the values in the form they go to the database, rather than objects. 
I was just concerned not about the mutability/immutability dichotomy, but about the case when a different object instance, however, having the same value, is set to an entity.

```
$entity->setCreatedAt(new DateTime('2017-08-04 00:00:00'));
$em->flush();
$entity->setCreatedAt(new DateTime('2017-08-04 00:00:00'));
$em->flush(); // unneccesary query
```

Currently, I have to wrap all setters with something like this:

```
public function setCreatedAt(DateTime $createdAt)
{
    if ($createdAt != $this->createdAt) {
        $this->createdAt = $createdAt;
    }
}
```

Obviously, looks like a dirty hack.  It's great that you managed to avoid such hacks in Doctrine itself, and hopefully, at some point you'll manage to allow Doctrine's users get rid of those in application business-logic.

**Comment by alcaeus** [comment]
@AlexeyKosov this issue can't be solved - just because `a !== b && a == b` is true doesn't mean Doctrine should just not update it. This is part of your application logic: someone sets a new object instance but your application wants to treat it the same. That belongs exactly where you currently have it: in your model.

**Pull request closed without merging**
