### PR TITLE
Remove obsolete and unnecessary properties from `Table` attribute (#11351)

### LINKED ISSUE #11351: `AttributeDriver` ignores index and unique constraint definitions in `Table` attribute
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | >=2.9.x

#### Summary

Since the implementation of the `AttributeDriver` there's a bug that the properties of the `Table` attribute aren't counted in for the indices and unique constraints.

#### Current behavior

Currently setting the indices and unique constraints through the `Table` attribute results in them being ignored which therefore disallows the usage of nested attributes.

This is being handled here:
https://github.com/doctrine/orm/blob/a809a71aa6a233a6c82e68ebaaf8954adc4998dc/src/Mapping/Driver/AttributeDriver.php#L165-L173

Before with annotations, this was possible and the code for the correct interpretation of these was implemented in the `AnnotationDriver`:
https://github.com/doctrine/orm/blob/a809a71aa6a233a6c82e68ebaaf8954adc4998dc/src/Mapping/Driver/AnnotationDriver.php#L137-L224

#### How to reproduce

Creating an entity with the following attributes:
```php
#[Orm\Entity()]
#[Orm\Table(
    'some_entities',
    indexes: [
        new Orm\Index(['some_column_1'], name: 'some_name_1'),
        new Orm\Index(['some_column_2'], name: 'some_name_2'),
    ],
    uniqueConstraints: [
        new Orm\UniqueConstraint('some_unique_constraint', ['some_column_3']),
    ],
)]
class SomeEntity
{
    // [...]
}
```

This wouldn't be handled by the `AttributeDriver`.

But doing it this way works:
```php
#[Orm\Entity()]
#[Orm\Table('some_entities')]
#[Orm\Index(['some_column_1'], name: 'some_name_1')]
#[Orm\Index(['some_column_2'], name: 'some_name_2')]
#[Orm\UniqueConstraint('some_unique_constraint', ['some_column_3'])]
class SomeEntity
{
    // [...]
}
```

#### Expected behavior

The nested attribute variant should also work as expected if indices and / or unique constrains are defined within the `Table` attribute.

OR if this is unwanted behavior it should be removed to reduce confusions in terms of defining the table definitions.

### PR DESCRIPTION
**Pull request by DaDeather**
The properties `indexes` and `uniqueConstraints` were present before and were used for the `AnnotationDriver` but were never implemented for the `AttributeDriver`.
Since the `AnnotationDriver` doesn't exist anymore these can be safely removed reducing possible confusion when defining indices and uniqueConstraints in the `Table` attribute which never worked anyway.

Fixes #11351

### CODE REVIEW

**Review by SenseException — DISMISSED** [review]

**Comment by greg0ire** [comment]
Having doubts regarding whether this is the right target branch for this/whether there should be a deprecation instead. @derrabus , WDYT?

**Comment by derrabus** [comment]
Indeed, this is a breaking change. We need to deprecate those properties first. Target 3.2.x for the deprecation and 4.0.x for the removal.

**Review by greg0ire — COMMENTED** [review]
Retargeted the branch. Please add a note about this in `UPGRADE.md` and open a separate PR [deprecating](https://www.doctrine-project.org/policies/deprecation.html) both properties.

**Review by greg0ire — APPROVED** [review]

**Comment by DaDeather** [comment]
> Retargeted the branch. Please add a note about this in `UPGRADE.md` and open a separate PR [deprecating](https://www.doctrine-project.org/policies/deprecation.html) both properties.

Here's the one for the deprecation: https://github.com/doctrine/orm/pull/11357

**Review by beberlei — DISMISSED** [review]

**Review by SenseException — DISMISSED** [review]
> Indeed, this is a breaking change.

Thanks, I've missed that the target branch wasn't the appropriate one.

**Review by greg0ire — CHANGES_REQUESTED** [review]
This needs to be rebased, and the deprecation code needs to be removed

**Comment by DaDeather** [comment]
> This needs to be rebased, and the deprecation code needs to be removed

:+1: done!

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Congrats on your first contribution @DaDeather !

**Pull request merged**
