### PR TITLE
Change bug reporting link from dead Jira to GitHub

### PR DESCRIPTION
**Pull request by Cladis**
As per the desc, I am not sure I have chosen the best location though (not sure if it is general enough).

### CODE REVIEW

**Comment by Cladis** [comment]
@Ocramius , perhaps you could deal with this one too. I reported it on IRC a week or so ago but no one responded there.

**Review by Ocramius — APPROVED** [review]
@Cladis thanks!

**Comment by Ocramius** [comment]
Related:

 * #5581
 * #6069

**Comment by Ocramius** [comment]
@Cladis I'm personally not on IRC anymore because I'm overloaded with communication channels, sorry...

**Pull request merged**
