### PR TITLE
#8460: Deprecated EntityManager::clear() with argument of one entity class and EntityRepository::clear()

### PR DESCRIPTION
**Pull request by smilesrg**
https://github.com/doctrine/orm/issues/8460

### CODE REVIEW

**Comment by smilesrg** [comment]
This PR is not going to work until these are merged:

- https://github.com/doctrine/persistence/pull/174
- https://github.com/doctrine/common/pull/928

**Comment by beberlei** [comment]
@smilesrg thank you for this contribution, but we are going to have to put a pause button for this for a while. There is a higher level planning todo necessary on the ORM / ODM Team to see the steps we want to pursue for a new `doctrine/persistence` and this is probably requires a top down approach.

**Comment by smilesrg** [comment]
@beberlei would you please tell me where can I see a roadmap for Doctrine 3.0?

**Comment by beberlei** [comment]
@smilesrg we haven't begun formaliziing the roadmap for Doctrine 3 yet

**Pull request closed without merging**
