### PR TITLE
update DBAL constraint to move away from non-existing branch

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
This will allow other projects that require Doctrine ORM (for example the Symfony Doctrine bridge) to test for compatibility with Doctrine DBAL 3.

**Comment by beberlei** [comment]
Dbal 3 is not supported with PRM at the moment. We will add support in an upcoming 2.x version, until then you cannot use dbal 3 if you use the ORM

**Comment by xabbuh** [comment]
@beberlei Thank you for the information. Would you be open for a PR targetting `2.8.x` that allows to install DBAL 3 and fixes the incompatibilities? I'd be willing to give it a try.

**Comment by beberlei** [comment]
@xabbuh honestly that iss something we want to do ourselves, since close interference is needed, and potentially learnings to improve the API and such.

**Comment by xabbuh** [comment]
@beberlei Understood, I am going to find another solution to test the Doctrine bridge with DBAL 3 then. Thanks for your time. 👍

**Pull request closed without merging**
