### PR TITLE
Fix Yaml::parse() errors

### PR DESCRIPTION
**Pull request by yahuarkuntur**

### CODE REVIEW

**Comment by yahuarkuntur** [comment]
This commit fixes the Yaml::parse() deprecation messages in Symfony 2.7 projects using the stable version of Doctrine (2.4.8).

This changes are already implemented in the master branch but not yet in the stable tagged versions.

**Comment by zeroedin-bill** [comment]
Doctrine ORM 2.4.8 was the final patch release of the 2.4 branch - future releases in the branch are security-only.

**Comment by Ocramius** [comment]
Please simply upgrade to `"doctrine/orm": "~2.5"`

**Comment by yahuarkuntur** [comment]
@Ocramius I just did that :) 
Thank you

**Pull request closed without merging**
