### PR TITLE
Remove TODO

### PR DESCRIPTION
**Pull request by VincentLanglet**
This todo is here for 10 years.

Plus, I don't think these two functions should be removed or renamed.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]
We can't find the reason for this and didn't do it in 10 years… fair enough.

**Comment by VincentLanglet** [comment]
@greg0ire ; Do you think it can be merged ? :)

**Comment by greg0ire** [comment]
I do, I approved :trollface: I just try not to merge things in the ORM without at least 2 approvals

**Review by SenseException — APPROVED** [review]
I didn't find any plans about what the todo was referring to. Despite its removal from the docblock, a renaming or removal of these methods can still be done even without those hints.

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !

**Pull request merged**
