### PR TITLE
annotations is required

### PR DESCRIPTION
**Pull request by remicollet**
See /usr/share/php/Doctrine/ORM/Configuration.php

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
It shouldn't be. Could you please file a bug report with steps to reproduce and the error message that you're seeing?

**Comment by remicollet** [comment]
In short running doctrine-data-fixtures test suite
=> requires doctrine-orm
=> use doctrine-annotations

**Comment by remicollet** [comment]
```
$ phpcompatinfo analyser:run lib/
...
Classes Analysis
----------------

    Class                                                                               REF        EXT min/Max PHP min/Max 
    ArrayIterator                                                                       spl        5.0.0       5.0.0       
    BadMethodCallException                                                              spl        5.1.0       5.1.0       
    DOMDocument                                                                         dom        5.0.0       5.0.0       
  U Doctrine\Common\Annotations\AnnotationReader                                        user                   5.3.0       
  U Doctrine\Common\Annotations\CachedReader                                            user                   5.3.0       
  U Doctrine\Common\Annotations\SimpleAnnotationReader                                  user                   5.3.0       
  U Doctrine\Common\Cache\ApcuCache                                                     user                   5.3.0       
  U Doctrine\Common\Cache\ArrayCache                                                    user                   5.3.0       
  U Doctrine\Common\Cache\Cache                                                         user                   5.3.0       
  U Doctrine\Common\Cache\MemcachedCache                                                user                   5.3.0       
  U Doctrine\Common\Cache\RedisCache                                                    user                   5.3.0       
 CU Doctrine\Common\ClassLoader                                                         user       0.1.0       5.3.0       
  U Doctrine\Common\Collections\ArrayCollection                                         user                   5.3.0       
  U Doctrine\Common\Collections\Collection                                              user                   5.3.0       
  U Doctrine\Common\Collections\Criteria                                                user                   5.3.0       
  U Doctrine\Common\Collections\Expr\Comparison                                         user                   5.3.0       
  U Doctrine\Common\Collections\Expr\CompositeExpression                                user                   5.3.0       
  U Doctrine\Common\Collections\Expr\Value                                              user                   5.3.0       
...

```

So doctrine-annotations is used

**Comment by derrabus** [comment]
It is used for optional functionality. If the data fixtures test suite makes use of annotations, that's where the `doctrine/annotations` dependency should be added.

**Comment by remicollet** [comment]
Sorry can't agree... data fixtures don't use annotations, it useq orm, wich use annotations

BTW, do the fuck you want with your project, at least you are aware of the problem.

P.S. previously annotations was pulled by persistence (but dep was removed there)

**Comment by derrabus** [comment]
> do the fuck you want with your project

Okay, closing the PR then.

**Pull request closed without merging**
