### PR TITLE
* LimitSubqueryOutputWalker should not duplicate orderBy clauses

### PR DESCRIPTION
**Pull request by billschaller**
When using the paginator, the LimitSubqueryOutputWalker uses the passed query as a subquery in a generated query.

Ex:

``` SQL
SELECT a0_.id AS id_0, a0_.name AS name_1, a0_.name AS name_2 FROM Author a0_ ORDER BY a0_.name
```

Becomes:

``` SQL
SELECT DISTINCT id_0, name_2 FROM (SELECT a0_.id AS id_0, a0_.name AS name_1, a0_.name AS name_2 FROM Author a0_ ORDER BY a0_.name) dctrn_result ORDER BY name_2 DESC
```

This transformation duplicates the ORDER BY clause unnecessarily -- In SQL Server, this is not valid - it will cause an error unless combined with the TOP clause. In other DBMS, the inner ORDER BY clause is meaningless unless combined with a limit/offset clause, and even then there is no guarantee that the order prescribed in the inner subquery will be maintained in the outer expression. ORM does not generate any subqueries where the order by clause is meaningful. The duplicate inner ORDER BY clause can safely be dropped, without any side effects.

I have modified LimitSubqueryOutputWalker to drop ORDER BY clauses in the subquery generated in the walkSelectStatement method. I have also modified the tests to remove the ORDER BY clauses inside subqueries.

### CODE REVIEW

**Comment by Ocramius** [comment]
Merged into `master` at doctrine/doctrine2@8f097ab30436412e8a62ead3fefe27c28d5bc905

Thanks @zeroedin-bill!

**Comment by zeroedin-bill** [comment]
Yay Thanks! :)

**Comment by austinsmorris** [comment]
@Ocramius, @zeroedin-bill, this broke ordering for pagination.  Here's what's happening:

If the inner subquery did a JOIN and ordering was meant to be done on a column in the joined table, the actual orderby column is not selected in the subquery.  This results in the outer query (where the ordering is meant to take place) selecting a column that is not available to it :boom:!

Still trying to make sense of the changes here so I can submit a fix, so if you know how to fix, let me know!

Thanks!

cc @brianium, @mrkrstphr

**Comment by zeroedin-bill** [comment]
@austinsmorris Can you PR a failing testcase?

**Comment by mvrhov** [comment]
Well. as I said. The ORDER BY is important.! We are going through this every couple of months.

**Comment by stof** [comment]
This is precisely why providing a testcase is important, to avoid regressions

**Comment by austinsmorris** [comment]
See #1267.  Let me know if you have any questions.  Thanks for your help!

**Comment by thomas-koch-comsolit** [comment]
@zeroedin-bill could you be so kind and have a look at http://www.doctrine-project.org/jira/browse/DDC-3688 ? I believe it might be caused by this change or at least related to it?

**Pull request closed without merging**
