### PR TITLE
Replace spl_object_hash() with more efficient spl_object_id()

### PR DESCRIPTION
**Pull request by Majkl578**
Simple function name replacement.
 spl_object_id() returns numeric id instead of string hash so it's a simple win, both memory and time-wise.

### CODE REVIEW

**Comment by Majkl578** [comment]
@guilhermeblanco Ready once your local environment is 7.2-ready. 😉

**Comment by Ocramius** [comment]
@Majkl578 can you run the phpbench suite on this? I realize it will be a minimal difference, but still interested :-)

**Comment by Majkl578** [comment]
I don't really know how to use that tool properly, but here's my try with:
```
php phpbench.phar run -l dots --report=default --iterations 10
```

develop:
```
(best [mean mode] worst) = 656.000 [82,393.438 81,644.309] 864.000 (μs)
⅀T: 19,774,425.000μs μSD/r 1,538.198μs μRSD/r: 4.208%
```

this PR:
```
(best [mean mode] worst) = 684.000 [80,597.321 79,853.433] 808.000 (μs)
⅀T: 19,343,357.000μs μSD/r 1,549.527μs μRSD/r: 3.284%
```

master:
```
(best [mean mode] worst) = 478.000 [55,520.700 55,048.114] 523.000 (μs)
⅀T: 13,324,968.000μs μSD/r 1,221.664μs μRSD/r: 3.714%
```

**Comment by Ocramius** [comment]
@Majkl578 the report from the single benchmarks is more relevant. For instance, a benchmark of persistence would show us how many lookups are done. 
Anyway, I don't see a big change right now.

**Review by guilhermeblanco — APPROVED** [review]

**Comment by Ocramius** [comment]
:ship:

**Comment by Ocramius** [comment]
Oh, conflicts

**Comment by Majkl578** [comment]
Somewhat messed up branches before rebase. but looks ok now. 👍

**Comment by Ocramius** [comment]
This is still running CI against 7.1 though... Weird o.O

**Comment by Majkl578** [comment]
Yes, that commit was lost during recent rebase. Let's wait until we're done with develop and reapply it afterwards.

**Comment by Ocramius** [comment]
This time it got merged 😜

**Pull request merged**
