### PR TITLE
Enforce read-only properties through Psalm annotation

### PR DESCRIPTION
**Pull request by Jean85**
As in title.

### CODE REVIEW

**Comment by greg0ire** [comment]
Maybe this should target 2.9.x, since it's not a bugfix, and might break some pipelines. Your other PR is not 100% bugfixes either (for instance the `numeric-string` thing is more precise, but `string` was technically not wrong). Maybe group things that are note bugfixes with this PR?

**Comment by beberlei** [comment]
`@psalm-immutable` is a class level annotation, if you use `@psalm-readonly` however this will fail internally, because we don't modify these only the in the constructor. We cannot use Psalm annotations for this.

Ref: https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-immutable
https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-readonly-and-readonly

**Comment by Jean85** [comment]
Ok, so maybe we can use `@psalm-readonly-allow-private-mutation` in those cases? 
https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-readonly-allow-private-mutation

**Comment by greg0ire** [comment]
That sounds appropriate 👍

**Comment by Jean85** [comment]
I've tried, it fails a lot, due to stuff like `ClassMetadataBuilder`, `ClassMetadataFactory` and a couple others...

**Pull request closed without merging**
