### PR TITLE
Flatten directory tree on 3.0

### PR DESCRIPTION
**Pull request by greg0ire**
It will make fuzzy matchers more efficient, and configuration files more readable.

- `lib/Doctrine/ORM` becomes just `src`
- `tests/Doctrine/` becomes just `tests`

### CODE REVIEW

**Comment by derrabus** [comment]
The PR title is misleading. We've been using PSR-4 for quite a while already. 😉

**Comment by greg0ire** [comment]
Note: I think this will make merge ups more difficult in the cases of files that have too different versions in 2.x vs 3.x

**Comment by derrabus** [comment]
> Note: I think this will make merge ups more difficult in the cases of files that have too different versions in 2.x vs 3.x

Shall we apply this change to 2.18.x instead then?

**Comment by greg0ire** [comment]
I think you're right. Let me first do a bunch of merges up to start on a clean state, and then I will:
- do this on 2.18.x
- rebase this PR
- do a merge up with the `-s ours` flag

**Review by SenseException — APPROVED** [review]

**Pull request merged**
