### PR TITLE
Validate Embeddable associations in SchemaValidator

### LINKED ISSUE #8052: Validate Embeddables in SchemaValidator
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

The schema validator doesn't currently validate embeddables, which is why you can put associations on embeddables but they are not working anyways and nothing happens. This should be validated and add an error in `SchemaValidator::validateMapping()`.

### PR DESCRIPTION
**Pull request by mateuszsip**
Resolves #8052

### CODE REVIEW

**Comment by beberlei** [comment]
@kejwmen can you rebase this onto the 2.8.x branch, this should not go into 2.7 brach. I'll merge then.

**Comment by kejwmen** [comment]
@beberlei sure, done!
Looks like travis build didn't trigger: https://travis-ci.org/github/doctrine/orm/requests

**Review by SenseException — APPROVED** [review]
Close and reopen PR to restart build. If the build doesn't break this is :+1:

**Comment by greg0ire** [comment]
Let's try again, I recently fixed the 2.8.x build

**Review by beberlei — APPROVED** [review]

**Pull request merged**
