### PR TITLE
Add psalm annotation to ArrayCollection of Parameters

### PR DESCRIPTION
**Pull request by snapshotpl**
Without this I always miss Parameters types in collection

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked by #8360

**Comment by greg0ire** [comment]
Please fix the coding standard issues.

**Comment by snapshotpl** [comment]
@greg0ire CS issues fixed

**Review by SenseException — DISMISSED** [review]

**Comment by greg0ire** [comment]
I don't think this qualifies as a bugfix… it touches `src` and might break pipelines, so… 2.9.x?

**Comment by snapshotpl** [comment]
@greg0ire updated to 2.9

**Comment by snapshotpl** [comment]
@greg0ire Can you review now?

**Review by greg0ire — DISMISSED** [review]

**Comment by greg0ire** [comment]
It looks good to me, but there are conflicts you need to fix.

**Comment by snapshotpl** [comment]
@greg0ire ready!

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @snapshotpl !

**Pull request merged**
