### PR TITLE
Update ConsoleRunner's command list to include L2 cache and DBAL reserved keywords commands

### PR DESCRIPTION
**Pull request by lcobucci**
These commands were missing and they're quite important...

### CODE REVIEW

**Comment by Ocramius** [comment]
@lcobucci can we add a test checking the list of registered commands? Or is the console runner untestable?

**Comment by lcobucci** [comment]
@Ocramius we can add an assertion like (for each command):
```php
self::assertTrue($app->has('dbal:run-sql'));
```
or:

```php
self::assertTrue($app->has((new \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand())->getName()));
```

Maybe we can move the list of classes to a constant and reuse that constant to instantiate them and test things, like:

```php
foreach (ConsoleRunner::COMMAND_LIST as $command) {
    self::assertTrue($app->has((new $command())->getName()));
}
```

What do you prefer?

**Comment by Ocramius** [comment]
The first one: ensures BC and we see the diff immediately if something
changes

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
LGTM :ship:

**Pull request merged**
