### PR TITLE
Fix of variable typo in cache usage example

### PR DESCRIPTION
**Pull request by SenseException**

### CODE REVIEW

**Comment by Majkl578** [comment]
Should probably target 2.6? Or is this issue only in master?

**Comment by SenseException** [comment]
It is in every available version, including 2.5. I guess I should have target 2.6 instead of master.

**Comment by Ocramius** [comment]
@SenseException if it's a bugfix it's worth backporting, but I'm really unsure if we should start backporting also documentation issues unless the gravity is high. Reason being that the amount of work increases.

**Review by Ocramius — APPROVED** [review]
Shipping to `master` for now

**Pull request merged**
