### PR TITLE
Remove duplicated enum type comment from declaration.

### PR DESCRIPTION
**Pull request by damour**
Diff command generate duplicated comment declaration:
ALTER TABLE test CHANGE type type ENUM(\'enabled\', \'disabled\', \'bonus\', \'jackpot\') COMMENT \'(DC2Type:enum_status)\' NOT NULL COMMENT \'(DC2Type:enum_status)\''

### CODE REVIEW

**Comment by Ocramius** [comment]
@damour can you please write a test that fails with the original version, and passes with your modified one?

**Comment by Ocramius** [comment]
@damour seems good, but can you please also add a [`requiresSQLCommentHint`](https://github.com/doctrine/dbal/blob/ec8fc16604915110eea8046e3ea594c133aee880/lib/Doctrine/DBAL/Types/Type.php#L331-L344) that always returns `true` please?

**Comment by damour** [comment]
@Ocramius done, thanks.

**Comment by Ocramius** [comment]
@damour thanks!

**Pull request merged**
