### PR TITLE
Fixing method name 'rollBack', which was documented as 'rollback'

### PR DESCRIPTION
**Pull request by rawkode**

### CODE REVIEW

**Comment by Ma27** [comment]
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L413
I'm sure that there are enough other occurences of the wrong method name.

**Comment by rawkode** [comment]
I fixed the other two references - though I'm not sure if you're suggesting that I fix them or just leave them and let PHP's case insensitivity handle it.

**Comment by Ma27** [comment]
I would recommend using something like "Find usages" in phpstorm in order to display all usages of rollBack() in this project, so you can fix them all :)

**Comment by rawkode** [comment]
Search and replace shows that I've got them all. The only `rollback` calls left are on the `EntityManager` class, where the method is actually `rollback`

**Comment by deeky666** [comment]
@rawkode thanks!

**Pull request merged**
