### PR TITLE
refactor(size): changed size in UnitOfWork

### PR DESCRIPTION
**Pull request by spyrash**
array_map and array_sum both iterate over the array.
A single loop could improve performance slightly.

### CODE REVIEW

**Comment by greg0ire** [comment]
Hi :wave: How did you find this issue?

**Comment by spyrash** [comment]
> Hi 👋 How did you find this issue?

Hi!
I was looking for similar improvements, as in [!11332](https://github.com/doctrine/orm/pull/11332), and noticed how much the removal of a single array_map improved performance. Inspired by that, I started exploring other areas and realized that the size function could be optimized to use only one iteration of identityMap instead of two.
This refactor is not linked to any specific issue at the moment.

**Comment by greg0ire** [comment]
Ok. I was wondering because I was not able to find any call to that method in the project. Better performance comes at a legibility cost. For !11332, that cost was more than justified, but here, I don't think it is, by your own admission. Maybe a better approach would be to start by hunting for `array_map` in a real world trace?

**Comment by spyrash** [comment]
The only reference I was able to find is in this docs->[working-with-objects.rst](https://github.com/doctrine/orm/blob/5d73458f0b13a8cde6b9ee7e6dfdd1a99e68e771/docs/en/reference/working-with-objects.rst?plain=1#L516). Despite the fact that this refactor remove an iteration and could be useful if other projects use this size function I agree with you.
 I'll hunt for other improvements and try to get a benchmark/trace of it. 
 
 ps: there is any documentation of how to trace improvements and time of execution in doctrine for contribution?

**Comment by greg0ire** [comment]
I don't know if there is any docs on this, however I do know that we have phpbench benchmarks here: https://github.com/doctrine/orm/tree/3.3.x/tests/Performance

If I had to hunt for improvements, I think I would use xdebug, blackfire or datadog features and would hunt for calls to `array_map` in traces. With xdebug, you can get a full trace with `xdebug_start_trace()`

**Pull request closed without merging**
