### PR TITLE
Merge 2.17.x up into 2.18.x

### PR DESCRIPTION
**Pull request by mpdude**
- Cover limit/offset values in `LimitSubqueryOutputWalkerTest`
- Fix calls to removed lock methods (#11061)

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @mpdude !

**Comment by mpdude** [comment]
Merging 2.18 into 3.0 seems way more complex with lots of conflicts. How to best approach that?

**Comment by greg0ire** [comment]
You may cherry-pick your commit so that you don't have to deal with the merge up. In general, to deal with big merges up, the best is to merge a commit that is not the latest 2.18, but something between the last merge up point and now. https://github.com/mhagger/git-imerge can help with automating that.

**Comment by greg0ire** [comment]
That being said, the diff between those branches seems small, so it's a bit suprising that you're having conflicts :thinking: : https://github.com/doctrine/orm/compare/3.0.x...2.18.x

Have you made sure your copy of 3.0.x is up to date?

**Pull request merged**
