### PR TITLE
DDC-2780 - Fixed issue with IS NULL on join aliases

### PR DESCRIPTION
**Pull request by byonchev**
#3528 Added fallback to SingleValuedPathExpression

### CODE REVIEW

**Comment by kipelovets** [comment]
Why isn't this one merged?

**Comment by vbyndych** [comment]
Without this patch IS NULL and IS NOT NULL expressions don't work in sub-queries. It would be really cool if somebody merge it.

**Comment by amerryma** [comment]
Yes, I would like to see this merged. Having to fork right now.

**Comment by fnagel** [comment]
Any workaround for this expect forking or using lazy loading?

**Comment by byonchev** [comment]
I'm using the "[netresearch/composer-patches-plugin](https://github.com/netresearch/composer-patches-plugin)" composer package to patch it on update for the last 8 months - it seems ok.

**Comment by hvt** [comment]
Would be really great if this PR could be merged.

If there's anything against it, what is it?

**Comment by HugoMestre** [comment]
A merge here would be great. Any time now.

**Comment by lcobucci** [comment]
Will take a look on it this evening or tomorrow but would be amazing if @byonchev could sync this branch with master and apply the same conventions we applied there (to make it a bit faster for me to review and merge).

**Comment by lcobucci** [comment]
Just to update you guys, I've discussed this with @guilhermeblanco and the changes are not exactly correct (they're almost right) but I'll fix them and we'll merge this very soon on `master` (and it will ONLY be available for v2.6).

**Comment by lcobucci** [comment]
Closing since it's being handled on #6328.

**Pull request closed without merging**
