### PR TITLE
Fix annotation in Expr

### PR DESCRIPTION
**Pull request by kirya-dev**
This request just fix annotation according allowedClasses.

Closes: https://github.com/doctrine/orm/pull/8098

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]
To help understand:

https://github.com/doctrine/orm/blob/7e5fe79349cd09a9f482460f8af22a8a6d1373ca/lib/Doctrine/ORM/Query/Expr/Base.php#L61-L103

**Comment by greg0ire** [comment]
Please associate your email address with your Github account, or change the
email in your commits to an address already associated with it. If you do not
want to expose your personal email address, you may use
`$userName@users.noreply.github.com`, that way we can still reach you through Github.
Additionally, you will get credit for this contribution on your Github profile.

**Comment by greg0ire** [comment]
I think the coding standard job fails because it looks for a merge base, and we fetch with a depth of 1 commit. Let me try to rebase.

**Comment by greg0ire** [comment]
Apparently this is not enough for git to make the link, the parent information is probably still missing on the merge commit. Let's try fetching deeper.

**Comment by greg0ire** [comment]
It works. @morozov , since you maintain git-phpcs, you may be interested in this.

**Comment by morozov** [comment]
This is how we solved this problem in DBAL at the time we used it here: https://github.com/doctrine/dbal/pull/2936. This might be a better approach than hard-coding the depth.

**Comment by kirya-dev** [comment]
> I think the coding standard job fails because it looks for a merge base, and we fetch with a depth of 1 commit. Let me try to rebase.

of course (-:

**Review by greg0ire — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]

**Comment by greg0ire** [comment]
Temporarily allowing rebase since both commits really don't have to do with each other…

**Comment by greg0ire** [comment]
Thanks @kirya-dev !

**Pull request merged**
