### PR TITLE
Fix CI SA failures

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by greg0ire** [comment]
@simPod this looks like a bugfix. Shouldn't it target 2.9.x?

**Comment by simPod** [comment]
Was not aware those issues disappeared on 2.9.x as well. Retargeted.

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]
Do we have any tests for this class?

**Comment by greg0ire** [comment]
The test suite passes even after throwing right at the beginning of `execute`, so I don't think we do.

**Comment by greg0ire** [comment]
Thanks @simPod !

**Pull request merged**
