### PR TITLE
Remove dead code in the schema tool

### PR DESCRIPTION
**Pull request by mpdude**
Hopefully this does not do anything...?

### CODE REVIEW

**Comment by Ocramius** [comment]
Failures are unrelated, IMO (see build with `--prefer-lowest` dependencies, which is passing). Possibly related to https://github.com/doctrine/dbal/commit/232d58528e554e4795a80e4d1adc0c2db0084e95 ( https://github.com/doctrine/dbal/pull/713 )

**Comment by mpdude** [comment]
Thanks Marco for checking that.

**Comment by Ocramius** [comment]
@lcobucci since the test affected is regarding what you just implemented with L2 cache eviction, can you check it please?

**Comment by lcobucci** [comment]
@Ocramius result set cache right? sure, will look this evening.

**Comment by lcobucci** [comment]
@mpdude @Ocramius issue fixed, `master` is green again 😉

**Comment by Ocramius** [comment]
:ship:

**Pull request merged**
