### PR TITLE
Merge up 2.6 to 2.7

### PR DESCRIPTION
**Pull request by ostrolucky**

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

**Comment by lcobucci** [comment]
Let's hold this for now until `2.6.5` is released.

**Review by lcobucci — DISMISSED** [review]
Actually, let's get it merged in since it fixes the build state. We can do another merge up afterwards. I've added the new commits in `2.6`.

Thanks @ostrolucky

**Comment by greg0ire** [comment]
I think `doctrine/persistence` should be bumped to `^1.2.0` (in `require-dev`) for the low deps build to pass.

**Comment by greg0ire** [comment]
Also, the composer.lock is out of sync, I'm going to try to fix both issues.

**Comment by greg0ire** [comment]
Oh I see you just fixed that issue in 2.7 @lcobucci , I'm going to redo the merge then

**Comment by lcobucci** [comment]
I've addressed this in 2.7 already :+1:
Thanks @greg0ire

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
