### PR TITLE
Remove not used variable $reflFieldValue in ObjectHydrator

### LINKED ISSUE #7834: Unused local variable 'reflFieldValue'
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

Unused local variable `$reflFieldValue` in `ObjectHydrator` at [this](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L379) line.

image

### PR DESCRIPTION
**Pull request by peter-gribanov**
fix #7834

### CODE REVIEW

**Review by mikeSimonson — APPROVED** [review]
Thanks @peter-gribanov

**Comment by lcobucci** [comment]
@peter-gribanov I'm a bit confused here... this has been reported to v2.6 but sent to `master`. Which branch should have been the destination?

**Comment by peter-gribanov** [comment]
@lcobucci this problem is in versions [2.7](https://github.com/doctrine/orm/blob/2.7/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L425), [2.6](https://github.com/doctrine/orm/blob/2.6/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L425), [2.5](https://github.com/doctrine/orm/blob/2.5/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L427), [2.4](https://github.com/doctrine/orm/blob/2.4/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L468), [2.3](https://github.com/doctrine/orm/blob/2.3/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L413), [2.2](https://github.com/doctrine/orm/blob/2.2/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L398), [2.1](https://github.com/doctrine/orm/blob/2.1.x/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L367). In version [2.0](https://github.com/doctrine/orm/blob/2.0.x/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php) there is no this problem.

**Comment by lcobucci** [comment]
@peter-gribanov alright, thanks for your reply!
Branches < 2.6 aren't supported so these aren't relevant. I'll backport this one to `2.6`, which will also be applied in `2.7` once it gets rebased.

Please check https://github.com/doctrine/orm#which-branch-should-i-choose on the next PRs :+1:

**Pull request merged**
