### PR TITLE
Identifier is cached with wrong type

### PR DESCRIPTION
**Pull request by guiwoda**
Based on #1556, just added a functional test that reflects what was described on the original ticket.

### CODE REVIEW

**Comment by guiwoda** [comment]
@guilhermeblanco let me know if this is what you needed to merge!

**Comment by guiwoda** [comment]
Saw the errors, I'm on it.

**Comment by guilhermeblanco** [comment]
:+1:

**Comment by janlanger** [comment]
@Ocramius @guilhermeblanco Will this changes be included any upcoming in 2.5 release? Or is 2.6 coming soon? :)

**Comment by Ocramius** [comment]
@janlanger I will backport this to 2.5.4, thanks for poking me :)

**Comment by Ocramius** [comment]
Backported in doctrine/doctrine2@aae43cbb7746d3569729f0807c2f59fb804ceb7e

**Comment by janlanger** [comment]
Thanks!

**Comment by Ocramius** [comment]
@janlanger and released as 2.5.4

**Pull request merged**
