### PR TITLE
Fix ClassMetadataInfo::$fieldMappings type

### PR DESCRIPTION
**Pull request by ondrejmirtes**
/cc @orklah

### CODE REVIEW

**Comment by orklah** [comment]
Great! I tried to infer manually the content of this array, looks like I missed some content.

**Comment by norkunas** [comment]
Isn't this also missing the `quoted` property? As it is set on the 1417 line when field name starts with backtick

**Comment by ondrejmirtes** [comment]
It's possible, but that one isn't even documented in the PHPDoc above.

**Review by greg0ire — APPROVED** [review]

**Comment by orklah** [comment]
@greg0ire I think this can be closed now

**Pull request closed without merging**
