### PR TITLE
Renamed ORM to something more suitable

### PR DESCRIPTION
**Pull request by GeeH**
@Ocramius this may need some more work, is this something you'd be interested in please?

### CODE REVIEW

**Comment by deeky666** [comment]
LOL

**Comment by deeky666** [comment]
LGTM :+1:

**Comment by Ocramius** [comment]
Sorry, but the `Shitty` namespace is already owned by https://github.com/ShittySoft, of which I'm an admin.

Closing due to licensing issues.

**Comment by Ocramius** [comment]
Changed to `Can't Fix`, as this is obviously not something we can apply in the near future.

**Comment by nuxwin** [comment]
Seriously ? LOL, ORM look ok for me ;)

@Ocramius You feel crazy or what ;)

**Comment by Ocramius** [comment]
@nuxwin totes serious :-P

**Comment by nuxwin** [comment]
@Ocramius 

Well, in that case, I would really know the intent of such renaming ;) Could you clarify a bit because "renaming to something more suitable" don't explain us the real purpose.

Thanks.

**Comment by helios-ag** [comment]
:hankey: Wow a lot of work. So much effort. :+1: for merge! :hankey:

**Comment by nuxwin** [comment]
Oh my god, I'm... Well I now understand the meaning of that PR (at least I think) Does that PR comes from someone which is not happy with Doctrine lol (Shitty). I now understand ocramius humorous answer ;) OUCH Some are really crazy...

**Comment by GeeH** [comment]
This PR was made possible by the power of PhpStorm's awesome ability to refactor quickly and easily.

**Comment by nuxwin** [comment]
@GeeH 

I use PhpStorm too ;) Really good for such a task; ) Now the question here is; Do you abused of beer? (CHUCKLES)

**Comment by helios-ag** [comment]
@GeeH so this PR is sponsored by PhpStorm? Sweet :)

**Comment by deeky666** [comment]
I had wished to see this in `2.6` :( Now I'll have to fork the repository in order to make use of that awesome improvement...

**Comment by ciaranmcnulty** [comment]
Does PHPStorm have a CoC?

**Comment by guilhermeblanco** [comment]
This PR violates our yet to be written/proposed CoC and unfortunately this cannot be merged. Nice performance improvement BTW!

**Comment by Ocramius** [comment]
@ciaranmcnulty we're still writing our Carnival of Conduct

**Comment by helios-ag** [comment]
@Ocramius do you use YAML for writing it?

**Comment by Ocramius** [comment]
@helios-ag XML + XSLT based, of course. We're a serious project!

**Comment by kinncj** [comment]
Nice Adobe PhotoShop logo btw: Adobe PHPStorm

**Comment by Ocramius** [comment]
The splash screen also adds to it: almost looks like a professional tool!

**Comment by eXistenZNL** [comment]
Great PR, could you just fix the tests? Other than that, looks good to me!

**Comment by deeky666** [comment]
Guess we can make an exception concerning test requirements here, as it is obviously perfect code!

**Comment by eXistenZNL** [comment]
Works for me, +1 code wise.

**Pull request closed without merging**
