### PR TITLE
Travis: Switch to container-based infrastructure

### PR DESCRIPTION
**Pull request by Majkl578**
This PR migrates Travis builds to the new container-based infrastructure.
See [Using container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) for details.

### CODE REVIEW

**Comment by Majkl578** [comment]
Open question (ideally for separate PR):
With container-based infrastructure, projects can now use cache, which is persistent across multiple builds. Although it sounds nice, it is probably only useful for packages that are not installed directly via git (i.e. stable versions and/or without `--prefer-source`). Do you think it'd be worth it to use `--prefer-dist` instead and enable caching?

**Comment by Ocramius** [comment]
`--prefer-dist` is not suitable, as we'd hit Github's API limits REAL quick.

**Comment by Ocramius** [comment]
:+1:

**Comment by zeroedin-bill** [comment]
:+1:

**Comment by stof** [comment]
@Ocramius with the usage of the cache, we would not hit it that fast. However, I would not use ``--prefer-dist`` but the default behavior (i.e. using dist for releases and source for dev versions), as dev versions cannot be cached efficiently (they change too often).
And Composer is able to fallback to source when reaching the API limit for dist anyway.

**Pull request merged**
