### PR TITLE
Add type hint for entity manager

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by DHager** [comment]
Looks good, but I've previously had a similar change rejected for being a backwards-compatibility break. (Which is *technically* is, even if it only breaks code that's already pretty broken.)

**Comment by bocharsky-bw** [comment]
Could we use [ObjectRepository](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Persistence/ObjectRepository.php) interface for type hint?

**Comment by stof** [comment]
@bocharsky-bw EntityManager is not an ObjectRepository at all

and this change is wrong as it forbids to pass other implementations of EntityManagerInterface

**Comment by bocharsky-bw** [comment]
@stof Sorry, I don't know how I wrote this.
I means `ObjectManager` instead of `ObjectRepository`.

**Comment by stof** [comment]
We don't accept any object manager here. It must be an entity manager

**Comment by bocharsky-bw** [comment]
Could we use `EntityManagerInterface`?

**Comment by beberlei** [comment]
Yes `EntityManagerInterface` could work, my question is why do you want to change this code anyways? I don't see a reason to.

**Comment by bocharsky-bw** [comment]
@beberlei I think it will be clearer, won't it? In PHP we have type hint for objects and it's a good practice to use it I think.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Ocramius** [comment]
Accepting the change, I thought a bit about possible BC breaks, but PHP doesn't care about constructor override signature changes.

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
