### PR TITLE
Undeprecate PARTIAL for array hydration.

### PR DESCRIPTION
**Pull request by beberlei**
Pair for https://github.com/doctrine/orm/pull/11365

Related: 
* #8471

### CODE REVIEW

**Comment by greg0ire** [comment]
Please update UPGRADE.md as well :pray:

**Review by greg0ire — DISMISSED** [review]

**Review by stof — DISMISSED** [review]

**Comment by derrabus** [comment]
Shouldn't we target 2.20 for this?

**Comment by greg0ire** [comment]
I don't think we should: https://github.com/doctrine/orm/pull/11365 will make this the deprecation wrong, which makes this PR a bugfix.

**Comment by greg0ire** [comment]
> Shouldn't we target 2.20 for this?

@derrabus I don't think we should: https://github.com/doctrine/orm/pull/11365 will make this the deprecation wrong, which makes this PR a bugfix.

**Comment by derrabus** [comment]
> #11365 will make this the deprecation wrong, which makes this PR a bugfix.

#11365 isn't a bugfix either, which makes this change a forward compat improvement.

**Comment by beberlei** [comment]
We made forward compatibility improvements in mini versions in DBAL, so I an with @greg0ire here that this can be in 2.19

**Comment by derrabus** [comment]
But that's not what we agreed on in #11208.

**Comment by greg0ire** [comment]
@derrabus I think it would qualify as an improvement if there was something that should be deprecated but wasn't. Here, we are wrongly over-deprecating, causing extra work.

Just like static analysis tags can be imprecise and wrong and static analysis changes can go on patch or minor depending on whether they make things more accurate or more precise, this change is about making the deprecation more accurate. When https://github.com/doctrine/orm/pull/11365, the deprecation will become wrong, hence this is a bugfix, and complies with #11208 IMO, although I must admit it feels like an edge case/ gray area stuff, because it's correct today, and will suddenly become wrong tomorrow.

This relates to https://github.com/doctrine/doctrine-website/pull/485

**Comment by beberlei** [comment]
@derrabus @greg0ire if we put this in 2.20 you both ok with it?

**Comment by greg0ire** [comment]
Yes

**Review by greg0ire — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Pull request merged**
