### PR TITLE
[DDC-3005] Defer invoking of postLoad event to the end of hydration cycle.

### PR DESCRIPTION
**Pull request by Strate**
This feature makes guarantee, that postLoad event fires after all associations are populated.
Test case also provided.

http://www.doctrine-project.org/jira/browse/DDC-3005

### CODE REVIEW

**Comment by igorpan** [comment]
Hoping for this to get merged too, just stumbled upon this.

I tried to evade using CRUD services and talk directly to doctrine from controllers but this is blocking me as I sometimes need to set dynamically calculated fields on models. 

I figured that postLoad event would be excellent place for that but, unfortunately, it doesn't always work when I need some data from related models.

**Comment by Ocramius** [comment]
I've manually merged this feature into `master` at doctrine/doctrine2@a906295c65f1516737458fbee2f6fa96254f27a5

Thanks @Strate!

**Comment by Strate** [comment]
@Ocramius big thanks to you, it was great job!

**Comment by robinduval** [comment]
@Ocramius Thanks you

**Pull request closed without merging**
