### PR TITLE
DDC-1879: Provide failing test case

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
Provides a failing test case as requested in https://github.com/doctrine/doctrine2/issues/2542#issuecomment-347041145 by @lcobucci for Ticket DDC-1879.

### CODE REVIEW

**Comment by lcobucci** [comment]
@MatthiasKuehneEllerhold thanks a lot for sending the test case, we'll investigate what we're going to do about this since `EntityManager#merge()` is being deprecated in `v2.7` (and was already removed in `develop`). Maybe @guilhermeblanco can help us here.

**Comment by MatthiasKuehneEllerhold** [comment]
Thanks for the heads up. 
Is a warning / something similar appropriate to warn people from the broken `merge()` (and soon deprecated) function?

**Comment by Ocramius** [comment]
@MatthiasKuehneEllerhold being handled in https://github.com/doctrine/doctrine2/pull/6869

**Comment by MatthiasKuehneEllerhold** [comment]
Ok! Do you want me to close this PR then or how do you want to proceed with it (and the issue)?

**Comment by Ocramius** [comment]
May be fixed in `2.6` if we can, but no high hopes, sorry: we are focused on `3.0`

**Comment by MatthiasKuehneEllerhold** [comment]
Fine by me. My use-case for `merge()` is gone because I had to rewrite this part of my app due to other constraints that came in.

**Pull request closed without merging**
