### PR TITLE
Support association mapping in Embeddable

### PR DESCRIPTION
**Pull request by dimarick**
Allow `@ManyToOne`, `@OneToMany` and other associations within `@Embeddable`

### CODE REVIEW

**Comment by Ocramius** [comment]
As previously explained in similar PRs, doctrine's embeddables are designed as ValueObjects, and referencing an entity from a VO is a known bad practice.

**Comment by dimarick** [comment]
@Ocramius, Hibernate and JPA 2.0 supports this behavior:
http://docs.jboss.org/hibernate/orm/5.0/userGuide/en-US/html_single/#criteria-join-singular
https://en.wikibooks.org/wiki/Java_Persistence/Embeddables#Relationships

If you want serialize Embeddable, you can use \Serializable interface.

**Comment by dimarick** [comment]
> referencing an entity from a VO is a known bad practice

Can you describe your position?

**Comment by Ocramius** [comment]
A VO is identified by its value: if it incorporates entities, then it is no
longer a value. We are aware of JPA 2.0.

**Comment by dimarick** [comment]
Doctrine has no features, where embeddable can be used as identifier of something. Also, I am not see any problem with usage as ID for ManyToOne and owning side OneToOne assoc. Support for OneToMany and ManyToMany breaks it, but it can be implemented as optional

**Comment by Ocramius** [comment]
I don't really see any value in implementing something that can hurt more than it can help. Could you come up with an example use-case that can't be modeled as simple entities?

**Comment by dimarick** [comment]
We are wants to group fields of very big entity by type(destination) of each. Embeddables can help to decompose entity fields. But have one problem: most fields are associations.

**Comment by dimarick** [comment]
Another solutions is not works effectively(like separate tables) or cannot fully resolve problem(like a traits)

**Comment by Ocramius** [comment]
> cannot fully resolve problem

The point is that you can just map the embeddable as an entity and you'd be quite fine. What is wrong with that approach?

**Comment by dimarick** [comment]
At first try we use similar solution. But it requires more difficult and repeatable logic in each getters/setters. Support of that is easy way to introduce bugs. Also, this way requires one of this: handle each field in root entity into PrePersist, PreUpdate, PostLoad. Or introduce dependencies from embedded object to root entity by passing $this to embedded constructor. Last solution also break reusability of embedded objects.

**Comment by DHager** [comment]
I find myself asking: "Is Embeddable a value-object owned by an entity, or is it a way to do traits/mixins in the mapping later?"

**Comment by Ocramius** [comment]
The former is the intended original design

**Comment by dimarick** [comment]
I mean, embeddable as value-object is doctrine-only know-how. But we are want to get more functional embeddables, like this: http://www.objectdb.com/api/java/jpa/Embeddable

Summary of my point:
1. Owning-side assoc should be implemented similar JPA. I am cannot see important reason for ignore this feature.
2. Non-owning-side assoc may be implemented and I am ready to do it in independent pull-request.

I am ready to find compromise.

**Comment by DHager** [comment]
@Ocramius Moving forward, is the goal to follow the more-trait-like path taken by JPA? 

I think the JPA 2.0 spec is solving two different use-cases (pure VOs versus trait-like composition) and both solutions involve `@Embeddable` mainly because they each need some of the same technical infrastructure. 

I haven't tried this, but:

    @Entity
    public class Widget {
        @Id int id;
        @Embedded Owned owning;        
    }

    @Embeddable
    public class Owned {
        @ManyToOne User user;      
    }

    @Entity
    public class User {
        @Id int id;
        @OneToMany(mappedBy="owning.user")
        Collection<Widget> items;
    }

In that example, I don't see any value-object-ness at all. `@Embeddable` is being used solely as a mechanism for composing entities.

**Comment by nexGN** [comment]
First of all forgive me my english:/

In domain driven designe one of the base rule is to separate domain from the application layer.
Doctrine is only and in that approch can be only part of app layer.

Basicly in DDD (bussiness) Entity is object which can be modified, but ValueObject can't.

But it doesn't mean that Value Object in app layer (exactly in db) cannot be save as db entity.
The good example is value object which represents some (composite) type with many specific attributes.
In this case in database can exist separate table representing all possible types.

And in such approach that exactly domain value object  can be in app layer Embeddable with oneToMany relation,
and nothing wrong or strange with that.

Of course using real DDD approach with Doctrine as DB (app) layer, mapping bussines logic (Entities and VO-s) must be in yaml or in xml, cause of strict separation of domain and app layers.

In DB there are only db entities and nothing more. 
Yes embeddables is mechanism for composing entities. 
I think that exactly it is their purpose, and that's why I think embeddables should have ability:
* to be an Identifier and 
* to have associations

**Comment by dimarick** [comment]
Confusion in the understanding of the issue is making use of two terms - ValueObject in internals and Embeddable as public interface. But both have different meanings. What is true concept: ValueObject or Embeddable? 
If Embeddable - we are must allow fullfeatured entity decomposition. 
Or if ValueObject - we are must have "identifiable" entity parts without non-owning-side associations(or without any associations). 
But in user interface everywhere used term "Embeddable". And we cannot change it because BC.

I can see next solutions:
1. Apply full association support for embeddables. Optionally refactor internals from ValueObject to Embeddables
2. Apply num. 1 and implement additional `@ValueObject` annotation for plain value objects.
3. Change nothing and leave this misconception.

**Comment by Ocramius** [comment]
Or schedule a rename for 3.x

**Comment by dimarick** [comment]
@Ocramius, embeddables with associations is demanded feature. Why you are so against? Implement both of this is not big problem.

**Comment by Ocramius** [comment]
1. It is an edge-of-the-edge case.
2. It would allow uni-directional only associations (which therefore allows only `@OneToOne`, `@ManyToOne`, `@ManyToMany`, and **NOT** `@OneToMany`) and add a huge pack of complexity for no real advantage.
3. while we named it `Embeddable` (we took the idea from the MongoDB ODM stuff that we already wrote), the idea is that it really just is a value object/struct (no references to other objects).

The feasibility is there, but the will to implement it is not there, given that it brings no real benefits.

**Comment by dimarick** [comment]
1. Subjectively. False for me. In our production we have tasks where it help for us.
2. No. My current implementation has full support of uni-directional (from embeddable and to embeddable) and bi-directional associations. It was one of simplest tasks. OneToMany/ManyToMany also supported.

>no real benefits.

Also subjectively.

>The feasibility is there, but the will to implement it is not there

I am ready to finish this.

**Comment by Ocramius** [comment]
>  OneToMany/ManyToMany also supported.

OneToMany cannot be implemented due to the fact that there would be no owning side being able to reference a non-concrete type (much like Mappedsuperclass)

**Comment by dimarick** [comment]
Yes. We are cannot refer abstract entity, but we are can refer concrete instance of abstract entity. With embeddables we are cannot refer embeddable defenition, but we are have no problem to refer concrete embeddable usage in concreate entity.

Test have examples for this:
https://github.com/dimarick/doctrine2/commit/f0cf63df34f96f18157ca02582fb19dfec24c0c3#diff-5aa5eb69c711bf32439394a129988a7bR977

**Comment by Ocramius** [comment]
The example at dimarick/doctrine2@f0cf63d should really just be disallowed IMO: now your embeddable is not reusable anywhere else, as it is strongly coupled with the referenced type, which again is pointing at the entity your embeddable is in.

**Comment by dimarick** [comment]
ManyToMany assoctiations are normally reusable(but have one resolvable limitation: cannot use it in one entity twice). OneToMany or OneToOne assotiations are not reusable with and without embeddables. But if you are want reuse embeddable with OneToMany or non-owning-side OneToOne you can use unidirectional mapping. Thanks for this note. I think to missing test for this.

**Comment by dimarick** [comment]
Or we can strip support for non-owning side associations and leave only OneToMany.

**Comment by Ocramius** [comment]
Since an embeddable cannot really be referenced, it would make sense to only support owning sides, no?

**Comment by dimarick** [comment]
Two points votes for non-owning-side support:
1. Not in all cases requires reusing embeddable.
2. ManyToMany reusable.

You are right. Partially-reusable is not very good. And after merge support for owning-side we can implement it as separate bundle.

**Comment by ABM-Dan** [comment]
What is odd is that the documentation example of an embeddable gives the exact case scenario in which we would want to use associations: http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html 

Country is very likely to be a reference to a Country table.

**Comment by Arkemlar** [comment]
It could be nice to be able to use relations in Embeddables, even by copling them to one Entity becaues it will allow me to use one class for 3 different ManyToMany assotiation from A to B and make my own methods to access the collection. (Or the other aproach is to tell doctrine to instantinate my own Collection class for these 3 associations instead of ArrayCollection, but I dont know how to do that.)

**Comment by Ocramius** [comment]
Just cross-linking for eventual discussion if anyone else wants to beat the already dead horse: https://gitter.im/doctrine/doctrine2?at=59480c3de59e74be0a95050e

**Pull request closed without merging**
