### PR TITLE
Test case for "class" keyword

### PR DESCRIPTION
**Pull request by lukasmaz**
Test case for http://www.doctrine-project.org/jira/browse/DDC-3493

### CODE REVIEW

**Comment by asprega** [comment]
@Ocramius I'd like to take care of it.

**Comment by Ocramius** [comment]
@asprega just open a PR whenever you have a fix :-)

**Comment by asprega** [comment]
Just submitted a pull request :)

**Comment by Ocramius** [comment]
Handled in #1256

**Pull request closed without merging**
