### PR TITLE
Stop testing intermediary versions

### PR DESCRIPTION
**Pull request by greg0ire**
In my opinion, testing with the lowest-supported version, the latest version of each major version, and optionally the next minor version should be enough.

### CODE REVIEW

**Comment by SenseException** [comment]
I'm in favour of reducing the PHP versions for the ORM build, but I'd like to keep the lowest supported PHP version as long as it's allowed in the Composer constraints.

**Comment by derrabus** [comment]
I think, having at least a smoke test for each supported PHP branch in reasonable. I don't think that we should drop all jobs for PHP 7.3 for instance as long as we support PHP 7.3.

**Comment by greg0ire** [comment]
> I'm in favour of reducing the PHP versions for the ORM build, but I'd like to keep the lowest supported PHP version as long as it's allowed in the Composer constraints.

It's still tested: https://github.com/doctrine/orm/actions/runs/3268036772/jobs/5373969736

That's because of this configuration block: https://github.com/doctrine/orm/blob/90bc6dc300be0987cd75f2027e0612f05fb6f8ff/.github/workflows/continuous-integration.yml#L316-L346

> I think, having at least a smoke test for each supported PHP branch in reasonable. I don't think that we should drop all jobs for PHP 7.3 for instance as long as we support PHP 7.3.

Ok, I'll trust your judgement. Still, I'd be curious to know if we are likely to ever end up in a situation where we would have code that fails on one of the versions I removed, and not on the other ones.

**Comment by derrabus** [comment]
> Ok, I'll trust your judgement. Still, I'd be curious to know if we are likely to ever end up in a situation where we would have code that fails on one of the versions I removed, and not on the other ones.

Note that it's not only about PHP versions. We're also testing against different sets of dependencies because the minimum PHP versions supported by our dependencies. But I also believe that the cases where a PHP 7.3 job would catch an error which would remain undetected by the PHP 7.1 or 7.4 job are rare. On the other hand, the SQLite tests are really fast, so keeping one of them per supported PHP version should not hurt too much.

**Pull request closed without merging**
