### PR TITLE
Remove broken assertion from DateAddFunction and DateSubFunction

### LINKED ISSUE #11240: Fix broken assert(is_numeric($sql)) in DateAddFunction and DateSubFunction
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0

#### Summary

I'm working on ORM 3 and DBAL 4 support on phpstan-doctrine, and I have this test case:

```php
				SELECT		DATE_ADD(m.datetimeColumn, m.intColumn, \'day\'),
							DATE_ADD(m.stringNullColumn, m.intColumn, \'day\'),
							DATE_ADD(m.datetimeColumn, NULLIF(m.intColumn, 1), \'day\'),
							DATE_ADD(\'2020-01-01\', 7, \'day\')
				FROM		QueryResult\Entities\Many m
```

Doctrine crashes on this line: https://github.com/doctrine/orm/blob/5a40b99e11a0de532eb866f062dccad20da19add/src/Query/AST/Functions/DateAddFunction.php#L74

The `$sql` value is: `m0_.intColumn`.

I think the `assert` assumption is wrong, as `interval` does not have to refer to a scalar value, but can be a column as well. The job of this part of the codebase is to just generate the correct SQL query to execute against the database.

Same problem is in DateSubFunction too.

#### Current behavior

```
assert(): assert(is_numeric($sql)) failed
```

#### Expected behavior

It should work and generate the right SQL.

### PR DESCRIPTION
**Pull request by ondrejmirtes**
Closes https://github.com/doctrine/orm/issues/11240

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
SA complains about DBAL 3.8.1 which accepts only `int|numeric-string` into these functions. In DBAL 4.0 `string` is accepted.

Should we ignore this here? Or should I send a PR to DBAL that widens the accepted type to `int|string`?

**Comment by derrabus** [comment]
> Or should I send a PR to DBAL that widens the accepted type to `int|string`?

Yes please. And the deprecation that is triggered there for non-int values looks bogus, given that 4.0 still accepts arbitrary SQL expressions for seconds.

**Comment by ondrejmirtes** [comment]
Done: https://github.com/doctrine/dbal/pull/6302

I didn't notice any wrong deprecations - all of them ask about `is_int(...)` which is fine - support for `int` is removed in 4.0.

**Comment by ondrejmirtes** [comment]
This one is ready 😊

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you!

**Pull request merged**
