### PR TITLE
Clean up the EntityManager constructor

### PR DESCRIPTION
**Pull request by afurculita**
This PR cleans up the EntityManager constructor by moving the
instantiation of a few objects in getters at the first call. This may
come also with a little performance boost, because:
1. The injection of the entity manager does not come with the
   instantiation of all its internal objects;
2. These objects are instantiated only when are needed and many times
   not all are needed.

### CODE REVIEW

**Comment by fprochazka** [comment]
I like the refactoring. But have considered, that calling a method is slower than accessing the property directly?

**Comment by afurculita** [comment]
Calling a method becomes visibly less performant if you call it in a for loop with thousands of iterations. I don't think that the getters from entity manager are called so many times. Only in a poorly designed code.

**Comment by fprochazka** [comment]
@afurculita the `getClassMetadata` is a very performance sensitive method.

**Comment by Ocramius** [comment]
A lot of the touched API is indeed used a lot in iterations and performance-sensitive code.

Make the construction eager instead (or simplify the constructor by chunking it into private methods).

If you need to make the entire EntityManager lazy, then use a lazy service.

**Comment by Ocramius** [comment]
Note that lazy-loading should not really be a baked-in concept, that's why I rejected the PR in first place. We should avoid coding new APIs as lazy-loaded whenever possible, as it just adds complication.

**Comment by afurculita** [comment]
I agree that at some level the lazy initialization adds complication, but the complication is relatively small. And I think that having a lot of instantiation logic in constructor is a much bigger problem. As it affects negatively the performance in some cases. I don't talk here only about EntityManager as I see that is a normal practice in Doctrine to have instantiation logic in constructors.

You say that lazy initialization should not be a baked-in concept, but you know, Swift is natively supporting it (not a reason why we should be all doors open to that, but a reason why not totally refuse it).

In Doctrine everything is performance sensitive, and lazy initialization might help in some places. 

Using a lazy service to make the EntityManager lazy I think is trying to avoid the actual problem.

**Comment by Ocramius** [comment]
Using a lazy service is the correct solution, not a workaround.

I experimented with these concepts a lot, and lazy services are just a
separation of the two concerns: use them ;-)

**Pull request closed without merging**
