### PR TITLE
Don't look for metadata on standard classes

### PR DESCRIPTION
**Pull request by duzenko**
...and don't throw exceptions when it's not found

Discussed here: https://github.com/doctrine/orm/discussions/10019#discussioncomment-3528300

### CODE REVIEW

**Comment by derrabus** [comment]
For the record: I don't think that raising and catching an exception is a problem that deserves a fix.

**Comment by duzenko** [comment]
> For the record: I don't think that raising and catching an exception is a problem that deserves a fix.

Can you suggest any workaround for debugger stopping on internal ORM exceptions during debugging as discussed in the link above?

**Comment by mpdude** [comment]
I don’t think we should merge this. 

It’s a problem related to how you use the debugger, not the code itself.

for sure there’s a way how to configure your debugger to ignore this exception, not stop for it or similar.

**Comment by greg0ire** [comment]
Let's close this then.

**Comment by duzenko** [comment]
Typical PHP-world hair-brained "solution"

**Comment by derrabus** [comment]
I guess, we PHP guys are just too stupid. Better move to go. 🤷🏻‍♂️

**Pull request closed without merging**
