### PR TITLE
[DDC-3761] Fixed cache key

### PR DESCRIPTION
**Pull request by Ragazzo**
Related with this [one](https://github.com/doctrine/doctrine2/pull/1423)

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
@Ragazzo makes sense to me, however I do want @FabioBatSilva to review it too.

**Comment by Ragazzo** [comment]
@guilhermeblanco he reviewed it in Jira task, and said that it is an issue, sure it would be great if he will see this one more time

**Comment by FabioBatSilva** [comment]
Looks good to me,

Wondering if we should give up the more readable serialization format here and just hash ``$entityClass`` + ``$identifiers``

**Comment by Ragazzo** [comment]
@FabioBatSilva note that you can easily go out of the limit for key, if `$entityClass` is namespaced, than with all prefixes and so on, you can get as it was in my case key with 244 bytes length, that is almost maximum for `memcached` 250 bytes key length

**Comment by DHager** [comment]
@Ragazzo : That sounds like a job for individual `CacheProvider` instances, to know how to "slim down"  keys that are too big for whatever system they are integrating with.

**Comment by Ragazzo** [comment]
@DHager yes, it is question of cache implementations in particular, just raised this question to avoid unnecessary bugs in future

**Comment by Ocramius** [comment]
I agree with @DHager here: the interface says `string`, not which kind of string. It is up to the `CacheProvider` to strip/replace invalid characters or sequences of characters.

**Comment by Ragazzo** [comment]
@Ocramius so you want to do this replace in `memcached` provider? I think that current fix is also correct, anyway to avoid fixing any other providers it is better just not to use spaces, not sure why they were used. Anyway i think it is a critical bug, and it should be fixed asap

**Comment by Ocramius** [comment]
@Ragazzo the fix fixes the symptom, not the cause, heh

**Comment by Ragazzo** [comment]
@Ocramius sure, but i dont think that replacing in memcached or other providers sounds right, if you will use or store the hash of entity key anywhere and then will try to get it without calling providers, maybe by your own implementation you can get in situation that you forgot to replace spaces like it would be done in provider. Anyway, why this situations does not have checks in cache providers, like max key length, spaces, and so on? Should separated issue be open for that to make research on what characters are valid and what not?

**Comment by Ocramius** [comment]
> Anyway, why this situations does not have checks in cache providers, like max key length, spaces, and so on?

It is indeed a bug in the cache provider, or in the specific cache adapter impl.

 > Should separated issue be open for that to make research on what characters are valid and what not? 

I think so, yes

**Comment by Ragazzo** [comment]
Ok, than what is on this PR, should i close it and open separate about memcached cache provider implementation?

**Comment by Ocramius** [comment]
@Ragazzo yes please, and thanks! :-)

**Comment by Ocramius** [comment]
Also: close after opening the other PR, or we'll lose track of it

**Comment by Ragazzo** [comment]
> Also: close after opening the other PR, or we'll lose track of it 

Ok

**Comment by Ragazzo** [comment]
@Ocramius i'll try to get back to this one asap, let me know if i should speed up or if it will take too long feel free to fix it as was described )

**Comment by lcobucci** [comment]
I've opened doctrine/cache#208 to keep track of this issue, so we can close this PR.

**Pull request closed without merging**
