### PR TITLE
Proove orphan removal is useless

### PR DESCRIPTION
**Pull request by greg0ire**
Refs #6772

### CODE REVIEW

**Comment by greg0ire** [comment]
Should it act as a one-time proof or should you merge this?

**Comment by lcobucci** [comment]
This merged by mistake and has been reverted in `v3.0` since @guilhermeblanco found out the test actually incorrect

**Comment by greg0ire** [comment]
How is it incorrect?

**Comment by lcobucci** [comment]
@guilhermeblanco can give you more details on this =)

**Comment by guilhermeblanco** [comment]
Simple: 
* using annotations the field does not exist
* using XML the document does not validate the schema (it is not mapped on xsd)

**Comment by greg0ire** [comment]
@guilhermeblanco the goal of this test was to proove exactly that :sweat_smile: 
I was trying to convince @Ocramius to merge #6772

**Comment by greg0ire** [comment]
Anyway, reverting it was the good call IMO :+1:

**Pull request merged**
