### PR TITLE
Enums are considered as changes when Entity is fetched through query.

### PR DESCRIPTION
**Pull request by Warxcell**
Test case that reproduces the behaviour.

### CODE REVIEW

**Comment by kbond** [comment]
I thought https://github.com/doctrine/orm/pull/10074 fixed but maybe not?

**Comment by Warxcell** [comment]
> I thought #10074 fixed but maybe not?

Ah, could be, but its not released yet.

**Comment by michnovka** [comment]
I will have a look into this today in few hours

**Comment by michnovka** [comment]
Hmm, I dont get why

```php
$card = $this->_em->find(CardWithDefault::class, $cardId);
```
returns Proxy class for `CardWithDefault`. `suit` is not initialized it seems. And I am not sure whether passing proxy class to `computeChangeSet` is supported. @HypeMC @greg0ire can you have a look please?

**Comment by Warxcell** [comment]
> Hmm, I dont get why
> 
> ```
> $card = $this->_em->find(CardWithDefault::class, $cardId);
> ```
> 
> returns Proxy class for `CardWithDefault`. `suit` is not initialized it seems. And I am not sure whether passing proxy class to `computeChangeSet` is supported. @HypeMC @greg0ire can you have a look please?

Ok, I will create exactly our use case then, for accuracy.

**Comment by Warxcell** [comment]
Ok, seems its indeed resolved with https://github.com/doctrine/orm/pull/10074 , closing this.

**Pull request closed without merging**
