### PR TITLE
Clean-up EntityClassMetadataBinder and AnnotationDriver

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by Majkl578** [comment]
This is new code for 3.0, still yet to be used afaik. @guilhermeblanco will know more one this one.

**Comment by malukenho** [comment]
@Majkl578 the fact that it's already on master made it confuse for me. Should I close it then?

**Comment by Majkl578** [comment]
I'd say yes, master is still highly WIP and unstable (not really meant for testing in real-world apps), and will be for some time.

**Comment by malukenho** [comment]
Closing as invalid

**Pull request closed without merging**
