### PR TITLE
Fix undefined index for discriminator column `length` attribute in `SchemaTool`

### PR DESCRIPTION
**Pull request by sergeyfedotov**

### CODE REVIEW

**Comment by Ma27** [comment]
:+1:

**Comment by Ocramius** [comment]
@sergeyfedotov sorry for the huge wait: this has been merged into `master` and `2.5`

Thanks for your patch: it was pretty much pristine - it wasn't considered "merged" because I manually rebased it before merging.

**Comment by Ocramius** [comment]
`master`: doctrine/doctrine2@98aa25b0ea0248dd2c097454014f2ad04a288e3f
`2.5`: doctrine/doctrine2@1d1de7de80e17cc881715bd897b3624a5007cc6d

**Comment by dengm129** [comment]
master：98aa25b
2.5：1d1de7d

**Pull request closed without merging**
