### PR TITLE
#6118 Remove `EntityManager#flush($entity)` and `UnitOfWork#commit($entity)` functionality

### PR DESCRIPTION
**Pull request by Ocramius**
As per #6118, this patch removes support for `EntityManager#flush($entity)` and `UnitOfWork#commit($entity)`.

### CODE REVIEW

**Comment by Ocramius** [comment]
@guilhermeblanco note: tests fail because `develop` is due a rebase. @lcobucci can you eventually help with that?

**Comment by guilhermeblanco** [comment]
I have rebased already, but I'm fixing the associated bugs now. =)

**Comment by Ocramius** [comment]
@guilhermeblanco run a `composer update` then: `develop` has some mismatch with the `StatementInterface` from DBAL

**Comment by guilhermeblanco** [comment]
@Ocramius I'm already past that! =) working on fixing metadata written with old approach, and also addressing the annotations too

**Comment by Ocramius** [comment]
@guilhermeblanco lemme know when I should rebase this branch then  - the current upstream develop does fail with a fatal

**Comment by Ocramius** [comment]
@guilhermeblanco rebased and documented the BC break: feel free to merge into `develop` if it looks fine :+1:

**Review by guilhermeblanco — COMMENTED** [review]
YAY! Less one mess...

**Pull request merged**
