### PR TITLE
[DDC-3579] Allow override of inversedBy

### PR DESCRIPTION
**Pull request by z38**

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
Looks like a valid use case. Also, JPA 2.1 allows this too.

**Comment by Ocramius** [comment]
I also like the change, but it was delayed for 2.5: can land in 2.6.

Some of the tests may be stripped down a bit, but the change itself is simple and clean

**Comment by Ocramius** [comment]
I just realized that the only bit missing here is documentation :-\

**Comment by z38** [comment]
@Ocramius Thank you for taking a second look. I rebased against master and added a small note in the docs. Is there anything else I should improve?

**Comment by Ocramius** [comment]
@z38 all fine, merging :-)

**Comment by timmd909** [comment]
Why is it taking over 2 years for this to make it out of limbo and into a released version of Doctrine?

**Comment by Ocramius** [comment]
Because nobody is paid to do it: we do what we can, when we can.

On 8 Dec 2017 17:33, "Tim Doerzbacher" <notifications@github.com> wrote:

Why is it taking over 2 years for this to make it out of limbo and into a
released version of Doctrine?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/pull/1308#issuecomment-350308266>,
or mute the thread

**Comment by silentiumtempus** [comment]
Is there any chance this will be into prod in 2.7 ? ^^

**Comment by Majkl578** [comment]
This is already part of 2.6.x release.

**Pull request merged**
