### PR TITLE
Adding DIR to include statement to fix issue with pathing

### LINKED ISSUE #8563: vendor/bin/doctrine won't work, reporting missing 'doctrine.php'
I was following the doctrine2-ORM Getting Started Guide (just learning about Doctrine) where I encountered a following issue.

**ERROR MESSAGE:**
```
PHP Warning:  include(doctrine.php): Failed to open stream: No such file or directory in D:\*mypathtoproject*\DoctrineORM\doctrine2-tutorial\vendor\bin\doctrine(25) : eval()'d code on line 2
PHP Warning:  include(): Failed opening 'doctrine.php' for inclusion (include_path='.;C:\php\pear') in D:\*mypathtoproject*\DoctrineORM\doctrine2-tutorial\vendor\bin\doctrine(25) : eval()'d code on line 2
```

DOCTRINE CODE:
```
#!/usr/bin/env php
<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../doctrine/orm/bin/doctrine) using eval to remove the shebang if present
 *
 * @generated
 */

$binPath = realpath(__DIR__ . "/" . '../doctrine/orm/bin/doctrine');
$contents = file_get_contents($binPath);
$contents = preg_replace('{^#!/.+\r?\n<\?(php)?}', '', $contents, 1, $replaced);

if ($replaced) {
    $contents = strtr($contents, array(
        '__FILE__' => var_export($binPath, true),
        '__DIR__' => var_export(dirname($binPath), true),
    ));
    eval($contents);
    exit(0);
}
include $binPath;

```

This code returns `include(doctrine.php)`, however, this will of course not work, because `doctrine.php` is NOT present in the current directory where we are executing the `vendor/bin/doctrine`. 

However, when I commented out the` if block`, the code executed as expected. I assume this works because the `$binPath` correctly holds the absolute path to where `doctrine.php `is present.

This raises the question, why do we even do `eval()` in this script block? including the absolute path to `doctrine.php` seems to work just nice.

### PR DESCRIPTION
**Pull request by roo7cause**
Fixes #8563

### CODE REVIEW

**Comment by roo7cause** [comment]
This PR should fix the reported issue here:
https://github.com/doctrine/orm/issues/8563

I do not have permission to set Linked Issues on this repository.

**Comment by roo7cause** [comment]
@greg0ire if you will be reviewing this PR. Could you please do a proper test whether this is the best fix?

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
We don't have functional tests in that project, so the manual test you did will have to do I'm afraid.

**Comment by greg0ire** [comment]
Thanks @cybercitizen7 !

**Pull request merged**
