### PR TITLE
Backport #6167 from 2.6 to 2.5.x branch

### PR DESCRIPTION
**Pull request by gigi**
- Test mocks cherry-picked from 2.6 branch 
- Code cleanup for php5.4 support

### CODE REVIEW

**Comment by Ocramius** [comment]
Linking #6167

**Comment by lcobucci** [comment]
@gigi thanks for your help! I'll do the last checks and get it merged (and maybe released) later today 👍

**Review by lcobucci — APPROVED** [review]
LGTM 👍

**Comment by lcobucci** [comment]
@gigi 🚢 thanks!

**Comment by gigi** [comment]
Thank you guys! You're doing a great job! :1st_place_medal:

**Pull request merged**
