### PR TITLE
Use a more specific type for getSqlStatements()

### PR DESCRIPTION
**Pull request by greg0ire**
It is strictly beneficial for the Psalm baseline.

### CODE REVIEW

**Comment by mpdude** [comment]
https://github.com/doctrine/orm/blob/82533af893200dd0b28a235d898f12e735c8a76c/lib/Doctrine/ORM/Query/Exec/MultiTableUpdateExecutor.php#L90-L116

Not sure this is guaranteed to be a `list`... It might increment the counter in line 108, but not meet the condition in 116.

**Review by mpdude — COMMENTED** [review]
Not sure, see above

**Comment by greg0ire** [comment]
I wish there was a way to express the fact that the keys don't matter other than `mixed[]`, because then it seems that we neglected to specify the type of they keys, when what we really mean is: "the keys don't matter, don't rely on them".

Also, see how the returned property is currently annotated (although yes, it might very well be a lie depending on what you mean by `list`):

https://github.com/doctrine/orm/blob/82533af893200dd0b28a235d898f12e735c8a76c/lib/Doctrine/ORM/Query/Exec/AbstractSqlExecutor.php#L34-L35

**Comment by SenseException** [comment]
I interpreted `list<>` rather as "the keys have no meaning" than "doesn't matter" (or maybe you meant the same thing). Because a tool like PHPStan defines a list also as [sequential integer keys](https://phpstan.org/writing-php-code/phpdoc-types#lists) I'd usually see gaps in a sequence as `array<int, string>`.

Even if the keys don't matter, they can be (re-)used by a dev. I wonder if `list<string>` could break someone's PHPStan workflow of custom code build on ORM.

Does `array_is_list()` return `true` when used on `$this->sqlStatements` in some cases? I'd expect that there can happen some `false` cases.

**Comment by mpdude** [comment]
To my understanding, the difference between `array<T>` and `list<T>` is that a `list` has keys that are the sequential integers 0, 1, 2, ...?

**Comment by greg0ire** [comment]
"the keys have no meaning" is indeed what I meant, I think. In this case, it's possible there are gaps, but we should not be careful to preserve them, I don't think they have a meaning.

> To my understanding, the difference between array<T> and list<T> is that a list has keys that are the sequential integers 0, 1, 2, ...?

Yes, technically, but if we were using Python, the data structure we would be using here would be `list`. We wouldn't be using a dictionary, right? If it's not a list, that's an unwanted albeit unimportant side effect.

Anyway, I've amended my commit to make sure `list` is technically true, thus removing even more baseline blocks.

**Review by SenseException — APPROVED** [review]

**Review by mpdude — APPROVED** [review]

**Pull request merged**
