### PR TITLE
mysqli is supported by HHVM

### PR DESCRIPTION
**Pull request by photodude**
- reference to [Known compatible extensions for HHVM](http://docs.hhvm.com/manual/en/extensions.alphabetical.php)

### CODE REVIEW

**Comment by stof** [comment]
Looks like pgsql is not supported

**Comment by stof** [comment]
Please also rebase your changes to fix conflicts as the hhvm-nightly jobs are gone entirely in #1401 (the conflict should be easy to solve though)

**Comment by photodude** [comment]
@stof I'll see if I can get the rebase done later in the week. When I attempted the rebase this morning I keep getting a notice saying the branch was up to date with head. 

I've notice the issue with pgsql, seems it is supported but you have to [install an officially supported dependency.](https://github.com/PocketRent/hhvm-pgsql/tree/releases) I've played around a little trying to install the dependency for testing on Travis CI but I have not been successful in getting the dependency to install for a build.

**Comment by photodude** [comment]
@stof the changes have been rebased and is ready for merge consideration.

**Comment by jrobeson** [comment]
@photodude : btw that hhvm pgsql driver will end up getting merged into hhvm at some point in the near future.

**Comment by photodude** [comment]
@jrobeson That's interesting, everything I've read indicates PostgreSQL for HHVM is only going to be supported by 3rd party components and wasn't going to be included in the core HHVM. Even the [official documentation](http://docs.hhvm.com/manual/en/pgsql.installation.php) only indicates that the PostgreSQL extension is externally-provided. I also don't see anything indicating a change from the externally-provided extension plan in the roadmap for HHVM.

Can you elaboration on your source for PocketRent/hhvm-pgsql being included in the core HHVM?

**Comment by jrobeson** [comment]
Sara Golemon is going to do it.

**Comment by photodude** [comment]
@jrobeson That's great, I hope that comes about soon.

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
