### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by alcaeus**
This backports #7723 and #7876 to 2.6 for a release in 2.6.5.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by weaverryan — APPROVED** [review]
Thanks Andreas! Users will need *some* version of `doctrine/orm` that is compatible with Symfony 5. I hope this can be a simple path to that.

**Review by ostrolucky — APPROVED** [review]

**Comment by Ocramius** [comment]
Should target 2.7

**Comment by alcaeus** [comment]
> Should target 2.7

It is in 2.7 already. This is a backport into 2.6 as 2.7 won’t be done in time.

**Comment by Ocramius** [comment]
This cannot be merged to 2.6, sorry.

**Comment by Ocramius** [comment]
Also, this has been discussed extensively yesterday, and the maintainers of ORM are pretty much clear on the fact that there may be a delay of 2.7 to 2.8, while we release this as 2.7. it won't land in 2.6 though, and that's final.

**Pull request closed without merging**
