### PR TITLE
embeddedClasses support in mapped superclasses

### PR DESCRIPTION
**Pull request by vvh-empora**
...for JoinedSubclassPersister.php

### CODE REVIEW

**Comment by Ocramius** [comment]
Requires test case

**Comment by vvh-empora** [comment]
*help* is there a short tutorial how can a write a unittest for doctrine?

**Comment by Ocramius** [comment]
@vvh-empora see https://github.com/doctrine/doctrine2/blob/v2.4.4/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by vvh-empora** [comment]
ok, i give up, how can i run the unittest? i have run the "composer install" and try some configurations, but i always i get an error. if i want to run my new unittest:

> php vendor/bin/phpunit -c tests/travis/mysql.travis.xml ./tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3597Test.php

it fails with:

> PHP Fatal error:  Call to a member function getDatabasePlatform() on a non-object in /var/www/test/tests/Doctrine/Tests/OrmFunctionalTestCase.php on line 281

*help*

**Comment by Ocramius** [comment]
Can you just run it with sqlite instead?

**Comment by vvh-empora** [comment]
> sudo apt-get install sqlite
> php vendor/bin/phpunit -c tests/travis/sqlite.travis.xml ./tests/Doctrine/Tests/ORM/Functional/Ticket/DDC3597Test.php 
> PHPUnit 4.7-g47cce98 by Sebastian Bergmann and contributors.
>
> Configuration read from /var/www/test/tests/travis/sqlite.travis.xml
>
> E
>
> Time: 286 ms, Memory: 8.50Mb
>
> There was 1 error:
>
> 1) Doctrine\Tests\ORM\Functional\Ticket\DDC3597Test::testSaveImageEntity
Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver

hmmm ?

**Comment by vvh-empora** [comment]
> sudo apt-get install php5-sqlite
has fix the driver problem... but now, the unittest dosnt create the tables ?
> 1) Doctrine\Tests\ORM\Functional\Ticket\DDC3597Test::testSaveImageEntity
> Exception: [Doctrine\DBAL\Exception\TableNotFoundException] An exception occurred while executing 'INSERT INTO DDC3597Root (createdAt, updatedAt, discriminator) VALUES (?, ?, ?)':
>
>SQLSTATE[HY000]: General error: 1 no such table: DDC3597Root

???

**Comment by vvh-empora** [comment]
will this fix merge?

**Comment by vvh-empora** [comment]
ping @Ocramius

**Comment by kmfk** [comment]
+1.  Just ran into this today, Class Table Inheritance with embedded objects.

**Comment by eglizzy** [comment]
+1

**Comment by lucky7id** [comment]
:+1:

**Comment by Ocramius** [comment]
Good to go, thanks :-)

**Pull request merged**
