### PR TITLE
Fix applying ON/WITH conditions to first join in Class Table Inheritance

### PR DESCRIPTION
**Pull request by vitaliyberdylo**
Now we build nested joins for CTI when using ON/WITH clause.

### CODE REVIEW

**Comment by vitaliyberdylo** [comment]
Hello @Ocramius.
You have already discussed this issue with my colleague
https://twitter.com/ato0n1/status/541754890499145728
Merge this PR as quickly as possible please.
Thank you.

**Comment by Ocramius** [comment]
@vitaliyberdylo can you add a functional test involving a JTI?

Ping @guilhermeblanco since you already handled this issue once before, IIRC.

**Comment by guilhermeblanco** [comment]
@Ocramius I didn't... it was required to implement precedence of joins (which is what this patch does for JTI) and I left aside.

**Comment by vitaliyberdylo** [comment]
Hello @Ocramius.
Do i need to do something like this https://github.com/doctrine/doctrine2/pull/668/files?
It PR must be into master and 2.4 or only 2.4?

**Comment by Ocramius** [comment]
@vitaliyberdylo this will go in 2.5 for now, and may be backported later on

**Comment by Ocramius** [comment]
I could also need a test case with a DQL query actually producing failing previously to this patch.

Should be doable with some of the existing test assets.

**Comment by guilhermeblanco** [comment]
@Ocramius that's only the tip of the iceberg... if we go down the precedence of joins path, we should also properly address whatever got listed in http://www.doctrine-project.org/jira/browse/DDC-349

**Comment by Ocramius** [comment]
This PR is already applied to `master`, therefore only merging into `2.4.`

**Comment by Ocramius** [comment]
Thanks @vitaliyberdylo!

**Comment by vitaliyberdylo** [comment]
Thank you guys!

**Pull request merged**
