### PR TITLE
DefaultQuoteStrategy::getTableName now returns correctly quoted table name

### PR DESCRIPTION
**Pull request by massimilianobraglia**
This PR aims to fix the use of reserved keywords as table names using DefaultQuoteStrategy.

### CODE REVIEW

**Comment by Ocramius** [comment]
I think this got already changed in `master`, where quoting is supposed to happen at all times. @guilhermeblanco can you confirm that?

**Comment by guilhermeblanco** [comment]
@Ocramius everything is quoted (and cannot be turned off) in `master`.

**Comment by Ocramius** [comment]
Closing as `duplicate` then

**Comment by massimilianobraglia** [comment]
Hello everybody, just a question. This can be merged into 2.6/2.7? In this way the default quote strategy will work as expected.

**Comment by Ocramius** [comment]
@massimilianobraglia `2.x` is closed for improvements

**Pull request closed without merging**
