### PR TITLE
Readme: badges for 2.5 added; 2.3- dropped

### PR DESCRIPTION
**Pull request by TomasVotruba**
If I understand [2.5 release info](https://github.com/doctrine/doctrine2/releases/tag/v2.5.0) correctly, 2.4 will have last bugfix release, then security fixes. I suppose then 2.3 and lower are in EOL, thus not needed to check badge for. Also they don't have any active branch.

Also, may I suggest flat badges unified for both Travis and Coveralls?

https://img.shields.io/badge/style-flat--squared-green.svg?style=flat-square

### CODE REVIEW

**Comment by Ocramius** [comment]
> Also, may I suggest flat badges unified for both Travis and Coveralls?

Yes please!

**Comment by TomasVotruba** [comment]
Great. Can I also rename it to `README.md` to be compatible with other .md files?

**Comment by Ocramius** [comment]
Sure, go on :-)

**Comment by TomasVotruba** [comment]
Done :)

**Comment by Ocramius** [comment]
@TomasVotruba thanks!

**Comment by TomasVotruba** [comment]
Thanks!

**Pull request merged**
