### PR TITLE
fixed memory leak while iterating results

### PR DESCRIPTION
**Pull request by stlrnz**
I've tried to fix the issue described in https://github.com/doctrine/orm/issues/8410

### CODE REVIEW

**Comment by beberlei** [comment]
@simPod can you say something?

**Comment by stlrnz** [comment]
I've checked why the test https://github.com/doctrine/orm/pull/8412/checks?check_run_id=1654953910 failed. 

It seems that the `ObjectHydrator` in contrast to the `SimpleObjectHydrator` does need `$result` to be persistent.
So maybe this is not the correct solution for the linked issue?

**Comment by simPod** [comment]
@stirnz same test run fails for `iterate()` as well, it was not tested for that case though while `toIterable()` is. Looking into it.

**Comment by simPod** [comment]
I remember being [tasked](https://github.com/doctrine/orm/pull/7885#issuecomment-587250359) with fixing https://github.com/doctrine/orm/issues/3238 which introduced the memory leak as we're keeping result in memory now. Looking for workaround.

**Comment by beberlei** [comment]
Related https://github.com/doctrine/orm/pull/8414

**Pull request closed without merging**
