### PR TITLE
RunDqlCommand: Use VarDumper when available

### PR DESCRIPTION
**Pull request by nicolas-grekas**
VarDumper output is so much prettier than var_dump's ;)

### CODE REVIEW

**Comment by Ocramius** [comment]
This introduces a soft dependency to an external component. No-go: override it in DoctrineBundle instead.

**Comment by nicolas-grekas** [comment]
You have a dep on symfony/console...

**Comment by Ocramius** [comment]
`symfony/console` is not `symfony/var-dumper`

**Comment by nicolas-grekas** [comment]
This is a matter of taste... The PR just makes using the command a bit nicer, optionally.
But anyway, you decide.

**Comment by beberlei** [comment]
I agree we can add this in DoctrineBundle, but here is not the right place.

**Comment by nicolas-grekas** [comment]
So, I should instead copy/paste the command in the bundle and overwrite this one?

**Comment by Ocramius** [comment]
Pretty much, yes :-)

**Comment by stof** [comment]
I suggest adding a protected method for the dumping part, so that the bundle can overwrite it. the bundle is already extending the command class anyway.

**Comment by guilhermeblanco** [comment]
+1 on previous comments

**Pull request closed without merging**
