### PR TITLE
Try running the tests on Oracle

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
:snail:

**Comment by greg0ire** [comment]
Maybe the error handling is what is so slow :thinking:

**Comment by greg0ire** [comment]
Locally strace via htop shows numerous calls to `getrusage` and `mmap`.

**Comment by greg0ire** [comment]
Closing as apparently, Oracle is known to be super slow, which is not noticeable on the DBAL unless you compare it to other jobs which indeed take 10 secs vs more 1m 15s for Oracle

**Comment by beberlei** [comment]
@greg0ire we could create the oracle job as once per week cron on the current active branch(es)

**Comment by greg0ire** [comment]
Indeed :thinking:

**Comment by dkarlovi** [comment]
Careful, this might be interpreted as against Oracle ToS:
https://stackoverflow.com/a/12116865/672885

**Comment by greg0ire** [comment]
> Maybe the error handling is what is so slow

@dkarlovi Did I write "slow"? I meant "fast"

**Comment by dkarlovi** [comment]
_Oracle lawyers stop sharpening their pencils_

**Pull request closed without merging**
