### PR TITLE
Fix commit order

### PR DESCRIPTION
**Pull request by tomaszgaw**
Fixes visit method of CommitOrderCalculator.

Without the fix the insertion order is not properly calculated when a cycle within the graph involves more than 2 classes, leading to a violation of not null constraints on the owning side of ManyToOne relation.

With the fix when a cycle is detected a node is revisited ignoring edges of weight 0.

### CODE REVIEW

**Comment by jhony1104** [comment]
This PR fixes [#7866](https://github.com/doctrine/orm/issues/7866).

@tomaszgaw: if you are interested in adding a test for this, it can be found here: https://gist.github.com/jhony1104/3c0793be7f1ee2fb9b933e1ee3734782

What is the status of this PR?

**Comment by derrabus** [comment]
> What is the status of this PR?

Well, it has been open for a while. If it's still relevant, it needs a rebase and a functional test that reproduces the issues that it tries to fix.

**Comment by beberlei** [comment]
We also have a bunch of commit order related PRs already. Its very complex algo with all rhe side effects and requirements, therefore it requires lots of maintainer time to review and trust to merge.

**Comment by jhony1104** [comment]
The product I am working on runs in a lof of issues with the commit order calculator. Because of this we are using a modified fork of doctrine wich changes the commit order calculator.These changes were made to 2.9.6.

A few weeks ago I war updating doctrine and since the plain doctrine was still having the same issues and our old patch was also no longer working as expeted I tried some of the PRs on this repos.

I am sorry to report, that this PR can - in some cases - still calculate the wrong commit order. In fact, I am not sure if the algorithm used (modified topolocical sorting with weights) can - without larger changes than modifying weights - ever reliably calculate the correct commit order.

For the software I am working on, I did create a new patch that treats all edges as required (not nullable) and on detecting a loop backtracks to the last optional (nullable) edge, skips it an continues. This is of course much less performant, but should allways be correct. It can be found [here](https://github.com/jhony1104/doctrine-orm). I am not sure if I should create a PR for it (performance, larger changes, ...).

**Comment by mpdude** [comment]
@jhony1104 and @tomaszgaw you might be valuable reviewing #10547.

**Pull request closed without merging**
