### PR TITLE
Failing test for #8337

### PR DESCRIPTION
**Pull request by Seb33300**
Failing test for #8337

### CODE REVIEW

**Comment by lcobucci** [comment]
@Seb33300 the test expectations is incorrect. The preFlush event is dispatched in the beginning of the flush operation. If you call flush twice you will have two events.

**Comment by Seb33300** [comment]
If you flush twice on an entity which has modified fields the `UPDATE` query will be executed only once unless you persist again the entity before the second flush. Right?
I was expecting the same behavior with events.

So, how can we prevent event to be executed multiple times on the same entity if we have several flush?

**Comment by lcobucci** [comment]
The ORM is built on top of the [Unit of Work pattern](https://www.martinfowler.com/eaaCatalog/unitOfWork.html). The flush operation commits the UoW to finalise the business transaction.

Having multiple flushes in a single business transaction is a wrong usage of the pattern (and the ORM).

**Comment by Seb33300** [comment]
Unfortunately the app was built like this and it could be quite complex to change it.

I am trying to understand why queries operations are executed only on the first `flush` call by the UoW but event operations are executed on every `flush` calls.
`flush` should flush all operations (queries & events), not only queries.

**Comment by lcobucci** [comment]
> I am trying to understand why queries operations are executed only on the first flush call by the UoW but event operations are executed on every flush calls.
> flush should flush all operations (queries & events), not only queries.

@Seb33300 that's a misunderstanding of the architecture. As mentioned in our [docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/events.html#preflush), `preFlush` is called before anything happens (even the changeset calculation).

> Unfortunately the app was built like this and it could be quite complex to change it.

That's a common mistake but IMHO we shouldn't adapt the ORM because of misusages.

It's also worth mentioning that the events used by the ORM aren't meant to trigger business rules, so if your app is also coupled to them I'd strongly recommend dispatching your own domain events.

**Comment by lcobucci** [comment]
Closing as invalid based on the discussion.

**Pull request closed without merging**
