### PR TITLE
Upgrade PHPStan to 0.9.x

### PR DESCRIPTION
**Pull request by lcobucci**
To avoid having weird bugs

### CODE REVIEW

**Comment by Majkl578** [comment]
I'm 👎 on this, it will break in long run and cause unexpected test failures. :/

**Comment by lcobucci** [comment]
@Majkl578 I think this is not a problem since I've configured a cron job in Travis to run the build in master daily, then we ensure that PRs won't be influenced by phpstan fixes. But I can modify the patch to simply bump to `0.9`

**Comment by lcobucci** [comment]
@Majkl578 updated ;)

**Comment by Majkl578** [comment]
> then we ensure that PRs won't be influenced by phpstan fixe

Only if someone finds time to fix them in meantime. 😄 

I prefer just bumping the version to 0.9. I've been using PHPStan since version 0.6, originally on level 5, now level 7, and every single version introduced new sniffs or features that found new errors. Since PHPStan is still 0.x version I think it's safer to stay locked at specific version for now. :)

**Pull request merged**
