### PR TITLE
Fix error undefined index "targetEntity"

### PR DESCRIPTION
**Pull request by andersonamuller**

### CODE REVIEW

**Comment by Ocramius** [comment]
Dang, how did this slip in?

@andersonamuller when does this happen for you? Can we have a test case showing the notice?

**Comment by andersonamuller** [comment]
Sorry, I don't have much time now for a test case, try this setup:

Classes:
```php
abstract class Animal 
{
    protected $id
}

class Cat extends Animal
{
    private $sound
}

class Sound 
{
    private $id
}
```
Mapping `Animal`:
```php
/** @var \Doctrine\ORM\Mapping\ClassMetadata $metadata */
$builder = new \Doctrine\ORM\Mapping\Builder\ClassMetadataBuilder($metadata);
$builder->setTable('animal');
$builder->setSingleTableInheritance();
$builder->setDiscriminatorColumn('kind', 'string', 32);
$builder->createField('id', 'binary')->isPrimaryKey()->build();
```
Mapping `Cat`:
```php
/** @var \Doctrine\ORM\Mapping\ClassMetadata $metadata */
$builder = new \Doctrine\ORM\Mapping\Builder\ClassMetadataBuilder($metadata);
$builder->createOneToOne('sound', Sound::class)->fetchLazy()->addJoinColumn('sound_id', 'id', false)->build();
```
Mapping `Sound`:
```php
/** @var \Doctrine\ORM\Mapping\ClassMetadata $metadata */
$builder = new \Doctrine\ORM\Mapping\Builder\ClassMetadataBuilder($metadata);
$builder->setTable('sound');
$builder->createField('id', 'binary')->isPrimaryKey()->build();
```

**Comment by Ocramius** [comment]
@andersonamuller I'll try integrating it with the test suite now

**Comment by Ocramius** [comment]
I integrated tests and merged everything in `master` at doctrine/doctrine2@d8d4ec6eb2cd1c276bd90b4f419e4caa75b15233

Thanks @andersonamuller!

**Comment by andersonamuller** [comment]
@Ocramius 
My pleasure, thank you for your hard work. Looking forward for the release.

**Pull request merged**
