### PR TITLE
fix: support array-type arg in QB variadic calls

### LINKED ISSUE #11241: 3.0 - QueryBuilder - multi-select is not supported
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0

#### Summary

I'm working on ORM 3 and DBAL 4 support on phpstan-doctrine, and I have this test case:

```
		$this->entityManager->createQueryBuilder()
			->select([
				'e.id',
				'e.title',
			])->from(MyEntity::class, 'e')
			->getQuery();
```

When this method is called, Doctrine crashes with: `Cannot use "::class" on array` originating here:

* https://github.com/doctrine/orm/blob/5a40b99e11a0de532eb866f062dccad20da19add/src/Query/Expr/Base.php#L63
* https://github.com/doctrine/orm/blob/5a40b99e11a0de532eb866f062dccad20da19add/src/Query/Expr/Base.php#L48
* https://github.com/doctrine/orm/blob/5a40b99e11a0de532eb866f062dccad20da19add/src/Query/Expr/Base.php#L36
* https://github.com/doctrine/orm/blob/5a40b99e11a0de532eb866f062dccad20da19add/src/QueryBuilder.php#L620

This is how `$select` looks like when coming into `new Expr\Select($select)`:

```
array(1) {
  [0]=>
  array(2) {
    [0]=>
    string(4) "e.id"
    [1]=>
    string(7) "e.title"
  }
}
```

#### Current behavior

The method throws an exception.

#### Expected behavior

It should work because even current 3.0 documentation mentions the possibility to pass arrays into the `select` method: https://www.doctrine-project.org/projects/doctrine-orm/en/3.0/reference/query-builder.html#high-level-api-methods

### PR DESCRIPTION
**Pull request by simPod**
Broke the behaviour in https://github.com/doctrine/orm/pull/8319 (see https://github.com/doctrine/orm/pull/8319#discussion_r1484269817)

Fixes https://github.com/doctrine/orm/issues/11241

### CODE REVIEW

**Comment by simPod** [comment]
cc @ondrejmirtes

**Review by greg0ire — APPROVED** [review]
Not sure what's the point of passing an array, but since this was an involuntary breaking change…

**Comment by ondrejmirtes** [comment]
> Not sure what's the point of passing an array,

It's one of the top examples in the docs :)

**Review by derrabus — APPROVED** [review]
🙈 

Let's please deprecate this in 3.1.

**Pull request merged**
