### PR TITLE
Annotations docs examples actualization

### PR DESCRIPTION
**Pull request by AlexVasechkin**
Unique constraints annotations actualization @Table->@ORM\Table and @UniqueConstraint->@ORM\UniqueConstraint

### CODE REVIEW

**Comment by greg0ire** [comment]
Why only these 2 specifically?

**Comment by AlexVasechkin** [comment]
Becose i faced with the problem the example does`t works. I want to fix this problem.

**Comment by SenseException** [comment]
It makes sense to update all namespaces on this page and make all the examples work. Could you please do that?

**Comment by AlexVasechkin** [comment]
I will fix.

**Comment by beberlei** [comment]
@SenseException @greg0ire This is not a small topic to tackle and requires some strategy. Current examples are based on the SimpleAnnotationReader everywhere in the docs at the moment. A change here must also update the docs on setup with Symfony based approach.

**Comment by SenseException** [comment]
@beberlei I agree. But does this affect the current changes of this PR between `SimpleAnnotationReader` and `AnnotationReader`?

**Pull request closed without merging**
