### PR TITLE
Fix query andX doctype

### PR DESCRIPTION
**Pull request by sserbin**

### CODE REVIEW

**Review by Ocramius — DISMISSED** [review]

**Comment by Ocramius** [comment]
Needs to be ported to `master` too

**Comment by sserbin** [comment]
(pardon my ignorance) should I open another pull request against master or will you cherry-pick it after merge?

**Comment by Ocramius** [comment]
No, we will cherry-pick from our end :+1:

**Comment by SenseException** [comment]
Will 2.7 be rebased/cherry picked too?

**Comment by Ocramius** [comment]
@SenseException yep

**Review by Majkl578 — APPROVED** [review]

**Pull request merged**
