### PR TITLE
Streamline documentation code block type hints for readability

### PR DESCRIPTION
**Pull request by afoeder**
This corrects a mistake with a given type hint in
the PHP code blocks as well as adds further for
consistency and brevity.

### CODE REVIEW

**Comment by Ocramius** [comment]
@afoeder does this affect only `2.6`?

**Comment by afoeder** [comment]
oh didn't watch out @Ocramius most likely it "was never correct". Shall I edit it to PR into _master_?

**Comment by Ocramius** [comment]
Yes please - whether it is worth backporting I'll leave to @doctrine/team-documentation and @doctrine/team-orm-documentation

**Comment by jwage** [comment]
Merging just to master is fine.

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thank you @afoeder!

**Pull request merged**
