### PR TITLE
Drop doctrine/lexer 1

### PR DESCRIPTION
**Pull request by greg0ire**
This is a backport of #10309 , except I'm not migrating to an enum for obvious reasons.

### CODE REVIEW

**Comment by derrabus** [comment]
I'm unsure if it isn't too soon to merge this PR into 2.x. We should watch the adoption of Lexer 2 a bit before we merge this change. Right now, Symfony's CI would be pinned to 2.14 if we merged this PR.

**Comment by greg0ire** [comment]
Ok, I'm not in a hurry.

**Comment by derrabus** [comment]
At least egulias/EmailValidator#340 should be resolved first. That package is used by Symfony Mailer and Validator.

**Comment by derrabus** [comment]
> At least [egulias/EmailValidator#340](https://github.com/egulias/EmailValidator/pull/340) should be resolved first.

✅ Now, Symfony's CI is fully unblocked and uses Annotations 2 and Lexer 2 everywhere. ✌🏻

**Comment by greg0ire** [comment]
@derrabus feel free to rebase this, I tried resolving the conflict from my phone but couldn't.

**Review by SenseException — APPROVED** [review]

**Pull request merged**
