### PR TITLE
[2.19.x] Fetching entities with Composite Key Relations and null values

### PR DESCRIPTION
**Pull request by michalbundyra**
Changes from #11486 into 2.19.x

### CODE REVIEW

**Comment by greg0ire** [comment]
Please squash both commits and use a summary of the description of #11486 . This should be understandable with the git log alone.

**Review by greg0ire — COMMENTED** [review]
Code-wise, I think it looks good, since no existing tests are changed. If it turns out this is useful, we will revert and ask people to add tests to protect their weird use cases.

**Comment by michalbundyra** [comment]
@greg0ire thanks, squashed, rebased and force-pushed now.

**Comment by greg0ire** [comment]
> use a summary of the description

Can you please amend your commit message to include a summary of the description?

**Comment by greg0ire** [comment]
More on this in [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches).

**Comment by michalbundyra** [comment]
@greg0ire thanks, pushed now, hope it makes sense.

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @michalbundyra !

**Comment by michalbundyra** [comment]
@greg0ire thanks for merging, I guess it will be pushed forward into 3.x as well, right?

There is still the other PR open with 3.2.x target: https://github.com/doctrine/orm/pull/11486 as it is quite different in terms of tests etc.

Thanks

**Comment by greg0ire** [comment]
> I guess it will be pushed forward into 3.x as well, right?

Yes, it should get merged up at some point. When that happens, maybe we will have to look at your PR to resolve conflicts/adapt the code, or maybe not and then you can rebase and improve things.

**Pull request merged**
