### PR TITLE
Make EntityManager `@final` and its constructor public

### LINKED ISSUE #9896: Make EntityManager::__construct() public
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Right now, one is forced to call `EntityManager::create()` in order to instantiate an entity manager.

This makes the ORM hardly compatible with lazy ghost objects. The reason is that lazy ghost objects need to first be created with e.g. `ReflectionClass::newInstanceWithoutConstructor()` and later on be populated on demand.

Right now, the object graph contains e.g: EM -> UOW -> EM. This circular reference is defined in the constructor of EM.

Because of the factory, the current process when creating a lazy ghost object involves the following steps:
- create empty EM1
- on demand: trigger EM1 initialization
- initialization calls the factory, which returns a populated EM2 (which contains UOW -> EM2)
- copy all properties of EM2 into EM1 to initialize EM1 as needed

The resulting object graph is EM1 -> UOW -> EM2. It's broken of course.

If the constructor were made public, one could call the constructor in the initialization step and this concern would disappear.

The alternative right now would be to deep-search-n-replace EM2 by EM1 in EM1, but this would be super hacky code involving complex reflection/rebinding logic (and incompatible with `readonly` even if EM doesn't use it for now.)

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fix #9896

### CODE REVIEW

**Comment by derrabus** [comment]
Thanks. Can you have a look at the failing tests?

**Comment by nicolas-grekas** [comment]
Likely not before a week but otherwise yes!
What about removing the last argument of the constructor btw?

**Comment by derrabus** [comment]
> What about removing the last argument of the constructor btw?

That's probably a good idea.

**Comment by nicolas-grekas** [comment]
Tests updated, PR should be ready.

**Review by derrabus — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
There was a cancelled job, I'm running it again, hopefully it will pass. I don't know why it was cancelled.

**Comment by greg0ire** [comment]
The performance of that job is suspiciously bad: https://github.com/doctrine/orm/runs/7559763390?check_suite_focus=true, even when compared with this other random PR: https://github.com/doctrine/orm/runs/7558748372?check_suite_focus=true
Let me re-run that last one.

**Comment by greg0ire** [comment]
It's slower than usual (1m13), but not as slow, let me restart the first one then.

**Comment by greg0ire** [comment]
53s :slightly_smiling_face:

**Comment by greg0ire** [comment]
Thanks @nicolas-grekas !

**Comment by nicolas-grekas** [comment]
Thanks for merging \o/

**Pull request merged**
