### PR TITLE
Remove comment for getDiscriminatorColumn

### PR DESCRIPTION
**Pull request by KartaviK**
`getDiscriminatorColumn()` does not exist any more in this repo

### CODE REVIEW

**Comment by SenseException** [comment]
@greg0ire Do you have a guess why Coding Standards is having this error?

**Comment by greg0ire** [comment]
No, let's troubleshoot this.

**Comment by greg0ire** [comment]
Looks like a Heisenbug :/

**Comment by greg0ire** [comment]
Let's try upgrading `git-phpcs`.

**Comment by greg0ire** [comment]
I can't promise that the error will not come back in a later PR, but at least we are up to date

**Comment by SenseException** [comment]
@greg0ire If we can reproduce it on demand, we'll create a PR to debug it. Thank you for making the build green.

**Review by SenseException — DISMISSED** [review]
@KartaviK Thank you for catching this.

**Pull request closed without merging**
