### PR TITLE
Describe return types more accurately

### LINKED ISSUE #8642: How to create schema using Schema tool in v2.9.x?
`SchemaTool::createSchema()` expects `list<Doctrine\ORM\Mapping\ClassMetadata>`.

I used to pass in metadata created as `$entityManager->getMetadataFactory()->getAllMetadata()` that returns `array<Doctrine\Persistence\Mapping>` so it's incompatible now.

I checked this I but seems to have the same issue https://github.com/doctrine/orm/blob/bcb4889a2c8eb57080f10494554dad5a0ffb1434/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php#L58-L66

### PR DESCRIPTION
**Pull request by greg0ire**
This fixes an SA regression introduced when using stricter types in
SchemaTool.

Fixes #8642

### CODE REVIEW

**Comment by greg0ire** [comment]
@orklah @simPod please review

**Review by simPod — APPROVED** [review]
As a fix this works 👌🏾.

Generics as mentioned here https://github.com/doctrine/orm/issues/8642#issuecomment-822627548 can be added in the future IMO.

**Comment by greg0ire** [comment]
I gave it a try, you can take a look at https://github.com/doctrine/persistence/pull/167

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Once 2.2.0 is released, I will use generics.

**Pull request merged**
