### PR TITLE
Identity map cannot contains null value

### PR DESCRIPTION
**Pull request by PowerKiKi**
This reduce psalm errors/warnings count

### CODE REVIEW

**Comment by greg0ire** [comment]
> This reduce psalm errors/warnings count

Do you maybe need to update the psalm baseline?

**Comment by PowerKiKi** [comment]
psalm baseline updated and rebased on top of latest 2.13.x

**Review by greg0ire — DISMISSED** [review]

**Comment by PowerKiKi** [comment]
I'm not super familiar with psalm, but I *think* the failing CI is not related to my changes. Let me know if I should do something more...

**Comment by greg0ire** [comment]
An easy to figure it out is to run

```
git switch -d origin/2.13.x
vendor/bin/psalm
```

I haven't seen this failure on other recent PRs, so I wouldn't be so sure if I were you. Not that you seem very sure :stuck_out_tongue:

**Comment by mpdude** [comment]
You want to give this another try?

**Comment by PowerKiKi** [comment]
Thanks for the reminder. I rebased on top of 2.14.x. It should be mergeable now.

**Comment by greg0ire** [comment]
Retargeted to 2.15.x since this is `|null` is technically not wrong.

**Comment by greg0ire** [comment]
Also, I updated the Psalm baseline.

**Review by greg0ire — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Pull request merged**
