### PR TITLE
 Added check for non-nullable property when deleting a record

### PR DESCRIPTION
**Pull request by joaojacome**
Solves #7999

### CODE REVIEW

**Comment by beberlei** [comment]
This needs to be fixed in doctrine/persistence instead. We already have a `TypedNoDefaultReflectionProperty` overwrite for `ReflectionProperty` there and it only needs an addition to `setValue()` to handle the `NULL` case as `unset()`. The problem is your unset() code here only works on public properties, it will cause an error on protected or private ones.

A workaround needs to be found to unset any kind of visibility property. The following is a prototype using closure and binding to this, but it doesn't seem to work: https://gist.github.com/beberlei/f28142a1b15f011bbcd0156c7aa64430

**Comment by beberlei** [comment]
Have the right approach thanks to @lcobucci now, updated the gist.

**Comment by prof-web-coding** [comment]
@joaojacome Will you update the code according to @beberlei 's input?

**Comment by joaojacome** [comment]
> @joaojacome Will you update the code according to @beberlei 's input?

I could, but I think @beberlei fixed it here:
https://github.com/doctrine/reflection/issues/34

**Comment by prof-web-coding** [comment]
Thanks. It does not work for me. I have a
`/**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private int $id;` in an `Doctrine\ORM\Mapping\Entity` and I'm getting`Error: Cannot access private property App\Entity\User::$id`. It seems that the newly added setValue in [lib/Doctrine/Common/Reflection/TypedNoDefaultReflectionProperty.php](url) is not called, also not without #23b57f6

**Pull request closed without merging**
