### PR TITLE
Use `equal to` instead of `equal of` in `assertSqlGeneration()`

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by greg0ire** [comment]
Restarting the build after the merge up

**Comment by greg0ire** [comment]
:thinking: 🤔 🤔 Why are you contributing this to 3.0.x and not 2.10.x?

**Comment by simPod** [comment]
I had 3.0 checked out. changed.

**Review by derrabus — APPROVED** [review]

**Comment by greg0ire** [comment]
I think the right order for this was switch branch, and then force push, Github CI looks confused…

**Pull request merged**
