### PR TITLE
Address deprecations from Collection 2.2

### PR DESCRIPTION
**Pull request by derrabus**
Part of #11313.

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

**Comment by greg0ire** [comment]
"Bug" is not really the right label, is it?

**Comment by derrabus** [comment]
> "Bug" is not really the right label, is it?

The current code triggers deprecations that it should not trigger. That is a bug. But we can reclassify if you're not comfortable shipping this change as a bugfix.

**Comment by greg0ire** [comment]
I'm comfortable shipping it in a patch release, but I think we might want to have a separate label for when we address deprecations, like maybe "Addressed deprecation" (can't think of something better right now, sorry). If we say it's a bug, it means other packages can decide to cause bugs in our projects from one release to the next minor release, although we did nothing wrong.

**Comment by derrabus** [comment]
> If we say it's a bug, it means other packages can decide to cause bugs in our projects from one release to the next minor release, although we did nothing wrong.

"Bug" is a totally blame-free word for me. I never said the we could've anticipated the issue that I've fixed here.

**Comment by greg0ire** [comment]
I think that makes some sense. Ignore me then.

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
