### PR TITLE
[Small Enhancement] Make scalar field separator overwritable

### PR DESCRIPTION
**Pull request by eliecharra**
I would like to have a custom Hydrator extending ScalarHydrator just to change field separator ('_'), but I dont want to overwrite all method.
It's not very risky to make it extensible.

### CODE REVIEW

**Comment by Ocramius** [comment]
This is internal API, not supposed to be extensible in first place.

**Comment by eliecharra** [comment]
@Ocramius Ok, protected accessors put me doubt

**Comment by Ocramius** [comment]
Well, it's indeed a bit of a messy re-use abstract class in the ORM, but you shouldn't really rely on it. What is the use-case?

**Comment by eliecharra** [comment]
@Ocramius Handle a backward compatibility with a bundle which create his own scalar array with a custom normalizer behind a ```$query->getArrayResult()```.
Dots are used to separate fields in previous versions.
Of course I could re-implement a full custom scalar hydrator, feel free to dismiss

**Comment by Ocramius** [comment]
That indeed sounds like a weird misuse :-\

Dismissing then, as per discussion. Thanks for your understanding :)

**Pull request closed without merging**
