### PR TITLE
add possibility to use sql comments in the DQL syntax

### PR DESCRIPTION
**Pull request by philippe-levan**
Hi,

Sometimes I want to add sql comments in DQL queries. This PR adds the possibility to use comments in DQL.

:warning: this PR is for the branch 2.8.x

Best regards,
Philippe

### CODE REVIEW

**Comment by greg0ire** [comment]
You can run `vendor/bin/phpcbf` to fix the build

**Comment by philippe-levan** [comment]
Hi @greg0ire,

I didn't use phpcbf because it made to many changes on the file. I just fixed the coding style by hand. I believe this phpcbf should be run outside this feature PR in this case.

I added a documentation.

Thanks for your feedbacks,
Best regards,
Philippe

**Comment by greg0ire** [comment]
> I didn't use phpcbf because it made to many changes on the file.

You did well. I forgot we have this special behavior in this repo where we only fix CS for new code.

**Review by ostrolucky — APPROVED** [review]

**Comment by guilhermeblanco** [comment]
LGTM

**Comment by philippe-levan** [comment]
> LGTM

Sorry @guilhermeblanco, but what does mean LGTM ?

**Comment by greg0ire** [comment]
https://www.urbandictionary.com/define.php?term=LGTM :) (I don't think it's the sixth meaning, don't worry)

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @philippe-levan !

**Comment by philippe-levan** [comment]
Thanks for the merge !

**Comment by philippe-levan** [comment]
@greg0ire : do you want me to create the equivalent PR on master ?

**Comment by greg0ire** [comment]
No don't worry, it will get merged up in time.

**Pull request merged**
