### PR TITLE
Resolving relationships with interface and Abstract

### LINKED ISSUE #7670: Resolving target entities from abstract class seems to not working as expected
Hello, according to the [How to Define Relationships with Abstract Classes and Interfaces](https://symfony.com/doc/current/doctrine/resolve_target_entity.html), I should be able to use the `ResolveTargetEntityListener` to resolve an abstract class to a specific entity.

**However, this "feature" seems to not working properly.**

## 1. Using an interface
Here is the PHP code used to resolve the interface to the entity class;
```php
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(RedirectRouteInterface::class)
    ->getName();
```
> **$registry** is an instance of `\Doctrine\Common\Persistence\ManagerRegistry`

When configuring doctrine using an interface like:
```yaml
doctrine:
    orm:
        resolve_target_entities:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: App\Entity\RedirectRoute
```
everything is working perfectly and the name is equals to `App\Entity\RedirectRoute`

## 2. Using an abstract class
Now when I'm trying to resolve an entity from an abstract class, the resolver seems to not working properly.
Here is the PHP code used to resolve the abstract class to the entity class:
```php
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(AbstractRedirectRoute::class)
    ->getName();
```
> **$registry** is an instance of `\Doctrine\Common\Persistence\ManagerRegistry`

When configuring doctrine using an abstract class like:
```yaml
doctrine:
    orm:
        resolve_target_entities:
            App\Model\AbstractRedirectRoute: App\Entity\RedirectRoute
```
In that case, the resolver is returning the abstract class FQCN: `App\Model\AbstractRedirectRoute`.

Weird thing is, to be able to resolve the abstract class I need to make the call to `getAllMetadata()` method like:
```php
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getAllMetadata();
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(AbstractRedirectRoute::class)
    ->getName();
```
In that case, the entity is resolved correctly!

---
**Is this an issue or more a miss-configuration on my side?**

### PR DESCRIPTION
**Pull request by Zul3s**
Fixes #7670

### CODE REVIEW

**Review by kuronana — DISMISSED** [review]

**Comment by Zul3s** [comment]
Hi, sorry, but what can i do to fix CI problem ?

**Comment by greg0ire** [comment]
The failure looks related to #8249

**Comment by Zul3s** [comment]
Ok thank you. So if i understand good, i can do nothing, just waiting :) .

**Review by greg0ire — COMMENTED** [review]
Please add some tests

**Comment by Zul3s** [comment]
Hi, 
I am sorry, but it's realy hard to  make tests with sense. 
The problem case is with Symfony validation schema (toolbar and command) and Bundle Entities. I can not understand why, but bundle entites is not in associationMappings on \Doctrine\ORM\Tools\ResolveTargetEntityListener::loadClassMetadata. So the remapAssociation will be not execute. In my tests, remapAssociation is always execute. 

The problem is not present on Doctrine Migration (ex. doctrine:migration:diff nothing to do). 

Have you an advise for me plz ? 

Without fix 
image
With fix 
image

**Comment by greg0ire** [comment]
> Have you an advise for me plz ?

Yes: show us the tests you have tried to write, maybe we will be able to understand more what makes the tests hard to write.

**Pull request closed without merging**
