### PR TITLE
Backport `NonProxyLoadingEntityManager::refresh()` signature change

### PR DESCRIPTION
**Pull request by michnovka**
BP as requested in https://github.com/doctrine/orm/pull/10196

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
btw, the email address that you use when authoring your commits is not connected to your GitHub account. You should fix that if you want your contributions to be counted.

**Comment by michnovka** [comment]
@derrabus what do you mean, what e-mail do u see when authoring the commits?

**Comment by michnovka** [comment]
OK, I understand. Will fix for future commits

**Comment by derrabus** [comment]
If you want to change the author of the commit in this PR, please do so. I can wait with the merge.

You can also register more email adresses with your account on https://github.com/settings/emails. That should give you credit for the commits I've already merged.

**Comment by michnovka** [comment]
Ive added my email to the github, you can merge. Im doing it for the humanity, not the credits anyways ;]

**Pull request merged**
