### PR TITLE
Add message to NonUniqueResultException

### PR DESCRIPTION
**Pull request by Alfredao**

### CODE REVIEW

**Comment by Ocramius** [comment]
@Alfredao can you please add a minimal unit test for this? Although the code is brutally simple, it is still a requirement.

**Comment by Alfredao** [comment]
Hello @Ocramius 

Today a coworker asked me for help identifying what was wrong with his code. No error message was displayed. Then I realized that this was about this exception with no text message

As he is starting with Doctrine developmet, it could have been difficult for him to identify the problem by himself

This PR has been open for a long time. Will the merge be done? Is there anything that needs to be done yet?

Thank you!

**Comment by Ocramius** [comment]
@Alfredao didn't see that tests were pushed: added milestone, will check it as soon as possible

**Comment by lcobucci** [comment]
@Alfredao @Ocramius I've rebased this branch but made a small mistake so I'm opening a new PR with your changes.

**Pull request closed without merging**
