### PR TITLE
[DDC-3343] Entities should not be deleted when using EXTRA_LAZY and one-to-many

### PR DESCRIPTION
**Pull request by asprega**
Here's a failing test case for the issue I filed a few days ago: http://www.doctrine-project.org/jira/browse/DDC-3343

Notifying @Ocramius.

### CODE REVIEW

**Comment by asprega** [comment]
@Ocramius any updates? do you want me to propose a fix?

**Comment by Ocramius** [comment]
@asprega I didn't check this yet

**Comment by Ocramius** [comment]
Moved to #1281

**Comment by Ocramius** [comment]
Handled in #1281 and #1282

**Pull request closed without merging**
