### PR TITLE
Refator array_map into simple loop for performance

### PR DESCRIPTION
**Pull request by beberlei**
Alternative to more complex performance refactoring in #11316 

This already reduces performance overhead measured by Tideways by 56%. It shows again how expensive array_map is vs a simple foreach in performance sensitive code path.

Bildschirmfoto 2024-03-02 um 17 35 22

Related to https://github.com/doctrine/orm/issues/11087

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]
🤯

**Review by derrabus — APPROVED** [review]
TIL

**Comment by mpdude** [comment]
_ties a knot into his handkerchief_

**Comment by michnovka** [comment]
Wouldn't it make sense to ban array_map with phpcs and remove all usage in all places of the code? I see it is used in SqlWalker, BasicEntityPersister, ReflectionPropertiesGetter, hydrators and other places

**Pull request merged**
