### PR TITLE
Fatal error with empty primary key in table definition

### PR DESCRIPTION
**Pull request by aschempp**
I'm using the `DatabaseDriver` but used `setTables` to add table information. This can result in the following error because the return value of `Doctrine\DBAL\Schema\Table:getPrimaryKey` can be `null`.

```
Fatal error: Call to a member function getColumns() on null in .../lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php on line 511
```

PS: While working on a test case I also figured out there is no test for a missing primary key in general.

### CODE REVIEW

**Comment by aschempp** [comment]
Any information in this PR?

**Comment by guilhermeblanco** [comment]
Borrowed from StackOverflow: 

> A table should have a primary key so that you could identify each row uniquely with it.
> 
> Technically, you can have tables without a primary key, but you'll be breaking good database design rules.

This means what you want is a bad design decision incorporation into Doctrine. We strive to advocate good standards and you *really* create PK before reverse engineering your database.

Closing as "won't fix".

**Comment by aschempp** [comment]
I might agree with the wrong DB design, thats probably something I can fix in my schema.

Nonetheless I think the case should be handled and not call a method on a non-object. If non-primary key tables are not supported, then the `hasPrimaryKey()` check I added should throw an exception instead of returning an empty array. If you agree I can update the PR.

**Comment by guilhermeblanco** [comment]
Please do it... breaking code is not nice. We should always ensure we have consistent state to perform operations! =)

**Comment by aschempp** [comment]
It's been a while, so I looked into this again, and it feels weird:

[`Doctrine\DBAL\Schema\Table::getPrimaryKey()`](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Table.php#L684) will return `null` if there is no primary key. That probably makes sense as it's only the schema definitions, which does support non-primary-key tables.

However, that methods calls [`getIndex()`](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Table.php#L740-L748) which throws a `SchemaException` if the index is not found. The current [`DatabaseDriver::getTablePrimaryKeys()`](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php#L505-L514) would catch this exception and return an empty array for the primary key. So that means if I implement as discussed, an undefined primary key would throw an exception, but a defined primary key who's index does not exist would not. That can't be right?

So either we need to remove the existing exception catching or add the code I already suggested?

**Pull request closed without merging**
