### PR TITLE
Add a EntityRepository#createQuery() method

### PR DESCRIPTION
**Pull request by wouterj**
This is usefull when you don't want to use a query builder in a custom repository.

### CODE REVIEW

**Comment by WouterJ** [comment]
Just got someone else asking for this on IRC: "*I want to write dql directly in my repository but can't find out how to do. Tried $this->createQuery('myDQL'), tried $this->createQueryBuilder()->createQuery('myDQL')*"

I don't think it's obvious where to find this method to create DQL queries in a custom entity repository. It seems to only have a `->getQueryBuilder()` method.

I think the current way (using `$this->_em->createQuery('...')`) isn't really good DX.

**Comment by Ocramius** [comment]
> I think the current way (using `$this->_em->createQuery('...')`) isn't really good DX.

They should just write their own custom repository class and not rely on `EntityManagerInterface#getRepository()`, tbh

**Comment by WouterJ** [comment]
Hmm, so you suggest people to write their own classes without extending `EntityRepository` or using `Manager#getRepository()` ?

**Comment by Ocramius** [comment]
> you suggest people to write their own classes without extending `EntityRepository` or using `Manager#getRepository()`

Yes, that's indeed what I suggest for the non-pragmatic approach.

The pragmatic approach is good enough with `$this->_em`

**Pull request closed without merging**
