### PR TITLE
Fix the "Erroneous data format for unserializing" error message

### PR DESCRIPTION
**Pull request by marmotz**
cf http://www.doctrine-project.org/jira/browse/DDC-3120

### CODE REVIEW

**Comment by kwisatz** [comment]
The problem also occurs on build #50607

**Comment by mickael-moreau** [comment]
+1

**Comment by Ocramius** [comment]
@kwiateusz I can't seem to find that build?

**Comment by Ocramius** [comment]
This is already resolved btw

**Comment by kwiateusz** [comment]
@Ocramius what do u want from me? I don't post on this issue...

**Comment by mickael-moreau** [comment]
http://www.doctrine-project.org/jira/browse/DDC-3120

**Comment by Ocramius** [comment]
> @Ocramius what do u want from me? I don't post on this issue... 

@kwiateusz github auto-complete fail, sorry

**Comment by kwisatz** [comment]
Might be a debian-specific build:
libapache2-mod-php5: 5.6.7+dfsg-1 0

**Comment by mickael-moreau** [comment]
vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
use @ before unserialise make all work fine, otherwise I Have not array type errore. Working code for me at this time : 
```
    public function newInstance()
    {
        if ($this->_prototype === null) {
            $this->_prototype = @unserialize(sprintf('O:%d:"%s":0:{}', strlen($\
this->name), $this->name));
            if ($this->_prototype === false) {
                $this->_prototype = @unserialize(sprintf('C:%d:"%s":0:{}', strl\
en($this->name), $this->name));
            }
        }

        return clone $this->_prototype;
    } 
```

**Comment by Ocramius** [comment]
@mickael-moreau you are using an old version of the lib there, as far as I can see.

**Comment by Ocramius** [comment]
Locking this thread: please check your library version before commenting further.

**Pull request merged**
