### PR TITLE
Fix PrePersist EventListener when using merge instead of persist

### PR DESCRIPTION
**Pull request by moroine**
The merge operation trigger PRE_PERSIST & POST_PERSIST events when we merge a new entity.

The bug that I encounter, is that the PRE_PERSIST event is trigger with the managed copy empty ! I that case my event listener can't access original data.

In order to fix this, I firstly merge entity state into managed copy. I think this is not the best move as it will be copied a second time at line 1888.

I tried to persist after this is done, but it break some unit tests.

### CODE REVIEW

**Comment by moroine** [comment]
@Ocramius I think this is a Bug on merge operation which is critical in my case :/

**Comment by moroine** [comment]
@DHager, @Ocramius any update on this PR ? I think this is a really bad issue

**Comment by moroine** [comment]
@Ocramius I wonder about this PR which seems to be ready. What about merging it ?

**Comment by moroine** [comment]
@Ocramius great thing that 2.5.5 especially with fixed spl_hash_object conflict on merge ! 

I would like to know what about this PR, this is removed from 2.5.5 but this would be on the next one or just delay as this is not in the top of the TODO ? 

Thank You !

**Comment by Ocramius** [comment]
@moroine I had actually looked at the PR, but then didn't manage to review the details (or specifically, the "cause") in time. Let me put a 2.5.6 on it.

**Comment by moroine** [comment]
@Ocramius I made a mistake on my fork repository that closed this PR :'( 

I've created a new one https://github.com/doctrine/doctrine2/pull/6174 that treat about a similar bug but also fix that one ! 

Could you check this other PR and may be schedule for the v2.5.6 also ? 

Thank You a lot

**Comment by Ocramius** [comment]
Moved to #6177, applied fixes locally, rewrote the tests to reduce cross-test dependencies. 👍

**Pull request closed without merging**
