### PR TITLE
small fix - `as` in lowercase

### PR DESCRIPTION
**Pull request by vv12131415**

### CODE REVIEW

**Comment by Ocramius** [comment]
@doctrine/team-coding-standards can you check this, please?

**Review by Majkl578 — APPROVED** [review]

**Comment by Majkl578** [comment]
This is [part of PSR-2](https://github.com/squizlabs/PHP_CodeSniffer/blob/4cb6b53c3c1cfcecc6c361508ebd8de0c613e351/src/Standards/PSR2/ruleset.xml#L69-L70) which [we use](https://github.com/doctrine/coding-standard/blob/4.0.0/lib/Doctrine/ruleset.xml#L5) as our base set of rules. Unfortunately we have no linter for RST. :/

**Review by carusogabriel — APPROVED** [review]

**Review by jwage — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by Majkl578** [comment]
Don't know if that's possible, but having a PHPCS check code snippets in our docs would rock. Definitely out of scope here though. :)

**Comment by Majkl578** [comment]
Hmm, Travis is really weird these days. :(

**Comment by Ocramius** [comment]
Travis passed - disabling checks, merging and re-enabling them.

**Pull request merged**
