### PR TITLE
Merge 2.7 into 2.10.x

### LINKED ISSUE #4257: DDC-3449: Single scalar Result and Hidden field
Jira issue originally created by user tgallice:

I have try to get a single scalar result but my query contains a HIDDEN field. The result is the `NonUniqueResultException` exception.

### LINKED ISSUE #7512: findBy broken for inherited entity property lookups
### Bug Report

| Q.                 |   A
|------------ | ------
| BC Break     | no
| Version        | 2.6.3

#### Summary

findBy does not work correctly for inherited entities. proof here: https://github.com/themizzi/doctrine-find-by-metadata-bug

#### Current behavior

If EntityB has a OneToMany relationship to EntityA, and EntityC inherits (via join) from EntityA. If there is no cache, calling `$entityBRepo->findBy('entityA' => $newEntityCInstance)` works fine. On a subsequent request after cache has already been generated and metadata is lazy loaded, the request breaks. on sqlite this just fails, on MySQL this potentially loads up an incorrect entity.

#### How to reproduce

Please see link above for an example and reproduction steps.

#### Expected behavior

Find by can find classes by properties with an inheritance structure at all times.

### PR DESCRIPTION
**Pull request by greg0ire**
2.7 should never have existed, things that have been merged into it have been lost (and were never released).

Fixes #4257 
Fixes #7512
Closes #7514

### CODE REVIEW

**Comment by greg0ire** [comment]
I need to rebase this

**Comment by greg0ire** [comment]
@Mediagone please review

**Comment by greg0ire** [comment]
ping @Mediagone @beberlei

**Review by SenseException — APPROVED** [review]
I can recognize #8340, plus coding style and analysis fixes.
#7514 is also there, even though comparing `BasicEntityPersister` with the original one was more to read because of the early exit changes with the `return`.

**Pull request merged**
