### PR TITLE
Work around some reflection bugs whose fixes cause test failures

### PR DESCRIPTION
**Pull request by mbeccati**
For more info:
https://bugs.php.net/bug.php?id=72174
https://bugs.php.net/bug.php?id=72209

### CODE REVIEW

**Comment by Ocramius** [comment]
@mbeccati the bug is in the test suite: this should not silently fail at all

**Comment by mbeccati** [comment]
Of course the proper fix would be not to try and fetch the value of a non-existing property

**Comment by mbeccati** [comment]
@Ocramius yup, feel free to reject it ;)

**Comment by Ocramius** [comment]
> Of course the proper fix would be not to try and fetch the value of a non-existing property

No, what I mean is that the `ClassMetadata` instance used by the test suite is wrong.

This patch fixes the symptom, not the cause.

I know you see these failures due to the CI, but this patch is invalid as-is, and will hit us once 7.0.7 or 7.1.0 are out.

**Comment by Ocramius** [comment]
Note: keeping it open due to the fact that the problem is actually clearly described here

**Comment by Majkl578** [comment]
We now require PHP 7.1+, this is not relevant anymore.

**Pull request closed without merging**
