### PR TITLE
Address method rename

### PR DESCRIPTION
**Pull request by greg0ire**
See https://github.com/doctrine/dbal/pull/5724

### CODE REVIEW

**Comment by derrabus** [comment]
LGTM, but we could could do this in 2.14.x already.

**Review by derrabus — APPROVED** [review]

**Comment by greg0ire** [comment]
@derrabus I thought of this, and it cannot be tested properly unless we use an unstable version of DBAL on 2.14. My current plan is to do a single backporting PR with all the other relevant changes when the next minor of the DBAL is released, but I'm unsure about this, let me know how you think we should handle this.

**Comment by derrabus** [comment]
But we DO test 2.14. with DBAL `3@dev`, don't we?

**Comment by greg0ire** [comment]
Oh right, I missed that. I'll do that backporting PR soon then 👍

**Pull request merged**
