### PR TITLE
[3.0] Moved IdentifierGenerator to Property.

### PR DESCRIPTION
**Pull request by guilhermeblanco**

### CODE REVIEW

**Comment by Ocramius** [comment]
@guilhermeblanco a lot of this seems to be incomplete though - especially the `'FIXME'` skipped tests :S

**Comment by guilhermeblanco** [comment]
@Ocramius We're pairing to address things here... =)

**Comment by Ocramius** [comment]
Gotcha

**Comment by guilhermeblanco** [comment]
@Majkl578 I've reverted the PR since it I didn't realize until now that there're 100 tests failing. =\
Once you reach all tests passing, then I'll look again.

**Pull request merged**
