### PR TITLE
Drop support for unserializing old serialization formats

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by derrabus** [comment]
Should we keep the test for the 2.15 format? It's still the current one, isn't it?

**Review by mpdude — DISMISSED** [review]

**Review by morozov — DISMISSED** [review]

**Review by SenseException — DISMISSED** [review]
> Should we keep the test for the 2.15 format? It's still the current one, isn't it?

Should it be renamed?

**Comment by greg0ire** [comment]
> Should it be renamed?

I don't think so, if it does not change.

**Comment by greg0ire** [comment]
Note that this removes txt files that I should have removed in my last merge up.

**Review by SenseException — APPROVED** [review]

**Pull request merged**
