### PR TITLE
Fix ignoring custom types for PersistentCollection matching()

### LINKED ISSUE #8995: Cannot use criteria matching with entities where the primary key is a binary ULID
I'm trying to do an efficient join using criteria in one of my entities like:

```php
    /**
     * @ORM\Id()
     * @ORM\Column(type="ulid", unique=true)
     */
    private Ulid $id;

    /**
     * @var Collection<User>
     * @ORM\ManyToMany(targetEntity="User", mappedBy="teams", fetch="EXTRA_LAZY")
     */
    private Collection $users;

    public function getMemberSample(): Collection
    {
        $criteria = Criteria::create()
            ->orderBy(['lastName' => 'ASC'])
            ->setMaxResults(5)
        ;

        return $this->users->matching($criteria);
    }
```

However the query doctrine creates is:

```sql
SELECT te.id AS id, te.first_name AS first_name, te.last_name AS last_name FROM users te JOIN user_teams t ON t.user_id = te.id WHERE t.team_id = '01EP7GVKX9K05ZK8G9ZRZTTW3N' ORDER BY last_name ASC LIMIT 5;
```

As you can see it has just turned the ULID into a string which won't match the binary.

I feel like this maybe come from `vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php`

```php
    /**
     * {@inheritDoc}
     */
    public function loadCriteria(PersistentCollection $collection, Criteria $criteria)
    {
        $mapping       = $collection->getMapping();
        $owner         = $collection->getOwner();
        $ownerMetadata = $this->em->getClassMetadata(get_class($owner));
        $id            = $this->uow->getEntityIdentifier($owner);
        $targetClass   = $this->em->getClassMetadata($mapping['targetEntity']);
        $onConditions  = $this->getOnConditionSQL($mapping);
        $whereClauses  = $params = [];
        if (! $mapping['isOwningSide']) {
            $associationSourceClass = $targetClass;
            $mapping                = $targetClass->associationMappings[$mapping['mappedBy']];
            $sourceRelationMode     = 'relationToTargetKeyColumns';
        } else {
            $associationSourceClass = $ownerMetadata;
            $sourceRelationMode     = 'relationToSourceKeyColumns';
        }
        foreach ($mapping[$sourceRelationMode] as $key => $value) {
            $whereClauses[] = sprintf('t.%s = ?', $key);
            $params[]       = $ownerMetadata->containsForeignIdentifier
                ? $id[$ownerMetadata->getFieldForColumn($value)]
                : $id[$ownerMetadata->fieldNames[$value]];
        }
```

Where maybe the `$params[]` being created here isn't using the binary value.

Anyone know where this bug might lie who knows a bit more about how it work, I'm also not sure who is responsible, Doctrine ORM, Doctrine Bundle, Symfony Uid...

### PR DESCRIPTION
**Pull request by sztyup**
Fixes https://github.com/doctrine/orm/issues/8995, https://github.com/doctrine/orm/issues/8406, https://github.com/doctrine/orm/issues/7822

### CODE REVIEW

**Comment by greg0ire** [comment]
@jdelaune @n3o77 @hubertnnn please test this patch

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
No answer… oh well, let's merge! Thanks @sztyup !

**Comment by armenio** [comment]
Is this related to that https://github.com/doctrine/orm/issues/9109 ?

**Comment by armenio** [comment]
> No answer… oh well, let's merge! Thanks @sztyup !

@sztyup please take a look at https://github.com/doctrine/orm/pull/9109
cc @greg0ire

**Pull request merged**
