### PR TITLE
fix: always cleanup in `AbstractHydrator::toIterable()`

### PR DESCRIPTION
**Pull request by simPod**
Related to #6480

Closes https://github.com/doctrine/orm/pull/11419

### CODE REVIEW

**Comment by derrabus** [comment]
Can we please add a test?

**Comment by oleg-andreyev** [comment]
@derrabus @simPod  please take a look https://github.com/doctrine/orm/pull/11419

**Comment by simPod** [comment]
@oleg-andreyev thank you. I have incorporated your test into the PR and cleaned it up.

**Comment by simPod** [comment]
@derrabus psalm failures seems irrelevant

**Comment by greg0ire** [comment]
@simPod you are targeting an unmaintained branch.

**Comment by greg0ire** [comment]
Retargeted, please address the conflicts.

**Comment by simPod** [comment]
done, thanks

**Comment by greg0ire** [comment]
No more Psalm failures :)

**Comment by greg0ire** [comment]
Please squash both commits and improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches).

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
While you're at it, please add the author of the test using a [`Co-authored-by` trailer](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

**Comment by simPod** [comment]
sure, done

**Comment by derrabus** [comment]
Thank you!

**Pull request merged**
