### PR TITLE
Update ordered-associations.rst

### PR DESCRIPTION
**Pull request by spirlici**
Fixed some typos

### CODE REVIEW

**Comment by kojiDev** [comment]
Do these kind of PRs live for 23 days because they are small and contributors don't think it's valuable to merge or because no one reviewed it?

**Comment by Ocramius** [comment]
@kojiDev mostly nobody on the team having capacity for working on issues these days, sorry :-\

**Review by phansys — APPROVED** [review]

**Review by Ocramius — APPROVED** [review]

**Comment by kojiDev** [comment]
@Ocramius I'm not like super free or very experienced of a developer, but something like typos I can review, tho I'm not asking for any privileges, nor I want to. I'd rather just review stuff and draw somebody's attention to it if that's fine.

**Comment by Ocramius** [comment]
@kojiDev going through issues and reviewing would be extremely helpful, if you can throw some effort at it. Next time I'll get to work on D2 will be in a couple weeks, I think.

**Pull request merged**
