### PR TITLE
[DDC-3640] Feature to force-increment entity version

### PR DESCRIPTION
**Pull request by DHager**
Status: Blocked waiting on #1380
- [x] Configuration mechanisms
  - [x] Annotations
  - [x] YAML
  - [x] XML
- [x] Handle inheritance (`JoinedSubclassPersister`)
- [x] Avoid double-updating entities that have "real" changes
- [x] Fix separate bug in test-code so that build succeeds again (#1380)

The major use-case for this involves using certain entities as the versioned-gatekeepers for changes that don't directly live on the same entity. For example, using the version of a `PurchaseOrder` to control changes to any of its child `PurchaseOrderLineItem` objects.

### CODE REVIEW

**Comment by zeroedin-bill** [comment]
Wouldn't cascade persist accomplish the same thing?

**Comment by DHager** [comment]
@zeroedin-bill I don't think so. Doctrine might be aware that `PurchaseOrder` is a managed entity, but since none the entity's fields are changing, it wouldn't update the version number.

The problem can be restated as "This entity's version must update when any changes happen to certain other entities that are somehow related", which seems like something way beyond Doctrine's scope, off in the realm of business-logic. (Plus, what if there are non-DB changes involved, like webservice calls?)

**Comment by DHager** [comment]
BTW, given that naming things is one of those hard computer science problems, I'm open to any suggestions.

The obvious one is `@VersionBump`. It basically means: "This PHP property will trigger behavior when it is `true`, and may be directly reset to `false` by Doctrine. It should only be used on entities that have an `@Version` annotation, and signals that the version *must* be updated on the next flush."

Some of the implementation uses phrases like "version update property", because calling it a "field" might wrongly suggest that it maps to some database column like most of the other "field"-related stuff.

**Comment by DHager** [comment]
I hope I've made the right kind of changes needed to test `BasicEntityPersister`. Right now it is testing when the base class has versioning/bumping, but another possible test would be where a subclass has it alone. 

`SingleTablePersister`  may need some tests, but I'm hopeful that it'll inherit all the needed behavior.

**Comment by DHager** [comment]
Opened new issue #1380 to address the build-failure I'm now seeing.

**Comment by DHager** [comment]
@Ocramius Any comments on this feature? Code-wise I think it's ready for some review. I believe the build-failure is a separate issue, involving how the test-harness tests the second-level cache.

**Comment by DHager** [comment]
So... anybody? Comments? Complaints? Questions about the use-case? Desire to do the configuration differently?

**Comment by Ocramius** [comment]
I didn't check anything related D2 this month (except security), sorry.

**Comment by DHager** [comment]
Are there any existing/future features that may require the same kind of configuration?

**Comment by DHager** [comment]
What's the etiquette for bumping this? Should I be drumming up interest in the IRC room?

**Comment by DHager** [comment]
@Ocramius : Does the use-case for this at least seem valuable? It allows user-land code to update the version of an entity to reflect indirect changes in its child/grandchild/etc. relations. For example, the version of a `Product` when you make changes to the text of one of its internationalized `ProductDescription` entities.

**Comment by zeroedin-bill** [comment]
@DHager The use-case seems good, I just wonder if there's a way to do this that touches less code and bloats the ClassMetadata and UnitOfWork less. If a child relation is configured to cascade persist operations to a parent, and the parent is versioned, it would make sense to me to just increment the version on the parent automatically. That would be a BC break, but it would be a better solution than a bunch of extra flags and methods I think.

**Comment by DHager** [comment]
@zeroedin-bill : I'm pushing for an entity property-flag because:

1. Once you get past the boundary of a single entity or row, the question of "What indirectly counts as a change" becomes murky and dependent on business-logic, rather than something you can encode into the persistence layer.
2. Some persist-linked items will need to have entirely independent versions.
3. For performance reasons, people may use `$em->persist($item)` instead of cascading.

The benefit of this approach is that Doctrine does not need to know where version means or what it covers, it simply has to notice a single little boolean flag on the entity. All the complicated "if this change that" logic is higher up, in the user's application.

> I just wonder if there's a way to do this that touches less code and bloats the ClassMetadata and UnitOfWork less. 

It may be possible to reduce the line-count by weaving the bumping-logic into the same parts that do updates, but having it as a separate step--for entities not already updated for other reasons--seemed like it would introduce fewer complications.

**Comment by zeroedin-bill** [comment]
@DHager: the issue outlined here is an important one, and needs to be addressed. 

This PR is not the right way to go about it though, for a number of reasons. Primarily, entity versioning should be transparent to userland. The entity version should be read by userland code, but should not be manipulated artificially by it. Only the persistence layer should affect the version. The changes you've made are unnecessary if versioning behavior can be modified to provide better default behavior.

I've outlined a solution more in line with behavior implemented by other ORMs in [DDC-3781](http://www.doctrine-project.org/jira/browse/DDC-3781).

Thanks for your work on the issue.

**Comment by DHager** [comment]
Well, if that's the route you want to go... I believe some of the UoW/Persister changes may still be worth looking at, since we probably want the same kind of outcome, just with a different form of configuration and triggering.

**Comment by DHager** [comment]
@zeroedin-bill : Would you be OK with me starting a new PR that contains just the supporting infrastructure for bumping a version on an entity that has no "direct" changes? 

It would not involve any configuration directives, but would instead expose the behavior through something like `$uow->scheduleForVersionBump()`. 

This would allow multiple solutions to be prototyped with custom `onFlush` subscribers, and my own use-case could be solve while waiting for [DDC-3781](http://www.doctrine-project.org/jira/browse/DDC-3781) to provide a definitive out-of-the-box solution.

**Pull request closed without merging**
