### PR TITLE
Consider usage of setFetchMode when checking for simultaneous usage of fetch-mode EAGER and WITH condition

### LINKED ISSUE #11128: setFetchMode() is ignored - Exception eager Fetch Join With Not Allowed
```
Entity/Category.php

#[ORM\Entity]
class Category
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private int $id;

    #[ORM\ManyToOne(targetEntity: 'Category', fetch: 'EAGER')]
    #[ORM\JoinColumn(name: 'root_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    private ?Category $root = null;
}
```

Query
```
$qb = $this->createQueryBuilder('content')
            ->join('content.category', 'category')
            ->join('category.root', 'categoryRoot', Expr\Join::WITH, 'categoryRoot = :root')
            ->setParameter('root', $host->getCategory());

$query = $qb->getQuery();
$query->setFetchMode(Category::class, 'categoryRoot', ClassMetadata::FETCH_LAZY);
```

Result
```
Doctrine\ORM\Query\QueryException

Associations with fetch-mode=EAGER may not be using WITH conditions in
             "[App\Entity\Category]"
```

There should be check over SqlWalker::getQuery()->getHint('fetchMode') in case you override fetchMode()
Maybe there is a bug in $relation->fetch, where fetchMode should be propagated from hints?

```
if ($relation->fetch === ClassMetadata::FETCH_EAGER && $condExpr !== null) {
            throw QueryException::eagerFetchJoinWithNotAllowed($assoc->sourceEntity, $assoc->fieldName);
}
```

https://github.com/doctrine/orm/blame/28d03e41f7b58781c516404bf179806e10a84ec5/lib/Doctrine/ORM/Query/SqlWalker.php#L897

Maybe related with
https://github.com/doctrine/orm/issues/7860

### PR DESCRIPTION
**Pull request by aprat84**
Fixes #11128.
Copy of #11174, author can't complete it right now.

Should be merged up to v3.1

### CODE REVIEW

**Comment by aprat84** [comment]
@beberlei dunno if u prefer to continue here and close #11174 or wait for the author...

**Comment by aprat84** [comment]
Can this get a little more attention?
It's a **fix for a BC** introduced lately...

**Comment by krzysztof-ciszewski-tg** [comment]
Bumping since this is a big deal

**Review by greg0ire — DISMISSED** [review]

**Review by SenseException — DISMISSED** [review]
Footnote: The test method names are hard to understand in that class if you don't know the context.

**Comment by greg0ire** [comment]
Retargeting since this is a bugfix.

**Comment by ottaviano** [comment]
Thank you for this fix, @Abbraxar & @aprat84 👍

**Pull request merged**
