### PR TITLE
Fix enum IDs in association mappings

### LINKED ISSUE #10132: Enum fields can't be an id field.
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.3

#### Summary

Id Field with enumType is not working.

#### Current behavior

I have a entity called "display" with a primary key over multiple columns:
[id] int feedback_id (relation to feedback)
[id] string with enumType identity_type
string identity_id

There also is a parent entity called "feedback" with the following columns:
[id] int id
collection<display> displays  (relation to display)

When I query for a entry from feedback with a join to displays, this call failes when done a second time, with:
Object of class App\Entity\IdentityType could not be converted to string
in vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:286

It is caused by this code:
```
foreach ($class->identifier as $fieldName) {
                $idHash .= ' ' . (isset($class->associationMappings[$fieldName])
                    ? $data[$class->associationMappings[$fieldName]['joinColumns'][0]['name']]
                    : $data[$fieldName]);
            }
```
not expecting $data[$fieldName]) to be an enum.

#### Expected behavior

Support for enum fields as index.

### PR DESCRIPTION
**Pull request by michnovka**
Attempt to fix https://github.com/doctrine/orm/issues/10132

### CODE REVIEW

**Comment by michnovka** [comment]
@greg0ire please review, this fixes a very specific case where we are using complex associations to entities with one or more ID columns, one of which is an enum.

My original thought was to use identifierFlattener like this:

```php
$associatedIdFlattened = $this->identifierFlattener->flattenIdentifier($targetClass, $associatedId);
$relatedIdHash         = implode(' ', $associatedIdFlattened);
```

here - https://github.com/doctrine/orm/blob/20d6c53f299fc97997939671dd5ae8544c9e7e11/lib/Doctrine/ORM/UnitOfWork.php#L2850

But when running tests, this created some issues and BC breaks. I this this fix is sufficient. Other cases (like a single enum ID not part of association) already use checks like this

**Comment by greg0ire** [comment]
Please squash your commits together and use a commit message as good as this one: 9d5ab4ce763810f42d2079bf42b8bf48264ffa5c
You can read [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches) to get guidelines rather than an example.

**Comment by greg0ire** [comment]
> a very specific case where we are using complex associations to entities with one or more ID columns, one of which is an enum

In your test, all 3 entities have the enum appear in the primary key, is that required to reproduce the issue?

**Comment by michnovka** [comment]
@greg0ire 

> In your test, all 3 entities have the enum appear in the primary key, is that required to reproduce the issue?

It is not required, but I did like the complex structure of the example as it works through 2 levels of association instead of just one.

**Comment by michnovka** [comment]
I have reduced the example entity to a minimum and provided a nice commit message.

@greg0ire please review

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @michnovka !

**Pull request merged**
