### PR TITLE
Fixed DDC-3740

### PR DESCRIPTION
**Pull request by StoshSeb**
The count must return an integer, not a string

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
What if count returns > PHP_INT_MAX?

**Comment by DHager** [comment]
Well, what's the contract/use-case for the method? My default assumption would be integers, for the use of looping, division to determining how many (also integer) pages are needed, etc.

**Comment by guilhermeblanco** [comment]
I'd suggest casting to float/double if really desired... but I'd still stick to strings.
You can already cast this in userland, and we always dealt with large integers as strings anyway.

**Comment by guillaumesmo** [comment]
Although I agree that the count shouldn't be narrowed down to PHP_INT_MAX, I would either:
update the documentation accordingly; or
be consistent with what other persisters (e.g. Doctrine\ORM\PersistentCollection in the lazy case) do

**Comment by mpscholten** [comment]
Any updates on this?

If that's not getting merged, maybe the documentation can be updated to better point out this very unintuitive behavior. Currently the documentation says that e.g. `LazyCriteriaCollection::count` returns an integer. That's wrong as it's returning a string.

**Pull request merged**
