### PR TITLE
Make "targetEntity must not be a mapped superclass" a lazy check

### PR DESCRIPTION
**Pull request by mpdude**
#10473 relaxed the runtime check that mapped superclasses must not use one-to-many associations. It turned the check the other way round, so that no mapped superclass may be used as the `targetEntity` of an association.

To find out whether a class is a mapped superclass, the `\Doctrine\ORM\Mapping\ClassMetadataFactory::peekIfIsMappedSuperclass` method was used, which is directly using the mapping driver.

#10552 reports a case where mapping configuration is not collected through the driver alone, but also a metadata listener is contributing relevant information. Updating metadata with a listener is currently not supported by the check in that method.

Also, https://github.com/doctrine/orm/pull/10473#issuecomment-1450048660 has a mapping configuration that cannot be loaded in the improvised way that `\Doctrine\ORM\Mapping\ClassMetadataFactory::peekIfIsMappedSuperclass` employs.

As I explained in https://github.com/doctrine/orm/issues/10552#issuecomment-1450794332, we cannot use the full ClassMetadataFactory itself to obtain information about the `targetEntity` while we're performing runtime validation for another class currently being loaded.

So, I don't see any other way than to make this check a non-runtime (offline?) check in the `SchemaValidator`. There, we can first completely load metadata for all classes and then inspect it.

Many fixes to the test models that were made in #10473 can be reverted, since these files are no longer scrutinized at runtime, and we probably don't care about the extra validation checks that much.

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]
I did not have a look at the code as I'm not unfamiliar with internals here but this PR fixes our problems inside @sulu: https://github.com/sulu/sulu/pull/7026

Thank you @mpdude 👍

**Review by BreyndotEchse — APPROVED** [review]
MappingException gone and all tests passed!
ty @mpdude

**Comment by mpdude** [comment]
Doctrine core team reviewers:

Please confirm that using a `SchemaValidator` based check only instead of a runtime check is a valid approach. That's what the schema validator is made for, right? Not all problems can easily be spotted at runtime.

**Comment by mpdude** [comment]
@derrabus, @greg0ire or @SenseException – can we try to get this merged in the near future? I have the impression it would unblock people who are kind enough to try 2.15-dev in their CI pipelines.

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @mpdude !

**Pull request merged**
