### PR TITLE
Added php 8.1 to CI

### PR DESCRIPTION
**Pull request by sir-kain**
Jobs updated:

- phpunit-postgres
- phpunit-mariadb
- phpunit-mysql

### CODE REVIEW

**Comment by derrabus** [comment]
Modifications to the CI should target the lowest maintained branch instead (2.11.x currently). That being said, we already do test on PHP 8.1. Can you elaborate why you wanted to change the PHP version on those jobs specifically?

**Comment by sir-kain** [comment]
> Modifications to the CI should target the lowest maintained branch instead (2.11.x currently). That being said, we already do test on PHP 8.1. Can you elaborate why you wanted to change the PHP version on those jobs specifically?

I saw that `phpstan`, `phpcs`, `psalm`, ... PHP version are all on `8.1` on the CI and I wanted to use the same version everywhere by default.

**Review by greg0ire — DISMISSED** [review]
So the question is, what should we use for testing platform-specific code? The answer is probably: either the lowest or the highest PHP version. To me, it makes sense to use the highest here, as we are more likely to be using DBAL code we have never been exposed to that way, and catch new bugs.

**Comment by greg0ire** [comment]
> we are more likely to be using DBAL code we have never been exposed to that way, and catch new bugs.

The build is failing, is that what is happening here? :sweat_smile: 

EDIT: the failing test is `Doctrine\Tests\ORM\Functional\ReadonlyPropertiesTest`, which is probably why this wasn't caught before (that test did not run at all for PostgreSQL)

**Comment by greg0ire** [comment]
This is why https://github.com/doctrine/orm/pull/8931 is important

**Review by derrabus — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @sir-kain !

**Pull request merged**
