### PR TITLE
Update custom-mapping-types.rst

### PR DESCRIPTION
**Pull request by glhms**
If you run tests, it will add type multiple times, because its static.

you must check if its already added.

### CODE REVIEW

**Comment by greg0ire** [comment]
It says "in bootstrapping code", and I think that implies this piece of code is only supposed to be run once.

**Comment by glhms** [comment]
Lets say you put it in the kernel constructor, which should run only once.

If you run multiple test cases, it makes new kernel, and everything is running again.

But the types are saved between test cases, because its static.

In the second test you will get a mapping exception because your type is already added.

Also, we can simply check if it is already added with Type::hasType(), then we do not need array_key_exists().

**Comment by greg0ire** [comment]
> Lets say you put it in the kernel constructor, which should run only once.

As you yourself said, it does not run only once, and thus does not qualify as bootstrapping code. In a phpunit context, bootstrapping code will be understood as running once too: https://phpunit.readthedocs.io/en/8.4/configuration.html#the-bootstrap-attribute

What you are describing is code running on `setUp`, not because of `bootstrap`.

**Review by SenseException — CHANGES_REQUESTED** [review]
As @greg0ire mentioned before this code is supposed to be put into a bootstrapper, that is only run once. This should be enough information for the ORM documentation. But it is only mentioned as a code comment and I suppose not everyone might be familiar with a "bootstrap" concept.

@glhms Can you please add a description that this has to be added into bootstrapping code and that bootstrapping code is supposed to run only once? This way we don't need to adapt the code example with an if-block like you introduced first. The new description addition should be added before the code example.

**Pull request closed without merging**
