### PR TITLE
Update EntityGenerator add method template

### PR DESCRIPTION
**Pull request by Arthurhall**

### CODE REVIEW

**Comment by aivus** [comment]
Why do you want to change `[]` on `add()` call?

**Comment by Arthurhall** [comment]
Because it is not an array but an ArrayCollection, it's more obvious like this i think.

**Comment by DHager** [comment]
I think using arrays (when they should be using `Collection`) is probably a common misstep for new Doctrine users. Having `->add()` in there makes them less-likely to do it.

**Comment by Majkl578** [comment]
Closing this as we will be removing EntityGenerator in Doctrine 3.0.

**Pull request closed without merging**
