### PR TITLE
[DDC-2524] Wrong commit order with cascade remove and double association

### PR DESCRIPTION
**Pull request by mnapoli**
This PR contains the failing test case for [DDC-2524](http://www.doctrine-project.org/jira/browse/DDC-2524).

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
@mnapoli I'm taking over this PR through a new one, managed by Doctrine itself #1570 including not only your test case, but also another one reported in the ticket (which looks like it was already fixed by my orphanRemoval support on CollectionPersister committed earlier this year.

**Comment by mnapoli** [comment]
:+1: thank you!

**Comment by guilhermeblanco** [comment]
@mnapoli on your second test `testMany`, you actually have a mapping issue.
You have to define the onDelete="SET NULL" because there's no way to control inverse awareness.

Once you change that, you fall back to same error as `testSingle`, which I addressed on #1570

**Comment by mnapoli** [comment]
Good to know. The original code is long gone, but thanks for following up.

**Pull request closed without merging**
