### PR TITLE
Fix selecting multiple entities #8413

### LINKED ISSUE #8413: Issue with toIterable() and selecting multiple entities
My code was previously working and since the last update, all the application is down due to toIterable() returning only the last entity when selecting multiple entities.

At line 179 in AbstractHydrator, Doctrine is doing yield end($result); causing the issue, the call to end() function should not be used.
$result is a simple array containing all retrieved entities, calling end() is just returning the last one.

https://github.com/doctrine/orm/blob/378944dd27c1953440c1797fc02ff4620ca956ea/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php#L179

I tested and the solution is really simple: Just remove the end() call, only yield $result;

This may be related to #8410

### PR DESCRIPTION
**Pull request by Cartman34**
Fix #8413
Now allowing to select multiple entities and return all of them

### CODE REVIEW

**Comment by Cartman34** [comment]
This fix is not enough to really fix issue, it creates another issue.

**Comment by Cartman34** [comment]
Tested selecting one or more entity in one row through several rows. It seems to work in all cases, it only affects iterations.

**Comment by SenseException** [comment]
Thanks for your contribution. Your changes are currently breaking the existing tests. You also need to create a test for your use case.

**Comment by Cartman34** [comment]
> Thanks for your contribution. Your changes are currently breaking the existing tests. You also need to create a test for your use case.

There is no new code, no new function, why should I develop a unit test ?
It's an important fix and I don't know how to do, so anyone do it and push it 😅
The a faulting code was developed recently and pushed without any test...

**Comment by SenseException** [comment]
> There is no new code, no new function, why should I develop a unit test ?

If changes don't fix or introduce anything, like in a refactoring, then there's no need for new tests. There's still the possibility that an assumed harmless change introduced a bug in a functionality, that wasn't covered by tests yet. New tests will close such gaps in the coverage too.

If your code introduces a change, a feature or a bugfix, then a new test has to guarantee that this newly code change is covered. This doesn't have anything to do with new classes or methods, but with code paths. The test should prevent that someone else is removing your fix accidentally (even after months or years). It's in your and the other affected developers' interest that this can be prevented.

**Comment by Cartman34** [comment]
I have no doubt this is very useful and I should provide it but it's out of my knowledges. I developed and shared the fix in a short time but this is a complex test, with probably a solution to mock up the database. I don't have the skills to do that and no time.
So somebody else have to do that.

**Comment by beberlei** [comment]
Superseded by #8467

**Pull request closed without merging**
