### PR TITLE
[WIP] Foreign association index names

### PR DESCRIPTION
**Pull request by jsuggs**
See http://www.doctrine-project.org/jira/browse/DDC-2989

### CODE REVIEW

**Comment by dbykadorov** [comment]
Hello, guys! Is there still work  in progress? Very useful but missed ability...

**Comment by Ocramius** [comment]
@dbykadorov if you want to contribute, then provide tests for this PR

**Comment by Ocramius** [comment]
Closing as per @deeky666's review.

**Comment by Ocramius** [comment]
This is actually fixed as per doctrine/dbal#769, which comes with release 2.5.1 of the DBAL.

**Comment by fmonts** [comment]
> This is actually fixed as per [doctrine/dbal#769](https://github.com/doctrine/dbal/pull/769), which comes with release [2.5.1](https://github.com/doctrine/dbal/releases/tag/v2.5.1) of the DBAL.

Still not fixed since it's not possible to set a custom name for a foreign key. 

There are situations where you don't want to change the FK name, for example when dropping a FK and recreating it is not feasible because the table is huge, or when the db structure is shared between different applications. 

For those coming here trying to find a way to do that, see this workaround: https://stackoverflow.com/a/77736787/3393663

**Pull request closed without merging**
